### ISSUE TITLE
Should add a test for minimum ISA of SSE4.1

### ISSUE THREAD

**Issue by ospray-owner** [ospray/OSPRay#10]
OSPRay run on anything older than SSE4.1, but does not currently report an error when executed on older machines, it just core dumps.

**Comment by ingowald** [comment]
fixed in upcoming 0.8

**Comment by pavolzetor** [comment]
If SSE4.1 is the real minimum, it should be checked instead of SSE4.2 (I have penryn).

**Comment by johguenther** [comment]
Changed with commit cda25446 -- will be in the next release. However, at some point we will really require SSE4.2.
