### ISSUE TITLE
Qt detection requires qmake, rcc, uic which aren't actually used in the build

### ISSUE THREAD

**Issue by yurivict** [ospray/ospray#100]
Without .pro files qmake shouldn't be required. Similarly, without .qrc files rcc shouldn't be required.

When I remove rcc, configure stage fails:
```
-- Looking for Q_WS_MAC - not found
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Qt4 (missing: QT_RCC_EXECUTABLE) (found version "4.8.7")
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/Modules/FindQt4.cmake:1319 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  apps/qtViewer/CMakeLists.txt:23 (FIND_PACKAGE)
```

Same with uic and qmake.

**Comment by jeffamstutz** [comment]
We use the standard, built-in CMake find_package modules for Qt4, so we don't control the CMake code which finds Qt. We aim to keep the maintenance of our sample applications as minimal as possible, which is why we haven't (and will unlikely in the future) implement a different find_package module for Qt.

**Comment by yurivict** [comment]
You use ```FIND_PACKAGE(Qt4 REQUIRED)``` which tests for major parts of Qt4. ```cmake/Modules/FindQt4.cmake``` has documentation explaining how you can test for individual parts of Qt4. For example ```find_package(Qt4 4.4.3 REQUIRED QtGui QtXml)```.

You overtest, this is the problem.

**Comment by johguenther** [comment]
OK. Still: `qmake` is always required, as per `FindQt4` documentation.

**Comment by yurivict** [comment]
cmake-modules requiring qmake is a bug in cmake-modules: https://gitlab.kitware.com/cmake/cmake/issues/16440

I doubt they can easily fix it though, because FindQt4.cmake is written using qmake as a detection tool.

**Comment by jeffamstutz** [comment]
I'm closing this issue as we have decided to consolidate our sample apps into a single app which will not use Qt. Thus this will no longer be relevant in future releases (likely v1.3.0 will remove Qt apps).

Cheers,
Jeff
