### ISSUE TITLE
Missing file: 12_monument_valley.pfm doesn't exist in http://www.pauldebevec.com/Probes/

### ISSUE THREAD

**Issue by yurivict** [ospray/OSPRay#101]
On http://www.ospray.org/demos.html San-Miguel demo refers to lightProbes/12_monument_valley.pfm which isn't in all_probes.tar.gz mentioned in http://www.pauldebevec.com/Probes/

Please replace the link with one that contains the file.

**Comment by carsonbrownlee** [comment]
Hi, thanks for letting us know about that, I will update the instructions.  Any pfm light image from all probes should work pretty well.

**Comment by carsonbrownlee** [comment]
Updated website
