### ISSUE TITLE
USE_IMAGE_MAGICK options should be ON by default since they are required for colors to appear correctly

### ISSUE THREAD

**Issue by yurivict** [ospray/OSPRay#105]
Defaults of ```USE_IMAGE_MAGICK``` and ```OSPRAY_USE_IMAGE_MAGICK``` should be ON.

**Comment by carsonbrownlee** [comment]
I'm adding big notices to the website demos now, obviously we will need to make this more intuitive.
Ideally we want to limit the number of default dependencies- the example apps are purely just for tutorial purposes, the OSPRay library itself does not require ImageMagick.  That said, it will obviously lead to a lot of confusion and headaches if our first tutorials require custom build options.  We will likely either bundle imagemagick with the binaries or try to find a header only library that can deal with the myriad of file types.  @jeffamstutz thoughts?

**Comment by yurivict** [comment]
So what part is for tutorial purposes, the whole bin/ospGlutViewer or only parts of it? If the whole bin/ospGlutViewer and lib/libospray_commandline.so are for tutorial purposes, you should add the option BUILD_COMMAND_LINE_APPS, and make ImageMagic required only in this case. Otherwise you build a broken ospGlutViewer.

**Comment by carsonbrownlee** [comment]
All the "apps" including ospGlutViewer are purely for tutorial/demo purposes, and are not particularly robust.  There are already cmake flags to control building them, which we could turn off by default.  That said, you are of course correct that they should work with the demo gallery examples out of the box, the imagemagick dependency was an omission on my part.

**Comment by yurivict** [comment]
Just sync ```USE_IMAGE_MAGICK``` and ```OSPRAY_USE_IMAGE_MAGICK``` with ```OSPRAY_ENABLE_APPS``` then.

**Comment by carsonbrownlee** [comment]
I have added a header only image library that will be built with the apps by default.  This should get the demos running with the binary releases by default.  Currently in devel and should be in next release.
