### ISSUE TITLE
build issue with stale libembree.so

### ISSUE THREAD

**Issue by ingowald** [ospray/ospray#108]
Just ran into a weird build/run issue that took me a while to track down: _if_ one ever builds ospray in non-external-embree mode one actually gets a libembree.so in the current build directory; and even if one eventually switches over to building from external embree that library is still there, and will actually get loaded during runtime (assuming that '.' is in the ld_library_path). That of course is wrong as the build actually used the _other_ libembree (from /usr/local) during linking - which in my case led to it linking fine when building, but not being able to run because the local libembree.so had some different symbols in it.
in the past that was avoided by the internal build having a different name for libembree (it was libemrbee_ospray), but in the current build that is no longer the case, producing the problem just described....

**Comment by jeffamstutz** [comment]
Closing this issue as our upcoming (and future) releases will no longer have the internal Embree option.
