### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by timbiedert** [ospray/OSPRay#109]
General question:    Is it safe to generate multiple OSPRay objects in parallel?

In my project I'm creating several `new ospray::cpp::Volume("block_bricked_volume");` in different threads and there seems to be a race condition: Sometimes there is an " Failed to create OSPVolume!" exception.
With a critical section around `new` the exception has vanished (so far)..

**Comment by jeffamstutz** [comment]
Hi, sorry for the delayed response. None of our API calls are *guaranteed* to be thread safe, though there should be plenty of calls that could be called in parallel. There are some things you might be able to do in parallel, like ospSetRegion on non-overlapping regions of a single volume, or doing so on different volumes. Regardless, this may be a reasonable thing to guarentee in the future, but we haven't written the code with that in mind.

With a quick look at the code, it looks like the way we look up the factory function to create volumes (and any other object types, for that matter) is definitely not thread safe as we use a lazily-updated factory function cache used to find the function to actually create the requested object. This means that one thread which is updating the cache makes the cache viewed by other threads as "finished/updated" before it is, indeed, updated.

For now, one thing you could do is create all your OSPRay objects up front before doing any operations on them, or protect their creation with a critical section as you discovered.

We will have some internal discussions about what we can do, and perhaps what steps we can take to make the API thread-safe. Unfortunately, it's not trivial to make the API entirely thread-safe: an easy example with calling ospRenderFrame() while simultaneously calling commit() on objects in the midst of being rendered. I personally think it's solvable, but I can't guarantee we will actually do so and any timeline (yet) if we do.

I hope that helps!

Jeff

**Comment by timbiedert** [comment]
Thank you very much for your feedback!
Yes, I also noticed the issue when creating other object types.   I just put critical sections around each new.

Personally, I don't need and also wouldn't expect the full API to be completely threadsafe (i.e. don't commit while rendering).
