### ISSUE TITLE
Signed short volumes

### ISSUE THREAD

**Issue by jeffamstutz** [ospray/OSPRay#111]
It has been requested that ```short``` (signed) is supported for structured volumes. This should be somewhat straightforward to implement for both block_bricked volumes and shared volumes.

**Comment by johguenther** [comment]
ae50d92c added support for (unsigned) `ushort` as well as templates for accessing voxel data, so it should indeed be easy enough.

**Comment by johguenther** [comment]
Added with ea02117a.
