### ISSUE TITLE
OSPRay causes abort/exit on CPUs with SSE < 4.1, but this isn't well documented...

### ISSUE THREAD

**Issue by tachyon-john** [ospray/ospray#113]
I've gotten the first report from VMD users running on older machines that VMD is getting terminated by OSPRay during startup when running on older hardware.  It seems to me that this is a pretty important issue to document somewhere.  For that matter, I haven't seen any documentation about what other exceptions OSPRay might throw or what else might result in termination of the entire application.  From my perspective, it would be best for an application to either catch any exceptions that OSPRay might throw, or catch an error code during initialization so that OSPRay can be left disabled rather than killing the entire app as it does now, but this is only feasible if there's some documentation on what exceptions it's going to throw, etc.  Here's a crash as reported by a VMD user.  This user also has issues with an ancient GPU w/ CUDA, but in that case VMD catches the errors, reports them, and leaves CUDA disabled for the rest of the session which is what I'd rather do in the case of OSPRay also:

Info) VMD for LINUXAMD64, version 1.9.3 (November 30, 2016)                     
Info) http://www.ks.uiuc.edu/Research/vmd/                                      
Info) Email questions and bug reports to vmd@ks.uiuc.edu                        
Info) Please include this reference in published work using VMD:                
Info)    Humphrey, W., Dalke, A. and Schulten, K., `VMD - Visual                
Info)    Molecular Dynamics', J. Molec. Graphics 1996, 14.1, 33-38.             
Info) -------------------------------------------------------------             
Info) Multithreading available, 2 CPUs detected.                                
Info)   CPU features: SSE2                                                      
Info) Free system memory: 1732MB (45%)                                          
Info) Creating CUDA device pool and initializing hardware...                    
CUDA error: invalid device symbol, CUDAClearDevice.cu line 56                   
Info) Detected 1 available CUDA accelerator:                                    
Info) [0] GeForce GT 440      2 SM_2.1 @ 1.62 GHz,  963MB RAM, KTO, ZCP         
Warning) Detected X11 'Composite' extension: if incorrect display occurs        
Warning) try disabling this X server option.  Most OpenGL drivers               
Warning) disable stereoscopic display when 'Composite' is enabled.              
Info) OpenGL renderer: GeForce GT 440/PCIe/SSE2                                 
Info)   Features: STENCIL MSAA(4) MDE CVA MTX NPOT PP PS GLSL(OVFGS)            
Info)   Full GLSL rendering mode is available.                                  
Info)   Textures: 2-D (16384x16384), 3-D (2048x2048x2048), Multitexture (4)     
terminate called after throwing an instance of 'std::runtime_error'             
  what():  Error. OSPRay only runs on CPUs that support at least SSE4.1.        
Abort (core dumped)

**Comment by johguenther** [comment]
I added the minimum requirement of SSE4.1 to the documentation. Additionally, we plan for release 1.2 to clean-up the error handling and reporting, such that terminating the application should not happen anymore.

**Comment by tachyon-john** [comment]
Johannes, that sounds very good.  As long as there's a way for an application to catch any thrown exceptions or error return codes, and the list of such scenarios is in the docs, I can adjust the calling code in VMD so that it handles unsupported hardware or other issues gracefully, and the user will be warned, but the application can continue on, albeit with features disabled as necessary.

**Comment by ingowald** [comment]
Hm.

Johannes has _documented_ it, but as yet there's no good way to catch 
errors.

The obvious solution would be to to have rtInit() return error codes, 
but that's an API breaking change. The alternative is to have dedicated 
query mechanisms that query whether / in which modes ospray would in 
principle be able to run (with this we could also, for exapmle, return 
whether MPI mode is compiled in).

Anyway; though the latter option is more flexible I'd be in favor of the 
former - rtInit _should_ tell the user whether it worked or not. Also, 
though "in theory" it's API breaking in practice it might not be: with C 
linkage the symbol wouldn't change if we change the return value to int; 
nor would the parameter list, so an app that was compiled against a void 
rtInit would simply ignore the return value but _should_ still run. As 
such, I'd argue this API "break" would be OK even in the middle of a 
release cycle.

Cheers,

Ingo

**Comment by johguenther** [comment]
OSPRay v1.2.0 won't be binary compatible to v1.1.2 anyway (changed enum `OSPDataType`). Additionally, we probably want to introduce a `getError` function and the possibility to set an error callback function.

**Comment by tachyon-john** [comment]
Hi, any news on this particular issue, I continue to get emails about this from VMD users...
Cheers,
  John Stone

**Comment by johguenther** [comment]
The `getError` function didn't make it completely into v1.2 and is pushed to the next release.

**Comment by tachyon-john** [comment]
Thanks for the note.  Is there a time frame for the next release?  In the mean time it seems I'm going to have to add in my own CPU capability checks to prevent VMD from instantiating OSPRay as this appears to affect many more users than I would have guessed.

**Comment by jeffamstutz** [comment]
Hi John,

We definitely have the transformation of thrown exceptions into error codes on our TODO list for v1.3.0. We think we will release v1.3.0 sometime before ISC (with a v1.2.1 release before that).

However in the meantime, have you considered wrapping ospInit() in a try-catch block to catch the exception in VMD? If any exception is thrown there, even if it's not the ISA compatibility one, OSPRay won't work, where VMD then handles and responds to that appropriately. This would let you handle those cases without blowing up VMD while we work out error handling on our end, similar to how you mentioned handling CUDA version problems.

Cheers,
Jeff

**Comment by tachyon-john** [comment]
As it turns out, the SSE 4.1 requirement also creates problems when running tools like valgrind, which caught me off guard.  Any tips to get around that problem?  I had thought valgrind already supported SSE 4.x, but perhaps not in a sufficiently complete way for OSPRay?
[...]
--36507-- _ZdlPv(0x6868590)
--36507-- _Znwm(160) = 0x6868600
--36507-- _Znwm(1) = 0x68686E0
--36507-- malloc(144) = 0x6868730
--36507-- _Znwm(86) = 0x6868800
--36507-- realloc(0x0,32)malloc(32) = 0x68688A0
terminate called after throwing an instance of 'std::runtime_error'
--36507-- free(0x68688A0)
  what():  Error. OSPRay only runs on CPUs that support at least SSE4.1.
==36507== 

The try/catch block didn't work well when I tried it at some point in the distant past, but I will revisit this going forward since other failures could conceivably occur as well.

**Comment by tachyon-john** [comment]
Okay, if I compile the latest valgrind revs from source, I am able to get OSPRay and the calling code to play nice.  I guess the valgrind revs in most distros are a bit carbon-dated...  Cheers, John

**Comment by tachyon-john** [comment]
I guess I spoke too soon.  valgrind still craters in some cases due to unrecognized CPU instructions that it can't emulate.  How do you guys do your leak checking?

**Comment by svenwoop** [comment]
Which valgrind version are you using? I just tried to run Embree compiled for SSE4.2 and this works fine using valgrind 3.10.

**Comment by svenwoop** [comment]
And please report the error valgrind outputs.

**Comment by tachyon-john** [comment]
Hi Sven.  The valgrind I had been using is 3.9.0, because I'm running tests that use very large amounts of physical memory that go beyond the standard capabilities of the stock valgrind (512GB and larger), as described here:  http://joelinoff.com/blog/?p=1549 

I'll capture the unrecognized machine instruction output and paste it for you here.  I'm also going to do a stock valgrind 3.12 build and see if it is able to run OSPRay without problems for a small test case at least.  If 3.12 works, then I would need to be able to apply patches to 3.12 to make it capable of running 512GB cases like I've been doing in 3.9.0...

**Comment by jeffamstutz** [comment]
Error reporting (and not aborting) was added to the new v1.3.0 release. Please re-open the issue if any additional problems related to the original issue occur.
