### ISSUE TITLE
Rendering on Knights Landing appears to use only a single core

### ISSUE THREAD

**Issue by jlefley** [ospray/ospray#114]
I recently gained access to a KNL system and ran into a strange issue when I tried volume rendering with OSPRay on the KNL. I built OSPRay v1.1.2 with TBB, ISPC v1.9.1, and ICC 17.1 on CentOS 7. When I attempt to use the ray cast volume renderer, through ospBenchmark, I observe only a single core in use (according to htop) for the majority of the execution time when running on the KNL. I reproduced the build on a Haswell Xeon system and htop shows all cores in use when I render and the execution completes in much less time then on the KNL system.

output from Haswell run:
```
$ time ./ospBenchmark ~/csafe-heptane-302-volume/csafe-heptane-302-volume.osp -r raycast_volume_renderer --warmup 0 --bench 1 --image ~/out --width 4096 --height 2160 --eye 151 151 -200 --gaze 151 151 0 --up 0 1 0
Frame Time Statistics:
	max: 75.5423 ms
	min: 75.5423 ms
	median: 75.5423 ms
	median abs dev: 0 ms
	mean: 75.5423 ms
	std dev: 0 ms
	# of samples: 1
FPS Statistics:
	max: 13.2376 fps
	min: 13.2376 fps
	median: 13.2376 fps
	mean: 13.2376 fps

real	0m1.333s
user	1m14.918s
sys	0m0.702s
```

output from KNL run:
```
$ time ./ospBenchmark ~/csafe-heptane-302-volume/csafe-heptane-302-volume.osp -r raycast_volume_renderer --warmup 0 --bench 1 --image ~/out --width 4096 --height 2160 --eye 151 151 -200 --gaze 151 151 0 --up 0 1 0
Frame Time Statistics:
	max: 8836.13 ms
	min: 8836.13 ms
	median: 8836.13 ms
	median abs dev: 0 ms
	mean: 8836.13 ms
	std dev: 0 ms
	# of samples: 1
FPS Statistics:
	max: 0.113172 fps
	min: 0.113172 fps
	median: 0.113172 fps
	mean: 0.113172 fps

real	1m52.508s
user	4m16.404s
sys	2m57.652s
```

We also have our own volume renderer implemented as a module and I observe the same behavior; when running on the Haswell system all cores are in use and on the KNL system only a singe core is in use for the majority of the rendering process.

Any ideas regarding what might be going on? Thanks

**Comment by Twinklebear** [comment]
I've run into this as well when using the Stampede KNL partition. It seems like some of the environment TBB uses to determine the available cores aren't set properly, your volume renderer may see this issue as well if it uses TBB or OpenMP. What worked for me on Stampede was setting `I_MPI_PIN_DOMAIN=node` you could also try setting `I_MPI_PIN_DOMAIN=omp` and ```OMP_NUM_THREADS=`nproc` ```. Although it's an Intel MPI environment variable I think it did also work for the single node non-mpi case, if not maybe try setting the OpenMP num threads?

**Comment by jeffamstutz** [comment]
Another idea to try is see if explicitly setting the number of threads by either setting the environment variable ```OSPRAY_THREADS=262``` (or whatever number of hw threads nproc reports), or by passing ```--osp:numthreads 262```. It's more likely to be an environment problem affecting thread affinity (above response), or perhaps you've found a bug in TBB: we default to passing -1 to TBB to indicate it should choose how many threads to spawn, which it may get confused with. Regardless, I haven't personally run into this problem, so please share what you discover should a solution be found.

Cheers,
Jeff

**Comment by ingowald** [comment]
BTW: Since we now had several people running into this: could we make 
sure that there's a few meaningful debug outputs (ie, num cores reported 
by OS, num threads we choose to initialize tbb with (after env vars 
taken into effect), etcpp) when --osp:verbose (or a similar env var) is 
specified?

Cheers,

Ingo

**Comment by jlefley** [comment]
I originally built OSPRay against an external Embree installation (v2.13.0, installed with rpms from Embree website). I built OSPRay again after uninstalling Embree from the system so OSPRay would use its in-source copy. After making this change, it looks like all cores get used as expected.

I tried passing in the number of threads with ```--osp:numthreads``` and tried some of the environment changes suggested without any effect.

**Comment by jlefley** [comment]
I think this may be related to the thread affinity introduced in v2.11.0 of Embree (https://github.com/embree/embree/releases/tag/v2.11.0). I did a little more investigation: building OSPRay against an external installation of Embree v2.10.0 results in the renderer using all cores while OSPRay built against an external installation of Embree v2.11.0 results in the renderer using only a single core.

**Comment by carsonbrownlee** [comment]
Thanks for the detailed report!  We'll take a look at what changed.  @jeffamstutz is probably the best one to look into this, but I can look through it and add a check in OSPRay as needed.

**Comment by jeffamstutz** [comment]
Is this issues reproducible with our current ```release-1.2.x``` branch w/ Embree v2.13.0?
