### ISSUE TITLE
Atmospheric effects and scattering?

### ISSUE THREAD

**Issue by davidgiven** [ospray/OSPRay#116]
(Is this the right forum? I couldn't find any other contact information.)

I'm looking for a C++ raytracing library for an art project. One of the things I need is the ability to render atmospheric Rayleigh scattering in heterogeneous volumes. API-wise, OSPRay looks ideal for my purposes, but I don't see any mention of atmospheric effects at all.

Are they supported? If not, can they be trivially added via the SDK?

**Comment by carsonbrownlee** [comment]
hello, 
we do have an email address for questions, but a feature request on the issue list seems valid to me.  OSPRay does not compute atmospheric scattering, nor single or multi-scattering volumetric effects and it's unlikely this will be on our todo list anytime soon; however, OSPRay was designed as an open source project to be easily modified.  We have several users that have done such modifications.  How difficult this may be will depend on exactly how you want to implement it- as simply a coefficient applied as a function of ray depth, camera, and sun angle it should be trivial; simulating single ray scattering in the volume renderer would be more difficult, but likely easier to add then writing something from scratch.

**Comment by jeffamstutz** [comment]
FYI: the email address Carson mentioned is ospray@googlegroups.com, but this is an OK place to ask questions as well. :)

As Carson mentioned, we don't have any atmospheric scattering code in OSPRay as our focus is on scientific visualization and not photo realistic rendering. That said, we DO have a path tracing renderer for more photo realistic rendering, but it doesn't have any volume rendering support in it (yet).

Even though our existing renderers don't implement what you're looking for "out of the box", OSPRay still has a nice collection of building blocks to work with: cameras, frame buffers, volume sampling, transfer functions, multi-threaded rendering, progressive refinement primitives, etc. What I would recommend is that you implement your own renderer, and reuse everything else in OSPRay.

There are two options for extending OSPRay, writing a "module" or using the "SDK". A module is just a subdirectory in the "modules" directory in the OSPRay source tree that lets you quickly develop little test apps through being built as a part of the OSPRay CMake build system setup. The "SDK" refers to the internal object headers we install in our binary releases to allow for production apps to extend OSPRay inside of their project's source.

To me, modules are easier to get working as there's a ton of "boiler plate" stuff we've already written for you (CMake system, data loaders, viewer app infrastructure). A simple example can be found here: https://github.com/jeffamstutz/module_multihit. By cloning that project into OSPRay's "modules" dir, that module implements a custom trianglemesh, renderer, and demo app (which simply loads the module objects for you by default) to showcase how to do multi-hit ray tracing using OSPRay. While the objects it defines won't be useful to you, it is a nice simple example of how you might structure a module.

Cheers,
Jeff

**Comment by davidgiven** [comment]
That's a shame --- unfortunately, it's the volumetric rendering that I find the hard bit; I've already tried playing with my own ray tracer, and that was where I got bogged down.

What I'm doing is rendering 3D images of planetary surfaces, complete with atmosphere and ocean (and, I hope, clouds eventually). I have code which will generate a procedurally deformed terrain mesh from a PDS dataset, but the cost of writing the huge mesh out to disk from one tool and immediately reading it back in again into another is crippling; right now I'm using the venerable Povray, which isn't the fastest. I'd like something which can be tightly coupled to my scene generator.

I'll bear OSPRay in mind (I actually think I can get away with homogeneous volumes, by stacking many layers of different densities) for for now I'll keep looking. Shame --- renderers with decent APIs are few and far between, and OSPRay has one of the cleanest I've seen...

**Comment by carsonbrownlee** [comment]
I will add that in case Jeff's comment about a new "renderer" threw you off, that depending on exactly what you are implementing this could be a minor alteration to our existing volume renderer.  However, we cannot do that for you unless it applies to our current Scientific Visualization focus or a major client application I'm afraid.
