### ISSUE TITLE
TriangleMesh should accept vertex.color data type OSP_FLOAT3FA

### ISSUE THREAD

**Issue by ingowald** [ospray/OSPRay#119]
(Brayns uses it this way, and that makes sense)

**Comment by johguenther** [comment]
This would require a dynamic check in `postIntersect` whether `vertex.color` was `OSP_FLOAT3FA` and set `dg.color.w = 1.f` in that case.

**Comment by ingowald** [comment]
Well, a conditional move for one component, based in a single precomputed variable. That should be affordable.... :-)

Float3 would be more tricky because this'd require different addressing, but nix'ing a single float to 1 should be ok.
