### ISSUE TITLE
broken code in exp_mpi mode

### ISSUE THREAD

**Issue by ingowald** [ospray/ospray#122]
just so we don't forget about this: this looks fishy, but can't curently look at it!

/home/wald/Projects/ospray/modules/DPRT/DPRT.cpp(82): warning #1011: missing return statement at end of non-void function "ospray::dprt::DPRTRenderer::beginFrame"
        virtual void *beginFrame(FrameBuffer *fb) {};
                                                   ^

/home/wald/Projects/ospray/modules/DPRT/DPRT.cpp(142): warning #1011: missing return statement at end of non-void function "ospray::dprt::DPRTRenderer::renderFrame"
      }
      ^

**Comment by jeffamstutz** [comment]
This looks like code you have in a module. Please re-open and update if you find in OSPRay itself.
