### ISSUE TITLE
Windows Build:  The ospray::TileError class is not exported.

### ISSUE THREAD

**Issue by lbarbieri** [ospray/ospray#125]
Hello,

I've considered the following bug when attempting to build the pathtracer module on Windows:

**Description**
In "ospray/fb/FrameBuffer.h", the ospray::TileError class declaration is missing the OSPRAY_SDK_INTERFACE linkage macro.  This causes problems when building & linking the ospray/render/pathtracer module against the installed software on Windows.

**Expected behavior**
The ospray::TileError class would be exported on Windows.

**Observed behavior**
The ospray::TileError class is not exported on Windows.

**Applies to**
v1.1.2 (revision 95ccc33)

Thanks
Lou

**Comment by johguenther** [comment]
Hi Lou,
thank you for sharing this. Please use the recently [released version 1.2.0](https://github.com/ospray/ospray/releases/tag/v1.2.0) of OSPRay, the linker error is already fixed there (commit 35e63476e0).

Best regards,
  Johannes

**Comment by lbarbieri** [comment]
Hello Johannes,

Whoops - I should have checked the latest version :)

Thank you for your time,
Lou
