### ISSUE TITLE
Streamlines: Per-vertex radius

### ISSUE THREAD

**Issue by tbiedert** [ospray/ospray#126]
Do you have any plans for per-vertex radii in the streamlines geometry?

Thanks,
Tim

**Comment by johguenther** [comment]
There were some ideas but nothing concrete...
But now, since you specifically ask for this feature, the plan is to have it in the next release (v1.3 :-).

**Comment by johguenther** [comment]
Well, it did not make it into v1.3, but it is not forgotten.

**Comment by tbiedert** [comment]
Ping! Any updates on this? :-)  Do you plan to create smooth transitions/curvatures between segments of potentially different radius?

**Comment by johguenther** [comment]
Well, the plan is to have it in the next release (v1.4), alas it is already clear that this will be tough... Cross your fingers.

**Comment by johguenther** [comment]
Streamlines with per-vertex radius are now supported in `devel` branch, with smooth transitions using Embree's Bézier curves. Feedback welcome :-)

**Comment by tbiedert** [comment]
Works great! Thanks! :-)
