### ISSUE TITLE
Multitexturing

### ISSUE THREAD

**Issue by timbiedert** [ospray/ospray#128]
Is multiple textures per triangle mesh support planned for the SciVis renderer?  i.e. a list of textures per material, and a corresponding list of UV coordinates per vertex.

In our application we use blend over in the given texture order.

Thanks!

**Comment by johguenther** [comment]
Well, the short answer is "no" (there are currently no plans).
Just to clarify: you really need multiple sets of texture coordinates (i.e. for the triangle mesh not only the vec2f array `vertex.texcoord`, but e.g. `vertex.texcoord2`, `vertex.texcoord3`, ...)? Is there a maximum number of sets? Do you use your own material to blend the textures?

**Comment by timbiedert** [comment]
Hi, thanks for the feedback.  Theoretically, the vec2f array `vertex.texcoord` would suffice, because we only need 2D textures. 
Now I need clarification:  It's currently not possible to use multiple materials for texture blending (on the same vertex/primitive), is it?

**Comment by johguenther** [comment]
If one set of texture coordinates is sufficient then everything is much easier. You can already use multiple textures, e.g. with the OBJ material. But I guess you want to combine multiple textures to modify a single material property (e.g. diffuse color). This can easily be implemented in a (probably custom) material (I just see that this requires a small change to the SciVis renderer).

**Comment by timbiedert** [comment]
Alright, thanks! We will investigate the custom material vs. maybe prebaking a single (mega) texture.

**Comment by johguenther** [comment]
OK. One more note: sometimes it is possible to have different UV coordinates for texture fetches, all still based on the same texture coordinates per vertex, but using different texture coordinates transformations (which again can happen in the material). Transformations such as scale, shift, or rotation; and [code for this is already in OSPRay](http://www.ospray.org/documentation.html#texture-transformations).

**Comment by timbiedert** [comment]
Thanks, but this is only implemented in the Pathtracer, right?

**Comment by johguenther** [comment]
Currently, yes. But if this would be a solution for you we would change the SciVis renderer to support texture transformations as well. This is again much easier than supporting multiple UV sets (what we will still discuss internally).
