### ISSUE TITLE
feature request : texture coordinates for sphere and cylinder primitives

### ISSUE THREAD

**Issue by demarle** [ospray/ospray#130]
I'd like the ability to specify texture colors maps and texture coordinates for sphere and cylinder primitives as can already be done for trianglemeshes.

For ospNewGeometry("trianglemesh") just supply a vertex.textcoord and a material with an osp:Texture2d to get a color for each pixel come from a lookup into the texture.

See: https://gitlab.kitware.com/vtk/vtk/blob/master/Rendering/OSPRay/vtkOSPRayPolyDataMapperNode.cxx#L420 for example.

With ospNewGeometry("sphere"|"cylinders") there could be something like an "offset_textcoord" to define the same.

For spheres each sphere should be entirely the same color determined by its single u/v lookup result. For cylinders the u/v should interpolate from one end to the other and then the texture lookup for each fragment will be different down the cylinder.

This will resolve longstanding VTK/PV issues where ospray results look notably different for point clouds, stream lines and wireframe representations.

**Comment by johguenther** [comment]
Re spheres: if each sphere still has a constant color, then how about adding a color parameter instead? Rendering would be much faster (texture fetches are expensive). The downside is probably more work in the ParaView->OSPRay adapter, and more memory consumption (when using `vec3f` colors).

Re cylinders: so you have a u/v pair for both vertices (`v0` and `v1`), which are linearly interpolated before fetching the texel (as opposed to interpolating the fetched colors)? The texcoords are 2D, not just `u` (they are used like for a 1D line segment)?

**Comment by demarle** [comment]
For points I could use direct colors as you suggest and it would be optimal. For other rendering modes I already use "color"+ "offset_colorID" and "materialList"+"offset_materialID" to do something similar so it isn't that much work on my end. I still recommend that OSPRay support texture lookup for spheres though. It will let you support real texture maps, more advanced materials, and just for the aesthetic of symmetry with triangle mesh's capability.

For cylinders yes, we pass in both u and v, but v is 1 wide, constant and effectively a don't care. Interpolating R,G,B along the line gives the wrong results. Consider a color map that says 0.0=255,0,0; 0.5=0,255,0; 1.0=0,0,255. The midpoint of a line with 0.0 and 1.0 at the ends should be 0.5=0,255,0 (green) and is if you interpolate first and color after. Interpolating RGB directly will give 128,0,128 (purple) which is wrong. This one is a high priority for me.

**Comment by johguenther** [comment]
Should work now, please give it a try.

**Comment by demarle** [comment]
Looking good so far. Will take me a day or five to get the rest of the modes checked out but this is a big improvement. From vtk's TestOSPRayRenderMesh, the point cloud with texture map in GL (squares) and OSP (spheres). Before OSP side had always just been white.

![glsmall](https://cloud.githubusercontent.com/assets/445592/25755993/198a9abe-3193-11e7-871d-a373f4798eec.png)

![ospsmall](https://cloud.githubusercontent.com/assets/445592/25756002/1e347986-3193-11e7-896d-b6f0a1e5baed.png)

**Comment by demarle** [comment]
"Will take me a day or five..." or less. ;) 
https://gitlab.kitware.com/vtk/vtk/merge_requests/2789

**Comment by johguenther** [comment]
Wonderful :-)
