### ISSUE TITLE
feature request :  clear background alpha to known start value

### ISSUE THREAD

**Issue by demarle** [ospray/ospray#131]
I'd like the ability to clear the alpha channel to a known value at the start of a render. Perhaps a bgAlpha (1f) parameter to go along with the existing bgColor (3f) parameter or a new bgColor (4f) parameter.

This will resolve a very recent issue (just this current ParaView release cycle) that cropped up when we bumped to Qt5 and gained good support for transparent backgrounds.

**Comment by ingowald** [comment]
I'd suggest the "vec4f" variant - better than adding yet another parameter.

**Comment by johguenther** [comment]
Currently `alpha` cannot be set because it is computed by OSPRay according to the definition:
- 0 if nothing is hit / background
- 1 if something opaque is visible in the pixel
- between 0 and 1 for semi-transparent objects or at anti-aliased edges.

This way the rendered image can easily be blended / composed with whatever background (potentially rendered by other renderers) the application wants. So, in a way `bgColor` is redundant and actually a shortcut to already blending with a constant background.

**Comment by ingowald** [comment]
But isn't that the same as saying bgColor becomes vec4f with a default
bgColor.a = 'fully transparent' ?


On Mon, Mar 13, 2017 at 10:26 AM, Johannes Günther <notifications@github.com

**Comment by johguenther** [comment]
Yes.
I could not find what the purpose of `GetBackgroundAlpha` in VTK is; why does QT5 need a special, non-standard alpha? To have a semi-transparent render window?
Anyway, it looks like we can do it with a `vec4f`.

**Comment by demarle** [comment]
We are using it to _prevent_ a semi-transparent window. See https://gitlab.kitware.com/vtk/vtk/merge_requests/2505

One some systems, now that we are 1:by default requesting RGBA contexts and 2: using Qt5 instead of Qt4, we found that Qt respects the alpha and shows the desktop background or garbage under the scene. That is sort of cool and all that but not at all what we want to see. So the recent change sets it to 1 for the Qt window and leave it default 0 elsewhere and then we glClearColor with the choice at the top of every frame. 

Potentially vtk's bgalpha might help with the frequently requested feature of saving out image captures with transparent backgrounds and the somewhat weird concept of a semi-transparent window too I guess.

If the suggestion doesn't make sense for OSPRay go ahead and close this request. I can blend after that fact. I think bgalpha+(1-bgalpha)*osp.a is what I need. It would just be nice if I didn't have to.

**Comment by johguenther** [comment]
It (`bgColor` including alpha as vec4f) is implemented in our internal branch and will be public on GitHub once all CI tests are green.

**Comment by johguenther** [comment]
Patch is available in 6d7a7634b293a69c04bbe79c14e332b4532ec5d9, so you could test it (I accidentally already pushed to GitHub...).

**Comment by demarle** [comment]
I patched onto 1.1.2 and make corresponding changes to VTK and the fix looks to be working in my case. Thanks!
