### ISSUE TITLE
Support for rectilinear volume grids?

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#137]
Is support for volume rendering rectilinear grids planned, i.e. grids with varying spacing? As that would be a great addition. ParaView currently has no support for this (https://gitlab.kitware.com/paraview/paraview/issues/10036).

**Comment by jeffamstutz** [comment]
We don't have immediate plans for implementing rectilinear grids ourselves, though we can use this issue to track any requirements for them in your application(s).

**Comment by ingowald** [comment]
Just in case: would you have to happen any data that you could share with us?
If we were to add this, we'd need something to test with....

**Comment by paulmelis** [comment]
I have received a small (in scientific terms) dataset from one of our users that uses varying spacing in X direction. It's stored in 2 HDF5 files + Xdmf file. One of the HDF5 files is 132MB, I guess I shouldn't attach it to this issue :)

**Comment by paulmelis** [comment]
Just noticed the current support for tetrahedral volumes and upcoming support for hexahedral cells. So rectilinear volume grids can already be rendered, but you just need to set up the cells manually?

**Comment by jeffamstutz** [comment]
Yes, I would think that if the data matches our upcoming ```UnstructuredVolume``` vertex/index/field data arrays then it should render just fine.

Still, there may be reason to implement a rectilinear volume type in the future for performance (i.e. we can make better assumptions about the data coming, thus make better algorithmic choices for prep/sampling/etc).

**Comment by paulmelis** [comment]
Great! Is there a specific order assumed for the vertex indices of tetrahedrons and hexahedrons?

**Comment by timrowley** [comment]
Hexahedron vertex indices are in the VTK_HEXAHEDRON ordering, as shown on the diagram here: [https://www.vtk.org/data-model/](url)

**Comment by jeffamstutz** [comment]
Closing this here for OSPRay, as now all volume sampling support comes from [Open VKL](https://github.com/openvkl/openvkl), where this request should be targeted.
