### ISSUE TITLE
Transparency for "Isosurfaces"

### ISSUE THREAD

**Issue by JimCR-Lin** [ospray/ospray#138]
I want to set transparency for "Isosurfaces".   Color can be changed by “transfer function” but not transparency.

**Comment by carsonbrownlee** [comment]
looking into it

**Comment by johguenther** [comment]
FYI, transparency for Isosurfaces is now working in `devel` branch. Transparency is controlled via the material that is assigned to the geometry, see for example the StructuredVolume tutorial.

**Comment by jeffamstutz** [comment]
Generic material support for all geometry types (including `isosurface`) is in `v2.0`, which enables transparency.
