### ISSUE TITLE
undefined reference in libospray building any of the applications. 

### ISSUE THREAD

**Issue by semeraro** [ospray/ospray#139]
Hi, 
I get the following error when building any of the example ospray applications:
../libospray.so.1.3.0: undefined reference to `ospray::PixelOp::Instance::~Instance()'

I am building version 1.2.1 from the source tarball ( git devel and master branch have same error). I am using ispc 1.9.1, embree 2.15, and tbb from tbb2017_20170226oss (the latest version from the website). I am using the intel15 compiler on a centos6 system. I have gcc/4.9.1 in my library path. 

I hate to bug you guys but any idea where this error is coming from? I cant seem to find the missing bit in my configuration. 

Thanks, 
Dave Semeraro

**Comment by semeraro** [comment]
I made the following change to PixelOp.h 
//virtual ~Instance() = default;
      virtual ~Instance(){};

This allowed the applications to compile. I have not had a chance to see if any of them run. It seems the default virtual destructor was the problem. I still think I have a configuration problem. The default destructor compiled but left the undefined reference. Perhaps order of linking? I dont know. ..

**Comment by johguenther** [comment]
Hi Dave,
I can reproduce the problem: it is the old version 2015 of icc, version 2016 works. However, your workaround should do the trick as well (it works for me also with icc15).

Best regards,
  Johannes

**Comment by semeraro** [comment]
Thanks Johannes, compiler bugs are the worst.

Dave Semeraro
Visualization Group
Texas Advanced Computing Center
University of Texas Austin

**Comment by jeffamstutz** [comment]
FWIW, we don't get the traditional benefits of icc with OSPRay because most of our performance sensitive code is compiled by ispc. By the time ispc code makes it to the C++ compiler, it cannot be further optimized. Thus if it makes things easier for you, compiling with gcc or clang will essentially give you the same result as using icc.

**Comment by semeraro** [comment]
Thanks Jeff, I usually default to the icc compiler because most of the stuff I deal with does benefit from it. I am too lazy to module swap. Looking forward to experimenting with the latest OSPRay.
