### ISSUE TITLE
Compiling error in ospExampleViewer.cpp

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#144]
ospcommon::vec3f translate is showing error saying that ospcommon doesnt have vec3f member.
I am not able to find a suitable header which has class ospcommon having member vec3f.
Basically the file included here is Utility.h. But the class ospcommon in Utility.h doesnt have vec3f as member.Please kindly advise

**Comment by johguenther** [comment]
For `translate()`  you need to include `AffineSpace.h` (which in turn includes `components/ospcommon/vec.h` where  `vec3f` is defined).

**Comment by johguenther** [comment]
Hmm, I think you mean the `translate` variable declared in `ospExampleViewer.cpp` line 29. Which branch are you compiling? `devel` and `master` compile well.

**Comment by swatinair123** [comment]
![screenshot](https://user-images.githubusercontent.com/23516228/27478702-653db45c-582e-11e7-9a40-cb9d2921b772.png)

This is the screen shot . I am getting errors where ever i use ospcommon.

**Comment by swatinair123** [comment]
i was able to run osptutorial.cpp. I will try out with the code in the above branches also branches. Thanks a lot

**Comment by johguenther** [comment]
Which platform/OS and compiler do you use?

**Comment by swatinair123** [comment]
My OS is Windows 10 and compiler is Visual studio15 2017 Win 64

**Comment by johguenther** [comment]
Ok, and you did use CMake to generate the VS solution?
Let's try something: could you
- open a MSVC console (`VS2017 x64 Native Tools Command Prompt` under `Visual Studio Tools`)
- go to the OSPRay source directory
- remove / rename the `build` folder (if there is any)
- run `scripts\build_gitlab\win.bat "Visual Studio 15 2017 Win64" "v141"`

If compilation fails, please copy the error message here.

**Comment by johguenther** [comment]
I forgot: this will only work if the dependencies (Embree, TBB, ISPC) can be found by CMake, e.g. if they are in the `PATH`.

**Comment by swatinair123** [comment]
To generate the build for osprey I had given the path for Embree ,ISPC, and
I used OpenMP instead of TBB

**Comment by johguenther** [comment]
Hmm, I still cannot reproduce your problem: current `devel` compiles fine with Visual Studio 15 2017 Win64, with the default CMake config (and also with OpenMP instead of TBB). However, I don't have access to Windows 10 right now, I compiled on Windows 7 and 8.

**Comment by swatinair123** [comment]
Yes the devel builds completely fine with Cmake. But the issue is when i try to compile ospExampleViewer.cpp in a separate project as i need to load ospray for different .obj files.

**Comment by johguenther** [comment]
Do you want to use OSPRay's OBJ importer in your own project? This is not implemented in `ospExampleViewer.cpp` – better use the SceneGraph (look at `apps/common/sg/SceneGraph.h`::[`importOBJ`](https://github.com/ospray/ospray/blob/v1.3.0/apps/common/sg/SceneGraph.h#L84)).

Or do you want to use the (potential modified) example viewer in your own project? Then make sure you catch all needed include files and paths (e.g. in Visual Studio with the OSPRay solution loaded have a look at the Property Page of `ospExampleViewer.cpp` at Additional Include Directories). To use the `ospcommon` namespace include the headers in [`components/ospcommon`](https://github.com/ospray/ospray/tree/v1.3.0/components/ospcommon), e.g. `box.h`.

Also, there is no need to compile the OSPRay libs yourself, you can use the [pre-compiled binaries](https://github.com/ospray/ospray/releases/tag/v1.3.0).

**Comment by swatinair123** [comment]
Ok Thanks a lot.
