### ISSUE TITLE
Build and install for VisIt

### ISSUE THREAD

**Issue by Krishnasamy** [ospray/ospray#145]
Can you please point me or guide me how to build and install the OSPRay in VisIt.

**Comment by wilsonCernWq** [comment]
Hi, I am the developer of VisIt-OSPRay.  So as far as I know, there are two implementation of VisIt-OSPRay. 

One is a VisIt+OSPRay/SWR integration built by Hota, Alok, where OSPRay is implemented as a renderer (which means you can render all the VisIt plots theoretically). You can find his building instruction here:
```
http://curent.utk.edu/people/power-systems-students/alok-hota/
```

Another one is the one I am developing, which implements OSPRay as a volume filter (specialized for distributed volume data and optimized for performance). I haven't finished the building instruction yet. But if you need it, you can contact me or go to
```
https://github.com/wilsonCernWq/VisIt-OSPRay
```
