### ISSUE TITLE
Unable to run the code in demos(Animated woody Object)

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#147]
Hi ,

I am trying to run the below code through command prompt but I am getting the below errors. Can you please help me resolve it.
![image](https://user-images.githubusercontent.com/23516228/27855935-f149dad4-6189-11e7-9a36-da180da22304.png)

I am trying to run this code
./ospExampleViewer crytek-sponza/sponza.obj --sun-dir -.3 -1 -.04 --renderer scivis --sun-int 3 -vp 667.492554 186.974228 76.008301 -vu 0.000000 1.000000 0.000000 -vi 84.557503 188.199417 -38.148270 --translate 250 -11 0 --scale 300 300 300 --lockFirstFrame wooddoll/wooddoll*.obj -ao 0 --ambient .85 .9 1 .3

**Comment by jeffamstutz** [comment]
Hi,

That demo was accidentally broken in favor of creating another customer demo. The viewers are currently being completely redone, where we will fix that demo in the next upcoming release (v1.4.0). We are currently targeting a release before SIGGRAPH in early August.

I'll leave this issue open until I have it working again in our upstream ```devel``` branch. Sorry for the inconvenience. 

Cheers,
Jeff

**Comment by swatinair123** [comment]
Hi,Thanks a lot for the reply.
