### ISSUE TITLE
Memory issues while running ospExampleViewerSg.exe

### ISSUE THREAD

**Issue by pratikshaandhare** [ospray/ospray#148]
Hello,

I had compile Devel branch of ospray and build the solution using Cmake. When I run the ospExampleVieweSg.exe, it shows the memory issue. Currently stack reserve size is 8388608. I increased it to 1073741824. But facing same problem.

Kindly advice.

**Comment by johguenther** [comment]
Which memory issue? The already increased stack size of 8388608 should be sufficient (running fine here). Are you using the unmodified `ospExampleViewerSg`? Can you start the application without any arguments (without loading a scene)?

**Comment by pratikshaandhare** [comment]
Yes. We are using unmodified ospExampleViewerSg. The memory issue which we are facing is attached here.
![error](https://user-images.githubusercontent.com/20615346/27858445-e19d9ad6-6192-11e7-98d5-6e25861d1b07.png)

**Comment by johguenther** [comment]
I can reproduce the problem with `Debug` config. In the meantime please try `Release` or `RelWithDebInfo`.

**Comment by pratikshaandhare** [comment]
Okay. Thanks a lot.
