### ISSUE TITLE
Starting tutorial in OSPRay exits 0 

### ISSUE THREAD

**Issue by dennis19** [ospray/ospray#149]
Hello,

right now im trying to start the ospTutorial in VS2015. 

I generated the Solution with cmake and added the paths for Tbb and embree.
After i start the project in debugmode it justs exits with some comments in the outputline.
The output tells me for the "tbb_debug.dll": PBD-file could not be found or not be opened.
Also it says ospTutorial exited with code 0.

I'm completely  new to OSPRay, so just tell me if yout need further information.

Thank you

**Comment by johguenther** [comment]
There seems to be problems with the `Debug` config. Until those are solved, please try `Release` or `RelWithDebInfo`.

**Comment by johguenther** [comment]
Related to #148.

**Comment by dennis19** [comment]
Ok, now i get the error that the embree.dll and the tbb.dll are missing.
Do i have to put them somewhere special?

**Comment by johguenther** [comment]
Either have the dlls accessable via the `PATH` environment variable, or simply copy them into the `build/$config` folder (where the `ospTutorial.exe` is as well).

**Comment by johguenther** [comment]
Sorry, misunderstanding on my side. There is no relation to #148. The message "exited with code 0" is actually fine, indicating everything went well. The tutorials do not open any window, but instead create two `ppm` images, as also [described in the documentation](http://www.ospray.org/documentation.html#tutorial). Try `ospExampleViewerSg` for an interactive application.
