### ISSUE TITLE
Build errors when building ospExampleViewer.cpp

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#150]
Hello ,

I am trying to build a new Project with the cpp  source code as ospExampleViewer.cpp. I have included all the header files and there are no compiler or linker errors . But I am having build errors more than 100 in my code. Attached is the error log.Please kindly advise .

Thanks and Regards,
Swati
[errorList.txt](https://github.com/ospray/ospray/files/1126757/errorList.txt)

**Comment by johguenther** [comment]
Hi Swati,
sorry, these errors are not related to OSPRay. Maybe some mistakes when setting-up the Visual Studio project?

Best regards,
  Johannes

**Comment by swatinair123** [comment]
Hi Johguenther,

I was able to run the osprayTutorial.cpp succesfully as a separate project. For ospExample Viewer.cpp I have given all the include files used in the Project in the sln got from the OSPray repository still i am getting these errors.

**Comment by wilsonCernWq** [comment]
Only include files is not enough. You probably need to also link libraries from your ospray build/release also, if you haven't done so.
