### ISSUE TITLE
Documentation for the math library

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#151]
Is that possible to have some kinds of documentations for the ospray math library ? It can be still helpful even the library is not very large currently.

**Comment by jeffamstutz** [comment]
We are considering the ```components/``` directory as a standalone library of tools not specific to OSPRay. If/when we decide to publish that as a separate project, documentation would certainly become more important. However, right now the public API is our only priority for documentation.

Use our internal code at your own risk!

**Comment by wilsonCernWq** [comment]
That makes sense, thanks anyways ~!
