### ISSUE TITLE
Co-ordinates of vp, vi, vu

### ISSUE THREAD

**Issue by pratikshaandhare** [ospray/ospray#160]
Hi,
Can anybody give me the ideas about the co-ordinates or limits of vp, vi and vu?

**Comment by johguenther** [comment]
`vp` is the viewing position, the position of the camera. `vi` is the point of interest, the position to look at. `vu` the up-vector. All have unlimited range (vu will be normalized internally).

**Comment by pratikshaandhare** [comment]
Thanks a lot. How to set the camera angle in ospExampleviewer.cpp?

**Comment by johguenther** [comment]
You are on `devel`, right? You can in a general way add and manipulate scene-graph nodes via command line parameters:
```bash
-nodeName:...:nodeName=value,value,value -- changes value
-nodeName:...:nodeName+=name,type        -- adds new child node
```
Thus, to change the angle value of the camera node, try `-camera:fovy=90`.

Hint: to learn about the names of the nodes try the online menu (press `g`), which prints the scene graph nodes.
