### ISSUE TITLE
path tracer metal material, no "color" with default "roughness"

### ISSUE THREAD

**Issue by demarle** [ospray/ospray#161]
Setting "color" on a metal material does nothing unless "roughness" is also set to 0.0.
0.0 forces Metal_getBSDF to choose Conductor instead of the default, MicrofacetConductor. 
This was in devel, a few commits off beyond v1.3.1 at b5ea4973.

**Comment by carsonbrownlee** [comment]
@johguenther ?  It appears that Microfacet does not use reflectance at all.  What is the correct way to specify the reflective color for a microfacet conductor?

**Comment by carsonbrownlee** [comment]
The correct solution appears to set eta and k values based on the wavelength equivalents for rgb and not use the reflectance value.  We should make a base color mapping to eta and k values, however it sounds like this may be put into a separate material such as the uber shader.

**Comment by carsonbrownlee** [comment]
note:  I used this site for grabbing eta and k values:  https://refractiveindex.info/

**Comment by johguenther** [comment]
I'll remove the "reflectance" parameter to avoid confusion.

**Comment by Twinklebear** [comment]
@carsonbrownlee the "site" I was thinking of was actually just the PBRT repo and PBRT v3 scenes distribution which comes with a bunch of SPD files, loading and interpreting them is covered in PBRT it's covered in section 5.2 of PBRT v2 & v3. Though with this approach for metals eta and k become RGB colors, which is more correct, but I'm not sure if that's what our materials currently support.

**Comment by carsonbrownlee** [comment]
thanks @twinklebear.  Reflectance RGB is being taken out, so the only way to specify the resulting color should be in the physically based k and eta variables, which are vec3fs for each color channel if that's what you meant by RGB.  It will likely be far more intuitive to have an automated conversion from RGB to eta and k which most renderers seem to support.  That can likely wait for the uber material Johannes is working on though.

**Comment by Twinklebear** [comment]
Gotcha, cool yea if we're migrating to a correct physically based k & eta for each color channel (yea what I mean by RGB) then those SPD files will get some good results. In the PBRT scenes they have them for many common metals we may want to support, so we could parse and convert them once to RGB using the PBRT code and keep those vec3fs hard-coded in some database somewhere to pick between Copper, Gold, Silver or so on.

**Comment by carsonbrownlee** [comment]
that is exactly what the material example database is for:)  Good idea, but unless they have all the values requested by Kitware for things like tungsten, I say we just pick a reasonable wavelength for RGB and stick to using the same tool from https://refractiveindex.info/ for all of them.

**Comment by johguenther** [comment]
This is harder than I though: on https://refractiveindex.info/ you can choose between several sources, which disagree considerable, which are again different from http://www.luxpop.com/
Then, e.g. using the Tungsten from PBRT gives a dark metal with reddish tint, whereas Tungsten should look grayish bright.

**Comment by carsonbrownlee** [comment]
@johguenther yes, I had the same experience when changing the publication source on refractiveindex.  In general I tried to just stick with the default entry when possible.  Another route we can take:  I downloaded a trial of Maya and Renderman, and I could go through and grab eta values from there as sort of an industry standard.  I'm not sure they would have all the metals on our list however.

**Comment by johguenther** [comment]
I came to the conclusion that the current implementation of Metal is close to useless, providing parameters `eta` and `k` as a `vec3f` "RGB" is rubbish and far from "physically plausible". Basically only silver and gold give OK results. What needs to be done is to compute the conductor Fresnel in the spectral domain and convert to RGB afterwards. First tests suggest that the performance impact is not that high.
