### ISSUE TITLE
path tracer thin glass material "thickness" has no effect?

### ISSUE THREAD

**Issue by demarle** [ospray/ospray#163]
The thickness parameter of the thin glass material doesn't seem to have any effect.

**Comment by johguenther** [comment]
Thickness has only a visible effect when also the attenuation color "transmission" (should be renamed...) is also set.

**Comment by carsonbrownlee** [comment]
marking as resolved, thin glass has no refraction.

**Comment by johguenther** [comment]
There are still a couple of problems with `ThinGlass` that I'm currently working on:
- enable parameter updates (currently can only be set once)
- maybe remove `thickness`
- parameter names
- implementation

**Comment by carsonbrownlee** [comment]
@johguenther I believe I already fixed the first item for thinglass, and most of the other pathtracer materials.

**Comment by johguenther** [comment]
Yes, I noticed after I wrote the comment. Thanks!

**Comment by johguenther** [comment]
OK, some additional improvements are now available (e1c752b8523dbecc6099670b12bf5afd85410298), e.g. support for textured attenuation and consistent parameter names (in particular to Glass).
