### ISSUE TITLE
path tracer metallicpaint material not working?

### ISSUE THREAD

**Issue by demarle** [ospray/ospray#164]
I can't seem to get any effects out of the shadecolor, glittercolor or glitter spread controls. All I seem to get are black objects that are more or less shiny and reflective based on eta. Is this broken?

**Comment by johguenther** [comment]
With 4cfe8916 it's not black anymore. But there are still some more issues (it looks too bright now).

**Comment by johguenther** [comment]
Remaining issues fixed in 6d1cf9c54938fac64ef1909b9025441cf2d6fb45.
