### ISSUE TITLE
How to set the transformation for a model?

### ISSUE THREAD

**Issue by cshan** [ospray/ospray#166]
Hi, 
I am finding how to set the model transformation by a matrix, I can't find a simple API in OSPRay to do this, could you tell me how to do this?

Thanks,
Chengliang

**Comment by wilsonCernWq** [comment]
`osp::affine3f` actually corresponds to a 3x3 rotational matrix plus a `vec3f` translation.
You can set an affine3f transformation by simply doing the following
```
osp::affine3f m;
m.l.vx = <1st column of the rotational matrix>
m.l.vy = <2nd column of the rotational matrix>
m.l.vz = <3rd column of the rotational matrix>
m.p    = <translation>
```  
Then you can use
```
OSPGeometry ospNewInstance(OSPModel modelToInstantiate, const affine3f &transform);
```
To create an instantiated geometry

**Comment by cshan** [comment]
@wilsonCernWq Thanks, works well!
Could I ask another question, which axis is up? Y-axis?

**Comment by wilsonCernWq** [comment]
I think that depends on your camera up vector ?

**Comment by cshan** [comment]
Yes, I think the problem is camera up vector is not correct.
Right now I have a opengl(right-handed) modelview matrix, do you know how to get the pos, dir and up for camera?

**Comment by wilsonCernWq** [comment]
OpenGL uses Y up by default. So I guess you can try use Y axis as the camera up also in ospray (camera pos can be anywhere ok positive Z. Camera direction should be pointing toward negative Z). Then just set an affine transformation the same as your model view matrix. That should give the same result as OpenGL.

**Comment by johguenther** [comment]
FYI, some example code to convert [OpenGL matrices to OSPRay's camera parameters](https://github.com/ospray/ospray/blob/release-1.2.x/apps/volumeViewer/glUtil/util.cpp#L42-L62).
