### ISSUE TITLE
How to rendering Shadow&AO into a transparent plane?

### ISSUE THREAD

**Issue by cshan** [ospray/ospray#167]
Hi,
I want rendering a model with Shadow&AO into a transparent plane, I created a plane but I don't want draw it on framebuffer, only want it receive the shadow and AO, so the vertex.color all is (0, 0, 0,0) the plane and the shadow will disappeared, but when I set the vertex.color to (1, 1, 1, 1) the plane is all white, but the shadow is correct.

Is anyway can rendering a plane just with shadow pixels not all the plane?

Thanks

**Comment by jeffamstutz** [comment]
(If I understand your question correctly) Currently what you are describing is not possible as the alpha channel is respected for all ray query types, at least for our main ```scivis``` and ```pathtracer``` renderers.

The idea is that you want an object to cast a shadow, but not be rendered itself?

**Comment by cshan** [comment]
right, the goal is I need render a model based on a video(AR) as the background.

**Comment by jeffamstutz** [comment]
Sorry for the late reply. This definitely sounds interesting as AR is not a space we have worked in yet, though we would like to discuss it first among the team (several team members are on vacation right now).

**Comment by carsonbrownlee** [comment]
hello, can you elaborate on the scenario you need?  You would like the light from the video frame to influence the scene without actually rendering the light image used is that correct?  This may be already supported in the path tracer, as you can create an image based light but then use a "backplate" for the background color which could be transparent.

**Comment by cshan** [comment]
Thank your all input, I have already find a solution and it is work well, when I review the code I got a property of renderer named "shadowCatcherPlane", but in core code have a lot of TODO, but after I set the currect plane for shadowCatcherPlane, it works well.

**Comment by johguenther** [comment]
Yes, `shadowCatcherPlane` is the (undocumented) feature you are looking for. Please note that this is implemented for the path tracer only (but you can use an `ambient` light to emulate AO, or maybe you even have a light probe (HDRI) recorded together with the video).

**Comment by bharatshiyani** [comment]
@cshan, can you please put some example code to use shadowCatcherPlane , because when I use it it gives black plane .
 renderer->setParam("shadowCatcherPlane", vec4f(0, 0, 1, 1));
 addObjectToCommit(renderer->handle());

**Comment by BruceCherniak** [comment]
The plane is affected by the renderer `backgroundColor` parameter.  There is currently no method to set the `shadowCatcherPlane` plane independent of the background color, because you are effectively just seeing a _shadow_ on the background with the `shadowCatcherPlane`.

**Comment by bharatshiyani** [comment]
I am setting shadowCatcherPlane with below code,
--------
renderer->setParam("backgroundColor", vec3f(1,1,1));
renderer->setParam("shadowCatcherPlane", vec4f(0, 0, 1, 1));
--------
the plane is coming but all black. 
Any idea why it is black instead of completely transparent ?

![image](https://user-images.githubusercontent.com/26597849/186402934-fd61269e-958e-4e36-a18b-c2e1647a5017.png)

**Comment by BruceCherniak** [comment]
From just this image, it is impossible to tell what the image _should_ look like.  Can you post images with and without the `shadowCatcherPlane` for some context?  Is the white I'm seeing the background or something else?

The plane will appear transparent to the background, however, if geometry is on the far side of the plane, it will not be visible - ie it is a _ground_ plane, anything _underground_ is not visible.

Also, please keep in mind that the `backgroundColor` has an alpha component as per https://www.ospray.org/documentation.html#renderers that affects the background of a saved renderbuffer image if png.

float / vec3f / vec4f | backgroundColor | black, transparent | background color and alpha (linear A/RGB/RGBA), if no map_backplate is set
-- | -- | -- | --

**Comment by BruceCherniak** [comment]
Also, looking at commits, it appears that we have made some fixes to the `shadowCatcherPlane` since the 2.8 release (https://github.com/ospray/ospray/commit/ce42e06709e342dae31fc919acaad829d24a40ca).  I can't recall if that would affect your situation or not.
