### ISSUE TITLE
ospModelViewer + dragon.xml = no pixels

### ISSUE THREAD

**Issue by timsandstrom** [ospray/OSPRay#17]
Look like data is loading correctly, but nothing being drawn. No CPU activity at all.
This was pulled/built from sources today.

(tao:~/local/ospray-data/dragon) > /u/wk/tsandstr/local/ospray/build/ospModelViewer dragon.xml
#ospModelViewer: starting to process cmdline arguments
#ospModelViewer: done parsing. found model with
  - num meshes   : 1 [922849]
  - num instances: 1 [922849]
  - num unique triangles   : 922849
  - num instanced triangles: 922849
#ospModelViewer: number of instances matches number of meshes, creating single model that contains all meshes
#ospModelViewer: adding parsed geometries to ospray model
#ospModelViewer: committing model
#osp/trimesh: Verifying index buffer ... 
#osp/trimesh: Verifying vertex buffer ... 
#ospModelViewer: done creating ospray model.
#ospModelViewer: Adding a hard coded directional light as the sun.
#ospModelViewer: done creating window. Press 'Q' to quit.
#ospModelViewer: set world bounds [(-6.83587, -0.431891, -6.93969); (7.11329, 7.60655, 5.10773)], motion speed 0.0201081

**Comment by ingowald** [comment]
Hey, Tim,

Can you tell us what branch (or git hash) you have been using?
Also, please run with "--osp:debug", and let us know the output, as well 
as what architecture you have been using.

I just updated to current sources (in devel tree), and rebuilt, and it 
works fine on my side ... and the output it makes are actually exactly 
the right ones, so I'm a bit confused ... !?

Ingo

**Comment by timsandstrom** [comment]
Arg, new to git, not sure how to get that info.
Lemme try... well, doesn't look like v0.8.1 does it.

If yours work then it's probably user-error on my part.

(tao:~/local/ospray) > git rev-parse --verify HEAD
8723ce62037b5853a28613f16f71041ed769114c

(tao:~/local/ospray) > git log -n 1
commit 8723ce62037b5853a28613f16f71041ed769114c
Merge: e7cb749 f639788
Author: Gregory P. Johnson <gregory.p.johnson@intel.com>
Date:   Fri May 8 11:56:13 2015 -0500

     Merge branch 'release-0.8'

---

> ospModelViewer --osp:debug dragon.xml

Embree Ray Tracing Kernels 2.3.3 (May 18 2015)
   Compiler : GCC 4.9.2
   Platform : Linux (64bit)
   CPU      : SSE SSE2 SSE3 SSSE3 SSE41 SSE42 POPCNT AVX F16C RDRAND
   Features : intersection_filter bufferstride
general:
   build threads = 1
   verbosity     = 2
triangles:
   accel         = default
   builder       = default
   traverser     = default
   replications  = 2
motion blur triangles:
   accel         = default
   builder       = default
   traverser     = default
hair:
   accel         = default
   builder       = default
   traverser     = default
   replications  = 3
subdivision surfaces:
   accel         = default
#ospModelViewer: starting to process cmdline arguments
#ospModelViewer: done parsing. found model with
   - num meshes   : 1 [922849]
   - num instances: 1 [922849]
   - num unique triangles   : 922849
   - num instanced triangles: 922849
#ospModelViewer: number of instances matches number of meshes, creating single model that contains all meshes
#ospModelViewer: adding parsed geometries to ospray model
#ospModelViewer: committing model
#osp/trimesh: Verifying index buffer ...
#osp/trimesh: Verifying vertex buffer ...
building BVH4<triangle4> with sse2::BVH4Builder() ... [DONE]
   dt = 7068.84ms, perf = 0.130552 Mprim/s
   primitives = 922849, vertices = 0, hash= 26839253013198374
   sah = 1.0000, depth = 18
   used = 68.3 MB, perPrimitive = 74.0 B
   alignedNodes = 79799 (89.0% filled) (10.2 MB) (15.0% of total)
   leaves = 204397 (58.1 MB) (85.0% of total)
   vertices = 0 (0.0 MB) (0.0% of total) (75.0% used)
created scene intersector
   accels[0]
     intersector1  = sse41::BVH4Triangle4Intersector1Moeller
     intersector4  = sse42::BVH4Triangle4Intersector4HybridMoellerNoFilter
selected scene intersector
   intersector1  = sse41::BVH4Triangle4Intersector1Moeller
   intersector4  = sse42::BVH4Triangle4Intersector4HybridMoellerNoFilter
#ospModelViewer: done creating ospray model.
#ospModelViewer: Adding a hard coded directional light as the sun.
#ospModelViewer: done creating window. Press 'Q' to quit.
#ospModelViewer: set world bounds [(-6.83587, -0.431891, -6.93969); (7.11329, 7.60655, 5.10773)], motion speed 0.0201081
Embree: Invalid operation, (rtcIntersect8 not supported)
Embree: Invalid operation, (rtcIntersect8 not supported)
...

-------------------------

**Comment by timsandstrom** [comment]
upon further inspection, my ispc is out of date [and llvm as well...] rebuilding... apologies :(

**Comment by ingowald** [comment]
Ah; old ISPC version might explain it - the current version uses 
multi-ISA build that may not be fully supported by an older ISPC. (We do 
actually check the ISPC version when you first run cmake to check for 
that case; but that check doesn't work if you _update_ in an existing 
repo, which is what I suppose happened).

Please update your ISPC, and ideally remove your build directory and 
re-ccmake from scratch in a new build directory (just to be sure).

Let us know if that fixes it; until verified that it works I'll leave 
this open.

Cheers,

Ingo

**Comment by timsandstrom** [comment]
OK, further updates...

so, cmake/gcc.make was not parsing the gcc --version output correctly
thus setting OSPRAY_COMPILER_SUPPORTS_AVX and OSPRAY_COMPILER_SUPPORTS_AVX2 to FALSE.

fixing that though, resulted in a compiler fail:

cd /u/wk/tsandstr/local/ospray/release/builddir/ospray/intel64 && g++   -DEMBREE_DISABLE_HAIR=1 -D__BUFFER_STRIDE__ -D__EXPORT_ALL_SYMBOLS__ -D__FIX_RAYS__ -D__INTERSECTION_FILTER__ -D__TARGET_AVX2__ -D__TARGET_AVX__ -D__TARGET_SSE41__ -D__TARGET_SSE42__ -fPIC -fno-strict-aliasing -DDEBUG  -g     -Wstrict-aliasing=1 -I/u/wk/tsandstr/local/ospray/release -I/u/wk/tsandstr/local/glut-3.7/include -I/u/wk/tsandstr/local/ospray -I/u/wk/tsandstr/local/ospray/release/builddir/ospray/intel64 -I/u/wk/tsandstr/local/ospray/ospray/embree -I/u/wk/tsandstr/local/ospray/ospray/embree/include -I/u/wk/tsandstr/local/ospray/ospray/embree/common -I/u/wk/tsandstr/local/ospray/ospray/embree/kernels -I/u/wk/tsandstr/local/ospray/ospray/embree/kernels/xeon    -mf16c -mavx2 -mfma -mlzcnt -mbmi -mbmi2 -o CMakeFiles/ospray_embree_avx2.dir/embree/kernels/xeon/geometry/instance_intersector8.cpp.o -c /u/wk/tsandstr/local/ospray/ospray/embree/kernels/xeon/geometry/instance_intersector8.cpp
/tmp/ccLi6Kxi.s: Assembler messages:
/tmp/ccLi6Kxi.s:3365: Error: suffix or operands invalid for `vpcmpeqd'

manually setting OSPRAY_COMPILER_SUPPORTS_AVX2 to FALSE in cmake/gcc.make
results in a successful compile and rendering...

So, thanks so much for your attention and help,

-Tim

---

  CPU: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
   OS: Linux version 2.6.32-504.16.2.el6.x86_64 (mockbuild@x86-028.build.eng.bos.redhat.com)
       (gcc version 4.4.7 20120313 (Red Hat 4.4.7-9) (GCC) ) #1 SMP Tue Mar 10 17:01:00 EDT 2015
  gcc: 4.9.2
ispc:Intel(r) SPMD Program Compiler (ispc), 1.8.2dev (build commit ebe165dff87213ce @ 20150519, LLVM 3.5)

(tao:~/local) > ./bin/llvm-as -version
LLVM (http://llvm.org/):
   LLVM version 3.5.1
   Optimized build with assertions.
   Built May 18 2015 (21:49:13).
   Default target: x86_64-unknown-linux-gnu
   Host CPU: core-avx-i

**Comment by johguenther** [comment]
The new release of OSPRay (and the master branch) now correctly detects the version of GCC.
