### ISSUE TITLE
rnl_probe.pfm location issue

### ISSUE THREAD

**Issue by ami-GS** [ospray/ospray#170]
Hello team,

Recently I play around SDVis, looks great technology:), and I found issue with ospExampleViewer.

When I tested Sam Miguel example with ospExampleViewer, it issued error as bellows.
> #osp:miniSG: could not open texture file '/rnl_probe.pfm'.
> Failed to load hdri-light texture 'rnl_probe.pfm'
> Failed to load hdri-light texture 'rnl_probe.pfm'

This says ‘/rnl_probe.pfm’ so that I believe the file path is hard coded and referring it from ‘/‘, because I tried to put rnl_probe.pfm to ‘/‘ and run, then it output as 
> Successfully loaded hdri-light texture ‘rnl_probe.pfm'
> Successfully loaded hdri-light texture ‘rnl_probe.pfm'

the command I tested was 
> ../../cent_release_icc/ospExampleViewer san-miguel/sanMiguel.obj -r pt --max-depth 15 --sun-int 50 -vp -2.198506 3.497189 23.826025 -vu 0.000000 1.000000 0.000000 -vi -2.241950 2.781175 21.689358 --hdri-light 20 rnl_probe.pfm --sun-dir .1 -1 -.2

and environment is bellow, but I think this issue is not related to this environment. Just FYI.

> centOS 7.3, built with intel compiler (included in parallel studio xe 2017 update4), embree 2.16.4, ispc 1.9.1

Best Regards,
Daiki

**Comment by wilsonCernWq** [comment]
I remember using ./rnl_probe.pfm will work.

**Comment by johguenther** [comment]
Thanks for reporting. The issue will be fixed in the next release (with the SG based viewer).

**Comment by ami-GS** [comment]
@wilsonCernWq 

thanks for that comment:) how and where did you set it?

thanks

**Comment by johguenther** [comment]
Simply change the commandline (to `... --hdri-light 20 ./rnl_probe.pfm ...`).

**Comment by ami-GS** [comment]
Wow... I am embarrassed...
I could not find `rnl_probe.pfm` in source code and command itself has, thats why the error was issued.
It means Example viewer is seeing file from root, it is kind of bug.

Thanks

**Comment by carsonbrownlee** [comment]
No reason to be embarrassed other than on our end, I updated the demos page to use "./rnl_probe.pfm". This should also be fixed in our new viewer in devel, however we will need to update the entire demo page for the upcoming release.
