### ISSUE TITLE
path tracer has no effect for a metal OBJ material

### ISSUE THREAD

**Issue by cshan** [ospray/ospray#173]
I have a obj file with a metal material, but looks like it is not correct in path tracer, maybe missing reflection when I setup a quad light.

**Comment by johguenther** [comment]
See also #161.

**Comment by carsonbrownlee** [comment]
hi Cshan, I believe this is a duplicate issue to the one Johannes linked to.  Try setting the roughness to 0 for reflectance to take affect, we are actively looking into this.

**Comment by cshan** [comment]
@carsonbrownlee Sorry, I mean it is not a metal material, it is a OBJMaterial from a obj file, but the OBJMaterial's params is for metal material. I am not sure I describe correctly.

**Comment by johguenther** [comment]
Hi,
can you please post the parameter values you use to set a "metal" OBJ material? And maybe an image or a description what is wrong / what you expect?
Thanks,
  Johannes

**Comment by carsonbrownlee** [comment]
note that if you have an obj material file and it specifies a "type" parameter, ie 
"type Metal" the obj loader will create a "Metal" material, not an OBJMaterial.

**Comment by cshan** [comment]
Thanks, but looks like Metal material does not support texture?

**Comment by carsonbrownlee** [comment]
hi cshan, currently "OBJMaterial" is the only Material type that supports textures in the path tracer.  You can create a metallic look through the OBJMaterial by increasing the reflectance if that works, otherwise if you are comfortable writing code you might create a new material based on "Metal" that supports whatever texture utilization you want.

**Comment by cshan** [comment]
@carsonbrownlee thank you very much, I using a specular color texture map in the mtl file looks effect is great, but need change the Ks > 0.0, I found these code in OBJ.ispc:
  if (reduce_max(Ks) > 0.0f)
    MultiBSDF_add(bsdf, Specular_create(ctx, shadingFrame, Ks, Ns), luminance(Ks));
