### ISSUE TITLE
How to setup a reflection map?

### ISSUE THREAD

**Issue by cshan** [ospray/ospray#175]
Hi,

I want to setup a environment map for a Obj model, but looks like ospray does not support reflection map from OBJMaterial. does anywhere have a way to set the environment map?

Thanks

**Comment by johguenther** [comment]
I think the [HDRI light](http://www.ospray.org/documentation.html#hdri-light) is what you are looking for: it uses a 360degree, lat-long environment texture to illuminate the scene from infinity, thus you'll see that texture also reflected in shiny objects. However, you need to use the pathtracer.

**Comment by cshan** [comment]
@johguenther HDRI Light is for the lighting, not reflection map, I tried it, not work well.

**Comment by johguenther** [comment]
In OSPRay there is no distinction between lighting and reflection, it's kind of the same.
What did not work well for you? Here on object with the OBJ material "illuminated" by the an HDRI light showing nice reflections (you need a very high `Ns`, like 50000, for sharp reflections):
![reflection](https://user-images.githubusercontent.com/9035336/30367606-f43cf016-986e-11e7-9774-65aa019df9c9.jpg)

**Comment by cshan** [comment]
@johguenther Thanks, change the Ns to 50000 working well, thanks again.
