### ISSUE TITLE
The texture and the color of the objects are missing in certain frames

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#176]
The color of the background is white and the obj is skin colored. But in few frames its getting mixed up

![renderdimage11](https://user-images.githubusercontent.com/23516228/30425163-e47e369c-9965-11e7-9554-552330b8cede.jpg)
![renderdimage12](https://user-images.githubusercontent.com/23516228/30425164-e4a4f0f2-9965-11e7-9d60-94877467c9e0.jpg)
![renderdimage19](https://user-images.githubusercontent.com/23516228/30425165-e4cd0dda-9965-11e7-9355-124a9ba219de.jpg)

**Comment by johguenther** [comment]
Which version are you using, did you try latest the `devel` branch? Is it possible to provide a (small) reproducer?

**Comment by johguenther** [comment]
Is the issue still open?

**Comment by swatinair123** [comment]
Yes, we had taken the latest devel branch (the branch of 1.3x) .

**Comment by swatinair123** [comment]
But the issue was still there

**Comment by johguenther** [comment]
It's just those two objects (the animal and the floor)? Do you change anything in the scene in between frames?

**Comment by swatinair123** [comment]
No , i am jus looping through with many objs . So the issue is for certain frames. I am using 
numWarmupFrames = 100; numBenchFrames = 50;

**Comment by johguenther** [comment]
In the loop, for new obj, do you again use ` ospSetMaterial` and `ospCommit` for it?

**Comment by swatinair123** [comment]
yes yes . I am using it.

**Comment by swatinair123** [comment]
Hi ,

This is the code i am using to load 15 objs in a loop

int main(int argc, const char *argv[]) {

	int init_error = ospInit(&argc, argv);
	if (init_error != OSP_NO_ERROR) {
		std::cerr << "FATAL ERROR DURING INITIALIZATION!" << std::endl;
		return init_error;
	}
	const char *BackgroundFilename = "G:\projects\Newfolder\crytek-sponza\sponza.obj";
	String FileName;
	for (int i = 0; i <15; ++i)
	{
		FileName = "G:\\animals_obj\\deer\\deer_"+to_string(i)+".obj";
		const char *ForegroundFilename = FileName.c_str();
		GetRenderedImage(BackgroundFilename, ForegroundFilename,i);////I am using the code from bench .cpp																	  
		
	}
	return 0;
}

The above function GetRenderedImage saves the rendered .ppm image for each objs .
Here i am facing the issues of texture mixing between the foreground and Background.

Can you please suggest any method to clear the buffer after each loop.

I tried intitializing ospray tracing engine inside the loop. But it gives me an error 3.

The issue is only when i load it in a loop.

If i load individual objs withou loop my rendered image is fine

**Comment by swatinair123** [comment]
![output_wp12](https://user-images.githubusercontent.com/23516228/31371098-ce07ec9a-adac-11e7-8c9c-7161edb3afe9.jpg)
![output_wp13](https://user-images.githubusercontent.com/23516228/31371099-ce36f63e-adac-11e7-92e4-34d980d4d42d.jpg)
These are few other examples
![outputnew0](https://user-images.githubusercontent.com/23516228/31371124-ee6018e6-adac-11e7-9a38-91959520eaf8.jpg)
![outputnew10](https://user-images.githubusercontent.com/23516228/31371125-ee8d9082-adac-11e7-8999-d877ffd6b6f7.jpg)

**Comment by johguenther** [comment]
Yes, it seems that the scene's object and texture IDs get mixed up when load the animation in a loop like shown above.

If performance is not a concern you can indeed just completely  setup OSPRay from scratch for each animation frame: instead of using `ospInit` use (at the beginning of the loop)
```cpp
auto dev = ospNewDevice("default");
ospDeviceCommit(dev);
ospSetCurrentDevice(dev);
```

**Comment by swatinair123** [comment]
Ok . Thanks a lot

**Comment by swatinair123** [comment]
Hi ,Should we free the  dev at the end of the loop. If so pls suggest how to release dev at the end of the loop.

**Comment by johguenther** [comment]
You can call `ospRelease(dev)` at the end of the loop. What does "break" mean, it crashes?

**Comment by swatinair123** [comment]
Yes it crashes (giving exception)

**Comment by johguenther** [comment]
It is difficult to provide suggestions with so incomplete information (e.g. what exception, or what happens in `GetRenderedImage`). From what I understand you like to kind of render a movie, from a scene with static parts and an animation. Your latest images seem to be based on the [Animated Woody demo](http://www.ospray.org/demos.html#animated-woody) &ndash; that demo works without texture or color changes, so the problem is probably somewhere in your code.

Another idea: if the first frame works, how about having the loop completely outside, e.g. a script calling your application with changing arguments for "deer_"+i+".obj"?

**Comment by johguenther** [comment]
Please re-open if the issue is still not solved with the latest release.
