### ISSUE TITLE
Orthographic projection bug ?

### ISSUE THREAD

**Issue by benjha** [ospray/ospray#179]
Hello,

I am rendering a 4 billion atom system using the precompiled OSPray 1.3.0  version. I generate several Geometry groups to avoid the "too many spheres" error. My code  uses perspective (no field of view) and orthographic projection. When switching to orthographic projection, atom clusters closer to the camera appears detailed as expected, but very distant clusters  appears blurred (see attachment). 

![sight_2017-09-28_11_24_45](https://user-images.githubusercontent.com/10212097/31198508-89ba5d22-a922-11e7-9d3b-ef91128277ea.png)

In other cases everything appears blurred and/or spheres are rendered as flat squares (snapshot of a different system):

![sight_2017-10-04_13_08_53](https://user-images.githubusercontent.com/10212097/31199899-dfe6966c-a926-11e7-9a63-dd418040e966.png)

The orthogonal projection is defined by:

`m_OSPcamera= ospNewCamera("orthographic");`
`ospSet1f		(m_OSPcamera, "aspect", (float)m_screenSize.x/(float)m_screenSize.y);`
`ospSet1f		(m_OSPcamera, "height", m_camera->zoom()* bb_extend[0] );`

where bb_extend[0] is the size of the bounding box in X direction.

The renderer configuration is:

`ospSet1i		(m_renderer, "aoSamples",			1			);`
`ospSet1f		(m_renderer, "aoDistance", 			0.0f		);`
`ospSet1i		(m_renderer, "spp",					1			);`
`ospSet1i		(m_renderer, "maxDepth", 			128			);`
`ospSet1i		(m_renderer, "oneSidedLighting",	false		);`
`ospSet1f		(m_renderer, "varianceThreshold",	5.5f		);`

I am wondering if there is a bug in the orthogonal projection or If I only need to tune more the renderer parameters   ?

Thanks,

Benjamin

**Comment by johguenther** [comment]
Interesting. So the blurring does not occur with the perspective camera?

I suspect this is related to float precision:
- Are the Geometry groups directly added to the model or are you using Instances?
- Can you please try adding `RTC_SCENE_ROBUST` to the `traversal_flags` in `ospray/common/Model.ispc::Model_init()`?
- To see the issue better could we eliminate secondary rays , i.e. `maxDepth`=1, no shadows (`shadowsEnabled`=false), solid material without transparency?

**Comment by benjha** [comment]
Thanks for your response.

The issue only occurs with orthographic projection.  The geometry groups are directly added to the model.

I disabled the ambient light and ambient occlusion, and set the parameters you suggested but the problem remains. I attached a set of pictures so you can have a better view of how the system looks like:

![sight_2017-10-05_10_38_38](https://user-images.githubusercontent.com/10212097/31246516-a513cbd0-a9db-11e7-807a-c6759df32a7d.png)

![sight_2017-10-05_10_38_56](https://user-images.githubusercontent.com/10212097/31246524-aacdaa8c-a9db-11e7-93bd-aa002d819437.png)

![sight_2017-10-05_10_39_10](https://user-images.githubusercontent.com/10212097/31246535-ae6c891a-a9db-11e7-89a1-98d47db44bbe.png)

![sight_2017-10-05_10_39_21](https://user-images.githubusercontent.com/10212097/31246544-b53363ae-a9db-11e7-9c1d-f05c48af9dac.png)

![sight_2017-10-05_10_39_41](https://user-images.githubusercontent.com/10212097/31246556-bb893ea4-a9db-11e7-8eb6-417cda13f2cc.png)

![sight_2017-10-05_10_39_29](https://user-images.githubusercontent.com/10212097/31246552-b82c2758-a9db-11e7-88a2-c06762dc0e50.png)


In order to set the `RTC_SCENE_ROBUST`, I need to compile  by myself OSPray right ?

Regards,

Benjamin

**Comment by jeffamstutz** [comment]
Yes, you would need to compile OSPRay from source using the suggested code change. Let us know if you have any issues doing that or would like any pointers. I think it's simple, but I'm NOT the best person to make that judgement. ;)

I/we can also look into generating a random block of spheres at roughly the same size to see if we can reproduce this ourselves (i.e. not needing your app + data). Do you have a particular strategy for how you divide up the data into multiple geometries? (e.g. slices along a particular axis or more randomly assembled)

**Comment by benjha** [comment]
Got it, I have past experience on compiling OSPRay.

No, there is not a particular strategy, I am just setting the particles in groups of the same size as they appear in the dataset, then generate the geometry for each particle group. Inside the dataset each particle doesn't have a specific order.

The size of the bounding box may help you to reproduce the problem:

Min = {-0.305125, -0.294927, -158.355 } 
Max = {987.633, 987.657, 5701.22 } 

and the radius of each sphere is 0.75

Thanks,

**Comment by johguenther** [comment]
I can reproduce the issue: the blurring is indeed caused by insufficient float precision in the sphere intersection code. You can also see the same artifacts with the perspective camera if you zoom into far away spheres (using a tiny `fovy`). So, the fix will be to improve the accuracy of the ray-sphere intersection.

**Comment by johguenther** [comment]
Ah, and BTW: `RTC_SCENE_ROBUST` does not help.

**Comment by benjha** [comment]
Thanks for the update.

**Comment by johguenther** [comment]
Please try the latest `devel` to check your problem is really solved.

**Comment by benjha** [comment]
The artifacts have gone.

Thanks
