### ISSUE TITLE
compile error in RawVolumeFile (master branch)

### ISSUE THREAD

**Issue by ingowald** [ospray/OSPRay#18]
Macbook, SSE target, clang compiler.
Check out master, enable volume viewer and loaders module, then I get:

/Users/wald/Projects/ingowald-ospray/modules/loaders/RawVolumeFile.cpp:98:5: warning: cannot delete expression with
      pointer-to-'void' type 'void *'
    delete [] voxelData;

Probably appears similarly in other branches.

**Comment by ingowald** [comment]
Note its just a _warning_, not a compile _error_ as the title might indicate.

**Comment by johguenther** [comment]
This is fixed in devel (1ab79d13).
