### ISSUE TITLE
FindGLFW.cmake has errors, I think

### ISSUE THREAD

**Issue by timsandstrom** [ospray/ospray#180]
I don't think the cmake 'SET' command supports HINTS/PATH_SUFFIXES

instead of:
SET(GLFW_HINTS ... )
SET(GLFW_PATHS ... ) 
FIND_LIBRARY(GLFW_LIBRARY ...)

I used this instead:

FIND_LIBRARY( GLFW_LIBRARY
    NAMES
        glfw
        glfw3
    HINTS
        "$ENV{GLFW_ROOT}/lib"
        "$ENV{GLFW_ROOT}/lib64"
        "${GLFW_ROOT}/lib"
        "${GLFW_ROOT}/lib64"
    PATHS
        /usr/lib
        /usr/lib64
        /lib
        /lib64
    DOC
        "the GLFW library"
)

**Comment by johguenther** [comment]
`SET` is just used to capture the strings, including "HINT", which are the passed unprocessed to `FIND_LIBRARY`, so I think this is fine. Anyway, I [ironed out this and other issues](/ospray/ospray/commit/eb378503212f8c1b23048ad842bce430c0cd502e) that became obvious by your comment – thanks!
