### ISSUE TITLE
How to support PBR Model

### ISSUE THREAD

**Issue by cshan** [ospray/ospray#183]
Does ospray have a plan to support PBR model? I have some model is PBR based, is possible ospray can directly use color, metallic, normal and roughness mapping will be great!

**Comment by johguenther** [comment]
OSPRay's example viewer does not have a native importer for PBR models. However, we recently added [more materials and features](/ospray/ospray/tree/devel#materials) to the path tracer. Thus OSPRay should be able to cover most PBR materials, including roughness mapping (albeit no anisotropy yet).
