### ISSUE TITLE
Link error in ospray build

### ISSUE THREAD

**Issue by biddisco** [ospray/ospray#184]
I installed ispc on arch without problem
`pacman -Si ispc`
```
Repository      : community
Name            : ispc
Version         : 1.9.1-1
Description     : A compiler for high-performance SIMD programming on the CPU
Architecture    : x86_64
URL             : https://ispc.github.io/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : ncurses  zlib
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 10.20 MiB
Installed Size  : 40.65 MiB
Packager        : Lukas Jirkovsky <l.jirkovsky@gmail.com>
Build Date      : Sun 07 Aug 2016 05:02:04 PM CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

I checked out embree from github and compiled against `tags/v2.17.0` which is the most recent release (as of the time of writing).
I compiled embree without problem using the default cmake options except 
```
EMBREE_TASKING_SYSTEM=INTERNAL
```
Because I wanted to disable TBB (which is installed on the system). I did not perform a 'make install' step but instead instructed ospray to use the build directory of embree

I cloned the ospray repo and tried several tags including `1.4.0` and the master branch. 
I used default cmake settings apart from the following
```
OSPRAY_BUILD_ISA=AVX2
embree_DIR=~/build/embree
```
and embreee does correctly generate the cmake config file in it's build dir and is picked up without problem by ospray. 

My compiler in all cases is `gcc (GCC) 7.2.0` (a bit new, sorry). and the CPU I'm using (laptop) supports avx2
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
stepping        : 9
microcode       : 0x5e
cpu MHz         : 799.975
cache size      : 6144 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            :
bogomips        : 5618.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
....
etc for other cores
```
All targets that link to the ospray/embree core libs fail with
```
[  5%] Built target ospray_common
[ 58%] Built target ospray
[ 60%] Linking CXX executable ../ospTutorial
../libospray.so.1.4.0: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unuavx2'
../libospray.so.1.4.0: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unusse2'
collect2: error: ld returned 1 exit status
```
which would appear to be a symbol export problem for some of the sse/avx kernels.

I tried a few tags of embree/ospray, but gave up after half a dozen combinations and hope that there is a simple fix.

**Comment by wilsonCernWq** [comment]
It looks like embree is causing the problem. Have you tried to use a lower version of embree ? For example 2.15 or 2.16 ?

**Comment by biddisco** [comment]
embree 
```
v2.17.0 : link errors reported above
v2.16.5 : as above
v2.15.1 : Even more link errors with more symbols missing
v2.14.0 : Lots of compile errors
```

**Comment by svenwoop** [comment]
The problem here is that Embree is by default compiled in multi-ISA mode (SSE2,SSE4.2,AVX, and AVX2) when the EMBREE_MAX_ISA is set to AVX2 (the default). If you set the OSPRAY_BUILD_ISA to AVX2, then Ospray builds only with AVX2 support. The link issues are than caused as AVX2 ISPC symbols generated by Ospray in single ISA mode are not compatible with the AVX2 ISPC symbols created by Embree in multi-ISA mode. This is an issue of the ISPC compiler.

To workaround this, Embree and Ospray should be compiled with the same ISAs enabled. Thus just set EMBREE_MAX_ISA to NONE, and then enable only EMBREE_ISA_AVX2.

**Comment by biddisco** [comment]
Thank you. It compiles ok now.

**Comment by johguenther** [comment]
Hmm, still, this should actually work, because [OSPRay has special code to workaround](/ospray/ospray/blob/master/components/ospcommon/cmake/macros.cmake#L122-L147) that issue.

**Comment by johguenther** [comment]
I could not reproduce the original problem. The linker error shows that OSPRay uses the workaround and is configured for ISPC targets `sse2` and `avx2`. For some unknown reason the respective symbols cannot be found in Embree.

**Comment by ArchangeGabriel** [comment]
Note that it should not matter now for Arch, we are building ispc, embree and ospray with all ISA enabled. ;)
