### ISSUE TITLE
Jittering of image when rendering w/o accumulation in MPI mode

### ISSUE THREAD

**Issue by tribal-tec** [ospray/ospray#185]
A framebuffer created without OSP_FB_ACCUM causes a jittered image every ospRenderFrame() in the MPI mode using --osp:mpi. Without MPI this works as expected where the image stands 'still'.

This was introduced with this commit:
https://github.com/ospray/ospray/commit/615dffb

I have no clue right now how to fix that, hopefully you guys have an idea.

**Comment by johguenther** [comment]
Thanks for already bisecting the faulty commit. The problem is that `accumID` is increased even when no accumulation happens, and since accumID is used to seed the RNG this results in jittering. So, the fix will come soon. :-)

**Comment by tribal-tec** [comment]
Yeah, I already bisected it because I was sure that this worked at a certain point. Thx for the fast response and looking forward to the fix.

**Comment by tribal-tec** [comment]
Thx for the quick fix! Will this be available also on the master branch soon? Like you plan to do a patch release anytime soon?

**Comment by jeffamstutz** [comment]
I'd like to have a ```v1.4.1``` release before Supercomputing next month, which seems very doable...it's just a matter of how many _other_ fixes make it in that release. :)
