### ISSUE TITLE
Clipping planes feature

### ISSUE THREAD

**Issue by benjha** [ospray/ospray#186]
Hello,

Does OSPray provide a clipping plane feature similar to OpenGL's clip planes ? The idea here is to make cuts to explore atomistic models' inside.

Regards,

**Comment by carsonbrownlee** [comment]
Volumes in OSPRay support clipping by specifying the bounds of the "volumeClippingBoxLower"/Upper.  A clipping plane for geometry is left up to the user though should not be difficult to add.

**Comment by johguenther** [comment]
Clipping planes (and more general clipping geometries) are not yet supported in OSPRay, but that feature is on the TODO list (see also #84).

**Comment by paulmelis** [comment]
Would indeed be great to have general clipping planes, for hiding parts of models

**Comment by straaljager** [comment]
I concur, this feature is high on our wishlist. 

We have been able to hack in clipping planes for now, but they also clip any secondary rays, resulting in very dark clipping surfaces when not using basic ray casting.

**Comment by straaljager** [comment]
> This is rather high on the list and should arrive within the next months (**end of this year**, earlier is really tough).

Any updates on this?

**Comment by johguenther** [comment]
Well, yes, this is embarrassing, but the clipping feature is still not implemented. We are about to start the implementation with the goal to have it in v2.0. Let's hope this time it does not get pushed to later.

**Comment by straaljager** [comment]
Good to know thanks. Clipping planes are essential for scientific visualization.

**Comment by jeffamstutz** [comment]
FYI: We've pushed this to `v2.1`. We have extensive experience with prototypes of the feature, so it looks promising to have this robust and ready soon.

**Comment by johguenther** [comment]
This is actually supported now, see examples in https://github.com/ospray/ospray/issues/84#issuecomment-487026829.
