### ISSUE TITLE
Issue with bench.cpp in the new version 1.4x of ospray

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#188]
Hi,

I am working with bench.cpp the 1.4x version of the ospray .  The new version build fine . But the code bench.cpp and ospBenchmark.exe  crashes when we give the command arguments  as in the image below. Please advise.
![error](https://user-images.githubusercontent.com/23516228/31930348-0cace516-b8bd-11e7-9f79-e9dcdca2d037.png)

From the cmd we tried running the command
 ospBenchmark.exe G:/projects/Newfolder/wooddoll/wooddoll_3.obj .
But we are getting the error as below
![error](https://user-images.githubusercontent.com/23516228/31931127-c438ae52-b8bf-11e7-9c4c-7fbac0ab7623.png)

**Comment by johguenther** [comment]
Thanks for reporting. Fix is in `release-1.4.x` branch.

**Comment by swatinair123** [comment]
Hi .I was able to fix it.

**Comment by swatinair123** [comment]
Thanks a lot
