### ISSUE TITLE
Lighting issue

### ISSUE THREAD

**Issue by pratikshaandhare** [ospray/ospray#189]
Hi,

I am trying for the lights(point, quad and spot) in bench.cpp of ospray 1.3x. I had used scivis renderer.  On the plane without texture the light is continuous and smooth  but I am not getting the smooth and continuous shading of light on the textured plane. 

![p5add](https://user-images.githubusercontent.com/20615346/31940290-3695205a-b8db-11e7-8cc2-2985fb5cb525.jpg)
![p6](https://user-images.githubusercontent.com/20615346/31940291-36edf18a-b8db-11e7-9b7b-c524805957e7.jpg)
![p11add](https://user-images.githubusercontent.com/20615346/31940292-372cedc2-b8db-11e7-8d68-5351ef047017.jpg)
![p12](https://user-images.githubusercontent.com/20615346/31940293-37686f3c-b8db-11e7-8a70-8dfbd5ac3e6a.jpg)

 The image  is attached here. Please kindly advise.

**Comment by johguenther** [comment]
Please have a look at the [documentation](http://www.ospray.org/documentation.html): you can get a smoother light cone with the `spot` light by setting its `penumbraAngle ` parameter. If you like to get soft shadows you need to use the path tracer (SciVis only supports hard shadows) and use "area" lights (e.g. `radius` > 0, or the `quad` light, or the `hdri` light).

**Comment by carsonbrownlee** [comment]
marking as resolved.
