### ISSUE TITLE
Minor mistake in "getting ospray" page

### ISSUE THREAD

**Issue by resuna** [ospray/OSPRay#19]
This is minor but should probably be fixed.

Web page ( http://ospray.github.io/getting_ospray.html ) shows the current directory as "~/Projects" instead of "~/Projects/ospray/release" (or probably just "release" assuming a typical prompt setting) when running the "ccmake" and "make" commands.

    Create a build directory, and go into it

      user@mymachine[~/Projects]: mkdir ospray/release
      user@mymachine[~/Projects]: cd ospray/release

    Open the CMake configuration dialog

      user@mymachine[~/Projects]: ccmake ..

    Make sure to properly set build mode, desired Instruction set to build for (SSE, AVX, AVX2), enable the components you need, etc; then type ’c’onfigure and ’g’enerate. When back on the command prompt, build it using

      user@mymachine[~/Projects]: make

    You should now have libospray.so as well as a set of sample viewers. You can test your version of OSPRay using any of the examples on the OSPRay Demos and Examples page.

Prompts should actually look something like:

      user@mymachine[~/Projects]: mkdir ospray/release
      user@mymachine[~/Projects]: cd ospray/release
      user@mymachine[release]: ccmake ..
      user@mymachine[release]: make

**Comment by johguenther** [comment]
Thanks for spotting! I corrected the page.
