### ISSUE TITLE
Changing the affine tranformation matrix in 1.4x

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#192]
Hi ,
I am working with bench.cpp of 1.4x version . Can you please tell me how to set the affine transformatiion marix for each obj loaded  . in 

for (auto file : files) {
			FileName fn = file;

			if (fn.ext() == "ospsg")

				sg::loadOSPSG(renderer_ptr, fn.str());
			else {
				auto importerNode_ptr = sg::createNode(fn.name(), "Importer");
				auto &importerNode = *importerNode_ptr;
				importerNode["fileName"] = fn.str();
				
				world.add(importerNode_ptr);
			}
		}

Thanks and Regards,
Swati

**Comment by johguenther** [comment]
The `ospExampleViewer` has command-line options to that the transformation, a feature that `ospBenchmark` does not yet offer.

What you need to do is to create a "`Transform`" scene graph node and add that as child to `world`, with the `importerNode_ptr` as its child (you can look into `ospExampleViewer.cpp::addImporterNodesToWorld()` as guide). The transformation can be set as a combination of "`position`", "`scale`" and "`rotation`", and/or the matrix (`affine3d`) in "`userTransform`".
