### ISSUE TITLE
Streamline rendering artifacts

### ISSUE THREAD

**Issue by jediati** [ospray/ospray#194]
I'm trying to render a scene with some streamlines, spheres, and a volume rendering, but i'm getting some strange results. For example, some of the cylinder parts of the streamlines are showing up as partially transparent.(e.g. see http://sci.utah.edu/~jediati/art/test.png)  If I increase the density of the lines (more points/line), it looks better, but when i do a high-resolution rendering i get artifacts that are pretty crazy. 

i'm making a high-res rendering (right now 40k x 11.2k, but want 78K), and the streamlines (and even spheres) are showing some strange behavior.  my current renderings are at http://sci.utah.edu/~jediati/art/newtest2.png

from sufficiently far away, the streamlines look fine, but zooming in, eg, in newtest2.png shows some serious artifacts.. 

not sure where to go from here... 
is this a precision issue? is there some workaround?

**Comment by jediati** [comment]
UPDATE: 

I replaced all my streamlines with simple spheres (and turned off volume rendering), and am still getting crazy artifacts. 
http://sci.utah.edu/~jediati/art/newtest5.png shows the high-res scene - zoomed out it looks like:

![capture_zoomout](https://user-images.githubusercontent.com/1343032/32280589-a8f7fd62-bed9-11e7-9bc8-83e2f89f8be8.PNG)
, at a 1:1 it looks like: 
![capture_zoomin](https://user-images.githubusercontent.com/1343032/32280652-d33ac80c-bed9-11e7-8039-3d299fa070e1.PNG)

the code to generate basically looks like:


//SCENE DIMS AND CAMERA
   const vec3i volume_dims(1536, 350, 256);
   float scale = 20.0;
   const vec2i img_size(2000*scale, 560*scale); 
   const vec3f cam_pos(vec3f(volume_dims) / 2.f + vec3f(0,0, volume_dims.z*8.0));
   const vec3f cam_dir = vec3f(volume_dims) / 2.f - cam_pos;
   const vec3f cam_up(0, 1, 0);
   read_lines();
   printf("done reading lines\n");
   // Setup the camera to render from
   OSPCamera camera = ospNewCamera("perspective");
   ospSet1f(camera, "aspect", img_size.x / static_cast<float>(img_size.y));
   ospSetVec3f(camera, "pos", (osp::vec3f&)cam_pos);
   ospSetVec3f(camera, "dir", (osp::vec3f&)cam_dir);
   ospSetVec3f(camera, "up", (osp::vec3f&)cam_up);
   ospSetf(camera, "fovy", 10.0f);
   ospCommit(camera);

   // Create the renderer we'll use to render the image
   OSPRenderer renderer = ospNewRenderer("scivis");
//SPHERES
   OSPGeometry spheres = ospNewGeometry("spheres");
   setup_spheres(spheres, volume_dims, renderer); // each sphere is radius 0.2
// LIGHTS
  // Create an ambient light, which will be used to compute ambient occlusion
   OSPLight ambient_light = ospNewLight(renderer, "ambient");
   ospSet1f(ambient_light, "intensity", 0.02);
   ospCommit(ambient_light);
   OSPLight sun_light = ospNewLight(renderer, "distant");
   ospSetVec3f(sun_light, "direction", osp::vec3f{0.f, 0.f, -1.f});
   ospSetVec3f(sun_light, "color", osp::vec3f{1.f, 1.f, 0.8f});
   ospSet1f(sun_light, "intensity", 0.96);
   ospSet1f(sun_light, "angularDiameter", 0);
   ospCommit(sun_light);
   std::vector<OSPLight> lights_list = {ambient_light, sun_light/*, fill_light*/};
   OSPData lights = ospNewData(lights_list.size(), OSP_LIGHT, lights_list.data(), 0);
   ospCommit(lights);

// RENDERER
  // Setup other renderer params
   ospSetObject(renderer, "model", model);
   ospSetObject(renderer, "camera", camera);
   ospSetObject(renderer, "lights", lights);
   //ospSet1i(renderer, "shadowsEnabled", 1);
   ospSet1i(renderer, "aoSamples", 0);
   ospSet1i(renderer, "spp", 32);
   ospSetVec4f(renderer, "bgColor", osp::vec4f{0.0f, 0.0f, 0.0f, 1.f});
   ospCommit(renderer);

   OSPFrameBuffer framebuffer = ospNewFrameBuffer((osp::vec2i&)img_size,
         OSP_FB_SRGBA, OSP_FB_COLOR);
   ospFrameBufferClear(framebuffer, OSP_FB_COLOR);

   // Finally, render the image and save it out
   ospRenderFrame(framebuffer, renderer, OSP_FB_COLOR);

**Comment by ingowald** [comment]
Hey

Are you actually at Utah? If so we can look at it together... send me an email to imgowald@gmail....

**Comment by ingowald** [comment]
Jedi,

Just commiited a fix that - at least in 'scale=1' resolution looks OK to 
me (see attached).

Haven't tested in fullest resolution yet (rendering only takes a few 
minutes on my 256-thread KNL, but your scalar png encoding code 'takes a 
while' on a gigapixel-image :-/)... but the fix _should_ work for higher 
resolutions, too.

Fix is implemented in branch iw/fix-streamline-artifacts, but should 
soon get merged into devel, too.

Cheers,

Ingo

**Comment by jeffamstutz** [comment]
I just merged and pushed @ingowald's fixes into ```devel```. Please reopen if these fixes do not work for you.

Thanks!
