### ISSUE TITLE
Porting to OS X

### ISSUE THREAD

**Issue by nyue** [ospray/ospray#196]
Hi,

  I have successfully build ospray on OS X 10.10 but when I run the Benchmark or ExampleViewer, I get the following errors. Just wondering if there are specific tweaks to Embree for ospray to work. I have enabled ISPC using the latest 1.9.1

=============
env DYLD_LIBRARY_PATH=~/systems/tbb/tbb44_20151115oss/lib:$DYLD_LIBRARY_PATH ~/systems/ospray/v1.4.0/bin/ospExampleViewer 
dyld: lazy symbol binding failed: Symbol not found: _rtcNewDevice
  Referenced from: /Users/nicholas/systems/ospray/v1.4.0/bin/../lib/libospray.0.dylib
  Expected in: /Users/nicholas/systems/embree/v2.4.0/lib/libembree.2.dylib

dyld: Symbol not found: _rtcNewDevice
  Referenced from: /Users/nicholas/systems/ospray/v1.4.0/bin/../lib/libospray.0.dylib
  Expected in: /Users/nicholas/systems/embree/v2.4.0/lib/libembree.2.dylib

Trace/BPT trap: 5

Cheers

**Comment by johguenther** [comment]
Hi Nicholas,
I think your Embree version is way too old, it does not contain `rtcNewDevice`. The just released [OSPRay v1.4.1](https://github.com/ospray/OSPRay/releases/v1.4.1) needs at least Embree v2.15 (the [current version is v2.17](https://github.com/embree/embree/releases/tag/v2.17.0)).

Many Greetings,
  Johannes
