### ISSUE TITLE
Memory leak in ospray::Model

### ISSUE THREAD

**Issue by stukowski** [ospray/ospray#198]
Apparently the Embree scene allocated in this code line never gets released:

https://github.com/ospray/ospray/blob/216110455e4583190f3d8c3e52797f2769f91194/ospray/common/Model.ispc#L52

I would think ``rtcDeleteScene()`` has be to called at some point, e.g from the destructor of the ``ospray::Model`` class.

**Comment by jeffamstutz** [comment]
Thanks for catching this! We release the handle if the model is recommitted, but not when the object is released....we will get this into a ```v1.4.2``` release asap! (it is already on both ```release-1.4.x``` and ```devel``` if you build OSPRay from source)

Cheers,
Jeff

**Comment by stukowski** [comment]
Great. Thanks for fixing this. I will keep my eyes open for similar issues in the code.

**Comment by jeffamstutz** [comment]
This was implemented in the recent ```v1.4.2``` release.
