### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by stukowski** [ospray/ospray#199]
As a new user of OSPRay, who had to learn the API for the first time, allow me to point out a few issues in the documentation I came across. This is meant as a feedback to help improve the documentation in the future.

- The path tracer is documented, but not what string needs to be passed to ``ospNewRenderer`` to instantiate it.
- The SciVis renderer seems to work without any materials assigned to the geometries, but the path tracer seems to require materials. This is not mentioned.
- Geometries can be assigned colors. Materials also have a (diffuse) color. OSPRay seems to be mixing both colors, the per-geometry color and the material color. This should probably be documented somewhere.
- ``ospTutorial.cpp`` seems to be the minimal example for first time users. Even though a footnote (easy to overlook) mentions that there is also a C99 version, it was kind of surprising to me that ``ospTutorial.cpp`` uses a C++ API that hasn't been introduced yet.
- Even though the ``ospRelease`` function is introduced in the docs, it is not being used in the code example. Because of this, I got the (wrong) impression that the C++ wrapper classes take care of memory management and reference counting automatically. See issue #112. I finally ended up writing a C++ wrapper class template for ospray's wrapper classes to take care of the memory management! I guess this situation can be improved.

**Comment by jeffamstutz** [comment]
Thanks for the feedback! We would be happy to update the docs with fixes for the issues you mentioned. We can add that to the upcoming ```v1.4.2``` release.

**Comment by johguenther** [comment]
Your comments are very much appreciated &ndash; sometime we indeed have blind spots...
Points 1, 2 and 4 have been addressed.
Re point 3: The material documentations mentions for which material color the per-geometry color is "also used"; I guess this formulation is too subtle?
Re last point: I agree there is much to improve wrt. to memory management and `ospRelease`; this will however take a little more time.

**Comment by jeffamstutz** [comment]
I fixed the tutorials to manage their handles correctly (i.e. ```ospRelease()``` them before the app exits).

Re memory management: We are now shipping ```ospray_sg``` scene graph headers in our installs. I would consider it more of an "alpha" release right now, but many features (handle management being one of them) are much easier with it. While it doesn't replace the underlying API (it simply builds on top of it), we are committed to improving it for users who don't need as much fine-grained control, which I think is true for most use cases of OSPRay.
