### ISSUE TITLE
epsilon values

### ISSUE THREAD

**Issue by carsonbrownlee** [ospray/ospray#20]
We have to custom modify the epsilon values to not get black speckles.  Talking with GregP, this is likely due to our use of instancing not reporting the correct bounding box for the scene.

**Comment by demarle** [comment]
Howdy checking on the status of this one.

**Comment by jeffamstutz** [comment]
I believe this was fixed in ParaView by setting the epsilon based on the scene size? Re-open if further feature requests related to epsilons are on the table.
