### ISSUE TITLE
Extend picking information

### ISSUE THREAD

**Issue by tribal-tec** [ospray/ospray#201]
Right now, OSPPickResult only returns the hit-point in world space, where applications would need to traverse/search their model themselves to find the hit geometry and/or primitive. This information is however also present after the intersection, so I was wondering what about exposing them as well in the pick result.

The problem arises from not having any model/geometry query capabilities in the API to get the actual geometry back from the geomID. A ospGetGeometry(model, geomID) could be a thing, or ospAddGeometry() returns the ID which is to be remembered by the application to correlate the 'internal' object back to the application object. The latter would require 'stable' IDs, which is not the case today (c.f. remove geometry).

I'm wondering what you guys think about this topic and what's your opinion. I would be really glad to leverage from the fact the OSPRay already knows which geometry was hit rather than doing another query in another scenegraph-like structure that is maintained by the application. I know that the ospExampleViewer does that, but you also do more things with the scenegraph.

**Comment by johguenther** [comment]
Totally agreed. `geomID` is internal only, thus the returned information should be the hit `OSPGeometry` (the same which the app got from `ospAddGeometry()`). There are some tricky details why this is not implemented yet:
- handling of instancing 
- MPI mode
- it is an API-breaking change (`OSPPickResult` is larger)

**Comment by jeffamstutz** [comment]
NOTE: we have explicitly stated this is going to be a part of `v2.0`. It's coming! :)

**Comment by tribal-tec** [comment]
Alright, great news, thanks a lot! You have an ETA for the 2.0 release?

**Comment by jeffamstutz** [comment]
Our goal is sometime prior to ISC this year, as we want our ISC/SIGGRAPH demos to rely on `v2.0`.

Over the last several months we prioritized `v1.x` features and bug fixes, so progress on some things (such as this) haven't been worked on. However, now we are committed to `v2.0` without porting off of ISPC (that is still an open question), so deterministic progress is now expected on all these kinds of lingering issues.

**Comment by jeffamstutz** [comment]
Also, we will be merging all of our work into `devel` as we are working, so I can post here when there's something available to try out.

**Comment by jeffamstutz** [comment]
FYI, this is currently implemented on `devel`. `ospPick` now gives you both the `OSPGeometryInstance` (new v2.0 concept) and `primID`.

This may be extended to include `OSPVolumeInstance` as well (those are not yet implemented) in the future...but that has not yet been determined.

**Comment by carsonbrownlee** [comment]
woot woot

**Comment by straaljager** [comment]
woot indeed

**Comment by straaljager** [comment]
> Our goal is sometime prior to ISC this year, as we want our ISC/SIGGRAPH demos to rely on `v2.0`.
> 
> Over the last several months we prioritized `v1.x` features and bug fixes, so progress on some things (such as this) haven't been worked on. However, now we are committed to `v2.0` without porting off of ISPC (that is still an open question), so deterministic progress is now expected on all these kinds of lingering issues.

Hi, when can we expect the release of Ospray 2.0? This would be useful to know for our roadmap. Thanks.

**Comment by jeffamstutz** [comment]
Our best estimate today is Q4. That said, we want to be done with it before Supercomputing (the sooner the better). SIGGRAPH this year took a lot more out of us than we thought, and because we are making API breaking changes we are being more cautious than with other releases (otherwise we would have released by now).

We are keeping `devel` up to date with our latest features that we merge from internal working branches, so you can always see the latest on how the API looks by watching that branch. Our list is getting shorter and shorter, so `devel` is continuing to becoming more stable over time as we settle on the various design changes we've been making.

**Comment by straaljager** [comment]
Thanks Jeff, sounds good.

**Comment by jeffamstutz** [comment]
Extended picking information is released in `v2.0.0-alpha`.

**Comment by straaljager** [comment]
Cool, is there any release info or a feature list of v2.0?

**Comment by straaljager** [comment]
Nevermind, I found this: https://github.com/ospray/ospray/blob/v2.0.0-alpha/CHANGELOG.md
