### ISSUE TITLE
AMR Isosurfaces

### ISSUE THREAD

**Issue by jakob0** [ospray/ospray#203]
Hi.
Just a short question not an issue.
Should it be possible to render isosurfaces of an AMR volume?  I can't get it to work and haven't seen any example, so I'm wondering if it's actually supported.

Thanks
Jakob

**Comment by ingowald** [comment]
Hey, Jacob,

Would you mind sending me an email to ingowald@gmail.com? We're actually currently working on an AMR isosurfaces module here at SCI - and am of course looking for interesting applications / early users / collaborators. Eventually this module will of course go into ospray, but at least right now it's still in a module in a separate repo.

Note we actually do already have some "first light" of the landing gear and cosmos data set, so I think we'd have something up and running with your data rather quickly - but if at all possible I'd like to do this _before_ we merge that code back into ospray proper.

Ingo

**Comment by carsonbrownlee** [comment]
closing issue - AMR isosurfaces are currently only supported through an external module available upon request and will be put into a future ospray release officially.

**Comment by jeffamstutz** [comment]
Let's leave this issue open until the feature is delivered in core OSPRay.

**Comment by johguenther** [comment]
AMR is natively supported in OSPRay (via Open VKL), including isosurfaces.
