### ISSUE TITLE
FR: warn/error on un-recognized command line parameters

### ISSUE THREAD

**Issue by ingowald** [ospray/ospray#206]
The "old" viewers iterated over all command line parameters, and error'ed out for those that weren't recognized, but the new ones simply silently drop those that aren't recognized. This makes is a nightmare for those that don't know all the parameters at heart (or haven't kept track of which ones got renamed, dropped, etc), because if the viewer doesn't do what one would have expected it to do one dones't know if there's some real problem, or if one simply used a wrong or outdated command line arg....

Suggested fix: have those components that parse the args take those off an argument list, and then have the final app complain if some are left that didn't get consumed..

**Comment by carsonbrownlee** [comment]
Looks good to me.  Did you purposely change ","s to ":", as in -sg:sun:direction=0,-1,0 to -sg-sun:direction=0:-1:0?  I suppose that's a style choice, but it seems confusing to use the same separator for children as value indices.
