### ISSUE TITLE
Giving input as x,y,z,r,g,b

### ISSUE THREAD

**Issue by pratikshaandhare** [ospray/ospray#213]
Hi,
Can we give the point cloud file instead of .obj or .stl in bench.cpp of version 1.4?

Thanks and regards,
Pratiksha

**Comment by carsonbrownlee** [comment]
hello,
point data can be imported in xyz format, please see apps/common/sg/importers.  We also have a more generic point loader.  Beyond that, ParaView can load many point file formats. Let me know if this works for your needs and good luck!

**Comment by pratikshaandhare** [comment]
Hi, Thanks a lot!!!

**Comment by swatinair123** [comment]
Hi , but in .xyz file only the points will be loaded . cAn you please tell us how to load the clor(rgb) and if the data cam ne directly sent from the buffer

**Comment by carsonbrownlee** [comment]
in the OSPRay library you can specify a color array for the spheres geometry.  ParaView uses this functionality, and is a good place to use as reference, see VTK/Rendering/OSPRay/vtkOSPRayPolyDataMapperNode.    If you are referring to our exampleViewer, note that it is there just for an example and not really a fully fledged loader, but it can be easily extended.  There is a importer called importPoints which in theory can take in arbitrary point formats, but currently does not recognize someting like xyzrgb.  It does recognize scalars and a colormap however.

**Comment by carsonbrownlee** [comment]
our ply loader is triangles only, I actually didn't even know it supported points!
