### ISSUE TITLE
Viewing the objs in a loop in Gui

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#218]
Hi can any one tell me how can i change the code of ospExampleViewer.cpp so that  i can load the objects in a loop and view them in the GUI. here once it hits ospray::imgui3D::run(); this line the gui runs but the objects doesnt change

**Comment by carsonbrownlee** [comment]
very sorry for the belated reply!  This one seems to have passed our group by for some reason.  If you mean animating through several obj files, we have an example of that using the wooden doll figure in the demos page on ospray.  This will only work with our scene graph viewer, which has become "ospExampleViewer" on the devel branch.
