### ISSUE TITLE
shared_structured_volume cannot render "ushort"

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#224]
Hi All

I recently noticed that my ospray renderer fails to render all "ushort" volumes using `shared_structured_volume`. However it looks fine if I simply switch to `block_bricked_volume` with all the other code unchanged.

You can find the code [here](https://github.com/wilsonCernWq/TinyVolumeRenderer/blob/master/projects/ospray/common/volume.cpp#L182-L189)
 
Can anyone do a double check and see if it is actually a bug ? 

Best 

Qi

**Comment by johguenther** [comment]
Hi Qi,
Ingo and Jeff found and fixed the bug (51f54a90d2b38397904d4b262f236199417d7fa7); could you please verify?

Thanks,
  Johannes

**Comment by wilsonCernWq** [comment]
Hi Johannes

I confirm that the bug is fixed. Thank you.

Qi
