### ISSUE TITLE
volume disappear from some angles using volumeClippingBox 

### ISSUE THREAD

**Issue by MengjiaoH** [ospray/ospray#225]
Hi,
I am trying to use volumeClippingBoxLower and volumeClippingBoxUpper to clip a thin slice from volume. I tried to clip a slice with 2 voxels width, but when moved camera, the slice disappear from some angles. I tested with my own viewer and also ospExampleViewer. It seems like the clip width should be  larger than around 16.
I attached some figures with same volume data clipping width 2 from different camera angles.
Thanks for helping.

-- Mengjiao
![volume_clipping0](https://user-images.githubusercontent.com/21250565/36655506-4da20f18-1a80-11e8-8366-caee479160a0.png)
![volume_clipping1](https://user-images.githubusercontent.com/21250565/36655510-536d9818-1a80-11e8-9ffb-aeea2f0c6eaa.png)

**Comment by carsonbrownlee** [comment]
hello,
try setting the sampling rate to something like 2.0 or even higher.  It is set at less than 1 by default and may be too large and simply stepping right out of the very thin volume.
