### ISSUE TITLE
Application fails to compile with newly exposed "sg" headers

### ISSUE THREAD

**Issue by cpgribble78** [ospray/ospray#227]
Hi,

I'm attempting to make use of the the newly exposed scene graph functionality.  My application includes the top-level header (e.g., #include <ospray/sg/SceneGraph.h>), and I have explicitly added libospray_sg.so to the link line.  (Seems that's not part of OSPRAY_LIBRARIES yet?)  The code fails to compile due to what seems like an incorrect path in the installed 'sg/common/Data.h' header:

  /usr/bin/c++   -DOSPRAY_TASKING_TBB -I/home/cgribble/research/code/isegsim/src -I/home/cgribble/research/code/isegsim/src/apps -I/usr/local/include -I/usr/local/include/ospray -I/usr/local/include/ospray/SDK  -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/driver.dir/driver.cc.o -c /home/cgribble/research/code/isegsim/src/apps/driver/driver.cc
  In file included from /usr/local/include/ospray/sg/SceneGraph.h:30:0,
                   from /home/cgribble/research/code/isegsim/src/apps/driver/driver.cc:27:
  /usr/local/include/ospray/sg/common/Data.h:20:37: fatal error: ospray/common/OSPCommon.h: No such file or directory

For an OSPRay installation and assuming '-I<path_to_install>' (i.e., /usr/local/include' as above), I believe the location of the referenced 'OSPCommon.h' header is 'ospray/SDK/common/', not 'ospray/common/'.  The former is the relative location for an OSPRay installation while the latter is for the internal OSPRay build.

Is this a failure of my application build to include some top-level directory or some other user-error?  Or is this an actual issue?

Thanks,

Christiaan

**Comment by jeffamstutz** [comment]
Hi Christiaan,

Re link issue: we populate the scene graph library in ```${OSPRAY_SG_LIBRARIES}```, similar to ```${OSPRAY_MPI_LIBRARIES}```. This allows applications to link against only the libraries the application desires, instead of putting everything in ```${OSPRAY_LIBRARIES}```.

Re includes: I went ahead and removed the need to include ```OSPCommon.h``` from the scene graph headers. This was an oversight, sorry about that! Please report any other issues you come up with as you are ahead of us on using the scene graph in an install. :)

Both of these issues are definitely artifacts of our aging CMake style. In the future we hope to make everything based on targets, where any application which decides to link a target (e.g. ```ospray::ospray``` or ```ospray::sg```), all link and include dependencies will be correctly resolved. However, that will have to come after ```v1.5.0```.

**Comment by cpgribble78** [comment]
Thanks for clarifying, Jeff---I should've been able to see the ${OSPRAY_SG_LIBRARIES} bit!

I'm getting a similar compile-time error, but now on 'Node.h':
/usr/bin/c++   -DOSPRAY_TASKING_TBB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/home/cgribble/research/code/isegsim/src -I/home/cgribble/research/code/isegsim/src/apps -I/home/cgribble/research/code/isegsim/src/apps/common -I/usr/local/include -I/usr/local/include/ospray -I/usr/local/include/ospray/SDK -isystem /usr/local/include/rckt -isystem /opt/Qt/5.5/gcc_64/include -isystem /opt/Qt/5.5/gcc_64/include/QtCore -isystem /opt/Qt/5.5/gcc_64/./mkspecs/linux-g++ -isystem /opt/Qt/5.5/gcc_64/include/QtGui -isystem /opt/Qt/5.5/gcc_64/include/QtOpenGL -isystem /opt/Qt/5.5/gcc_64/include/QtWidgets  -O3 -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/driver.dir/driver.cc.o -c /home/cgribble/research/code/isegsim/src/apps/driver/driver.cc
In file included from /usr/local/include/ospray/sg/SceneGraph.h:30:0,
                 from /home/cgribble/research/code/isegsim/src/apps/driver/driver.cc:27:
/usr/local/include/ospray/sg/common/Data.h:20:18: fatal error: Node.h: No such file or directory

It appears as if 'Node.h' is not in my install 'sg/common' directory.  Did that get removed?

**Comment by jeffamstutz** [comment]
Bah, sorry about that too...I just pushed a fix for that (header just wasn't installed)...given the road we are on, I'm going to make a little stand-alone version of the OSPRay viewer so I can sanity check this stuff. :)

**Comment by cpgribble78** [comment]
Back in business---thanks!
