### ISSUE TITLE
Embree's rtcSetSceneBuildQuality() function

### ISSUE THREAD

**Issue by straaljager** [ospray/ospray#229]
Hi, first of all great job on Ospray!

We are building a scientific application which requires real-time rebuilding of the BVH per frame. Our scenes typically contain multiple millions of primitives (often user defined primitives).

Embree 3.0 has a new function called rtcSetSceneBuildQuality(), which lets you choose the low quality Morton based BVH builder for very quick BVH updates. Would it be possible to expose this function in OSPRay?

Thanks,

Sam

**Comment by ingowald** [comment]
Hey Sam,

We’re currently working in n ospray 2.0, which, among some other major changes, will switch to Embree 3 as well... so yes, as soon as a beta for that is out you’ll have access to that (and we can make it available to the app as well; that’s easy enough).

Can you tell us a bit more about this app you’re building (via non public email, if you prefer)

Cheers

Ingo

Ps: like the user name :-)

**Comment by straaljager** [comment]
Thank you for the reply Ingo, I guess we will have to impatiently wait for Ospray 2.0 in that case.

Any ETA on when v2.0 might drop? 

In the meantime, is there a way to force Ospray v1.x to use the fast-to-build, low quality BVH?

**Comment by jeffamstutz** [comment]
Right now we are shooting for having some sort of pre-release of ```v2.0``` by ISC.

We don't have the ability to set (at run time) which flags an ```OSPModel``` will use to create the Embree BVH. ```v1.5.0``` just came out, so we can get this added to the next feature release which will be either ```v1.6.0``` or ```v2.0``` (whichever comes first, depending on how quickly ```v2.0``` progress happens).

**Comment by johguenther** [comment]
What you could do just now is to override Embree settings by creating a file `.embree2` is the (home or) application folder with the content

    tri_builder=morton

**Comment by straaljager** [comment]
Thanks for the tips @jeffamstutz @johguenther . Our current use case doesn't use triangles unfortunately, but OSPRay's spheres and cylinders, so I guess the Morton based tri_builder function will not be useful. I suppose we could hack it in though.

**Comment by johguenther** [comment]
Ah, right. Try

    object_builder=dynamic

to select the fast builder for user geometries.

**Comment by ingowald** [comment]
If you mention spheres and cylinders then you might also like our latest 
"tubes"/"neuron" module, with cylinders, spheres, and cone stumps - ie, 
"stream lines" that support varying radius and bifurcations - including 
"CSG" like intersection for transparency.

If you send me an email I can share copy of the latest paper draft (it's 
not public yet, but currently beign finalized and written up)

**Comment by straaljager** [comment]
@johguenther Thanks, we'll try that first thing tomorrow

@ingowald That sounds awesome!
