### ISSUE TITLE
RenderFrame massively slow when unused vertices are in line of sight.

### ISSUE THREAD

**Issue by acdemiralp** [ospray/ospray#231]
Hello,

We utilize 3 buffers: vertices, colors and indices to render streamlines computed on a 128x128x128 grid with one seed per vertex (for testing purposes). Each streamline can reach a maximum of 100 segments, but more often, they terminate early.

Due to efficiency reasons, I preallocate the 3 buffers assuming 128x128x128x100 entries each. I then never modify the sizes of the vertices and the colors, but shrink the indices - removing any invalid indices after streamlines have been computed. Then I pass everything to Ospray.

Now when I launch the application everything is smooth, but the moment I look at (0, 0, 0), which is where my invalid vertices are, renderFrame starts taking multiple seconds instead of the interactive framerates. When I turn my head even slightly, so that (0, 0, 0) is no longer in sight, everything is smooth again.

**Comment by acdemiralp** [comment]
![point](https://user-images.githubusercontent.com/6049621/37035552-331e061e-214d-11e8-8f75-00cb60ec346a.png)

**Comment by acdemiralp** [comment]
Cannot reproduce on an isolated sample. Closing until then.

**Comment by ingowald** [comment]
Hey, Ali,

That almost surely sounds like the "invalid" vertices aren't actually 
invalid, but are still there to some degree. If you have a lot of 
vertices all at the same location the BVH will not be able to separate 
them, so any ray passing through that region will have to intersect them 
all, one after another, which will be expensive...

Ingo
