### ISSUE TITLE
OSPRay 1.4.3 on CentOS 7.4 not building

### ISSUE THREAD

**Issue by TheOtherDave** [ospray/ospray#232]
We having trouble building OSPRay 1.4.3 on CentOS 7.4.

There seems to be two main problems:

1) The MD5 files needed by everything other than the benchmarking suite are missing (and even those are pretty tricky to find… the build instructions don’t say anything about them, and google is strangely unhelpful on the matter). I eventually found them at http://sdvis.org/ospray/download/baseline/test-data/MD5/ and http://sdvis.org/ospray/download/baseline/benchmark-data/MD5/, but the test-data files don’t help. Are those even the correct files?

2) ISPC (both 1.9.2 and 1.9.3dev) is having trouble compiling some of the files when invoked via make, but compiles them fine if done manually.

Does anyone have any ideas about either issue? Here's the build commands:
source /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/iccvars.sh intel64
source /opt/intel/parallel_studio_xe_2018.1.038/bin/psxevars.sh
export prefix=/usr/local
export CC=icc
export CXX=icpc
flags="-O2 -march=native"
export cflags_nostd="${flags}"
export cxxflags_nostd="${flags}"
export cstd="-std=c11"
export cxxstd="-std=c++14"
export CFLAGS="${cflags_nostd} ${cstd}"
export CXXFLAGS="${cxxflags_nostd} ${cxxstd}"

export CPATH="/opt/intel/impi/2018.1.163/include64:${CPATH}"
export LDFLAGS="${LDFLAGS} -pthread -ldl -lrt -lm"

cmake .. \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DISPC_EXECUTABLE=/opt/ispc-v1.9.2-linux/ispc \
        -DOSPRAY_MODULE_MPI=ON \
        -DOSPRAY_TASKING_SYSTEM=TBB \
        -DOSPRAY_INSTALL_DEPENDENCIES=ON \                                                                                     
        -DOSPRAY_BUILD_ISA=ALL \                                                                                               
        -DOSPRAY_ENABLE_APPS=ON \                                                                                              
        -DTBB_ROOT=/opt/intel/tbb \                                                                                            
        -DTBB_INCLUDE_DIR=/opt/intel/tbb/include \                                                                             
        -DTBB_LIBRARIES=/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64_lin \                              
        -DTBB_COMPILER=gcc4.7 \                                                                                                
        -DOSPRAY_MODULE_RAY_MARCHER=ON \                                                                                       
        -DOSPRAY_APPS_BENCHMARK=ON \                                                                                           
        -DOSPRAY_APPS_EXAMPLEVIEWER=OFF \                                                                                      
        -DOSPRAY_APPS_PARAVIEW_TFN_CVT=OFF \                                                                                   
        -DOPENVDB_LIBRARY=/usr/local/lib/libopenvdb.so \                                                                       
        -DOPENVDB_ENABLE_ABI_3_COMPATIBLE=ON \                                                                                 
        -DBLOSC_USE_STATIC_LIBS=OFF \                                                                                          
        -DOSPRAY_ENABLE_TESTING=OFF                                                                                             
make -j100 ospray_common
make -j100 ospray_bench_data
make -j100 ospray_test_suite

It's that last line that builds ospray_test_suite that fails. Here's the output:
Intel(R) Parallel Studio XE 2018 Update 1 for Linux*
Copyright (C) 2009-2017 Intel Corporation. All rights reserved.
-- The C compiler identification is Intel 18.0.1.20171018
-- The CXX compiler identification is Intel 18.0.1.20171018
-- Check for working C compiler: /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64/icc
-- Check for working C compiler: /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64/icpc
-- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Found TBB: /opt/intel/tbb/include  
-- Found Embree v2.17.2: /usr/local/lib64/libembree.so.2.17.2
-- OSPRay SSE4 ISA target enabled.
-- OSPRay AVX ISA target enabled.
-- OSPRay AVX2 ISA target enabled.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found OpenEXR: /usr/local/lib64/libHalf.so  
-- Found TBB: /opt/intel/tbb/include (found version "2018.0") 
-- Found OpenVDB: /usr/local/include  
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/local/lib64/libhdf5.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.1") found components:  C HL 
-- Found MPI_C: /opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/intel64/lib/libmpifort.so (found version "3.1") 
-- Found MPI_CXX: /opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/intel64/lib/libmpicxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BLOSC_USE_STATIC_LIBS
    OPENVDB_ENABLE_ABI_3_COMPATIBLE

-- Build files have been written to: /path/to/source/tree/ospray/build
Scanning dependencies of target ospray_common
[  0%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/common.cpp.o
[  0%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/FileName.cpp.o
[  0%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/library.cpp.o
[ 25%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/sysinfo.cpp.o
[ 25%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/malloc.cpp.o
[ 50%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/thread.cpp.o
[ 75%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/array3D/Array3D.cpp.o
[ 75%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/networking/BufferedDataStreaming.cpp.o
[ 75%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/vec.cpp.o
[ 75%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/tasking/detail/tasking_system_handle.cpp.o
[ 75%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/utility/PseudoURL.cpp.o
[ 75%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/networking/Socket.cpp.o
[100%] Building CXX object components/ospcommon/CMakeFiles/ospray_common.dir/tasking/detail/TaskSys.cpp.o
[100%] Linking CXX shared library ../../libospray_common.so
icpc: warning #10237: -lcilkrts linked in dynamically, static library not available
[100%] Built target ospray_common
Scanning dependencies of target ospray_bench_data
[  0%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/stats.csv
[  0%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_heptane2_scivis.ppm
[  0%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_fiu1_scivis.ppm
[  0%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_heptane1_scivis.ppm
[ 25%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_fiu2_scivis.ppm
[ 50%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_magnetic3_scivis.ppm
[ 75%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_llnl_iso1_scivis.ppm
[ 75%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_llnl_iso2_scivis.ppm
[ 75%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_magnetic2_scivis.ppm
[ 75%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_magnetic1_scivis.ppm
[ 75%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_san_miguel1_scivis.ppm
[ 75%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_sibenik1_scivis.ppm
[100%] Generating /path/to/source/tree/ospray/build/benchmarks/baseline/test_sponza1_scivis.ppm
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/a6f8cb2bb28a50195fcf211ac53aff5c"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/8242cac555477107b83868bc648b74eb"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/78d73a567dfdda8978118aa65324008b"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/a84738a97d6ee2e341b352cc990dadff"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/0e1943eda090b1acd31420d6ec0aaf3d"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/7cf587d5062e4cc18ba29ededd92edc0"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/3d935bd1a25b0e97334f995d19981eb8"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/a84738a97d6ee2e341b352cc990dadff"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/e2c4962cbb3978edcd28ab989ce7bf6f"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/f3f3b43a038c4d3f1b5aafd99ee8284e"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/2d31c5db73ba9d927bebe43f407356af"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/2a7ae5a95396cc350623966fee451140"
-- Found object: "/path/to/source/tree/ospray/build/ExternalData/Objects/MD5/c2cf3fbb7cc3c990211388cde0456077"
[100%] Built target ospray_bench_data
Scanning dependencies of target gtest
[  8%] Built target ospray_common
[ 10%] Building CXX object built_components/ospcommon/testing/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 10%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_common/OSPCommon.dev.o
[ 10%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/amr/method_octant.dev.o
[ 10%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_fb/FrameBuffer.dev.o
[ 12%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_common/Model.dev.o
[ 12%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_fb/LocalFB.dev.o
[ 14%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_camera/PerspectiveCamera.dev.o
[ 14%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_camera/Camera.dev.o
[ 14%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/Geometry.dev.o
[ 14%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_camera/OrthographicCamera.dev.o
[ 16%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_camera/PanoramicCamera.dev.o
[ 16%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/TriangleMesh.dev.o
[ 18%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/StreamLines.dev.o
[ 18%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/Instance.dev.o
[ 18%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/Spheres.dev.o
[ 20%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/Cylinders.dev.o
[ 20%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/Slices.dev.o
[ 20%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_geometry/Isosurfaces.dev.o
[ 22%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/Light.dev.o
[ 22%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/AmbientLight.dev.o
[ 22%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/DirectionalLight.dev.o
[ 22%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/PointLight.dev.o
[ 24%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/SpotLight.dev.o
[ 24%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/QuadLight.dev.o
[ 24%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_lights/HDRILight.dev.o
[ 26%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_math/box.dev.o
[ 26%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_math/Distribution1D.dev.o
[ 26%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_math/Distribution2D.dev.o
[ 28%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_math/spectrum.dev.o
[ 30%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/raycast/RaycastRenderer.dev.o
[ 30%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/util.dev.o
[ 30%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/Renderer.dev.o
[ 30%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/simpleAO/SimpleAO.dev.o
[ 30%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/simpleAO/SimpleAOMaterial.dev.o
[ 32%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/scivis/lightAlpha.dev.o
[ 32%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/scivis/volumeIntegration.dev.o
[ 34%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/scivis/SciVisRenderer.dev.o
[ 34%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/scivis/surfaceShading.dev.o
[ 34%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/scivis/SciVisMaterial.dev.o
[ 34%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/PathTracer.dev.o
[ 36%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Material.dev.o
[ 36%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/GeometryLight.dev.o
[ 36%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/OBJ.dev.o
[ 36%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Velvet.dev.o
[ 38%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Metal.dev.o
[ 38%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Alloy.dev.o
[ 38%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/ThinGlass.dev.o
[ 38%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/MetallicPaint.dev.o
[ 40%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Glass.dev.o
[ 42%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Plastic.dev.o
[ 42%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Luminous.dev.o
[ 42%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Mix.dev.o
[ 42%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_texture/Texture2D.dev.o
[ 44%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_transferFunction/LinearTransferFunction.dev.o
[ 44%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/Volume.dev.o
[ 46%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/structured/GridAccelerator.dev.o
[ 46%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/structured/StructuredVolume.dev.o
[ 48%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/structured/bricked/GhostBlockBrickedVolume.dev.o
[ 48%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_transferFunction/TransferFunction.dev.o
[ 48%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/structured/bricked/BlockBrickedVolume.dev.o
[ 48%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/unstructured/MinMaxBVH2.dev.o
[ 48%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/structured/shared/SharedStructuredVolume.dev.o
[ 50%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/amr/AMRVolume.dev.o
[ 50%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/amr/DualCell.dev.o
[ 50%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/unstructured/tetrahedral/TetrahedralVolume.dev.o
[ 52%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/amr/method_current.dev.o
[ 52%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/amr/method_finest.dev.o
[ 52%] Building ISPC object /path/to/source/tree/ospray/build/ospray/local_volume/amr/CellRef.dev.o
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_common/OSPCommon.dev.idep
make[3]: *** [ospray/local_common/OSPCommon.dev_avx2.o] Error 1
make[3]: *** Deleting file `ospray/local_common/OSPCommon.dev_avx2.o'
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [ospray/local_common/OSPCommon.dev_sse4.o] Error 1
make[3]: *** Deleting file `ospray/local_common/OSPCommon.dev_sse4.o'
make[3]: *** [ospray/local_common/OSPCommon.dev_avx.o] Error 1
make[3]: *** Deleting file `ospray/local_common/OSPCommon.dev_avx.o'
make[3]: *** [ospray/OSPCommon_ispc.h] Error 1
make[3]: *** Deleting file `ospray/OSPCommon_ispc.h'
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_math/Distribution1D.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_math/spectrum.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_fb/FrameBuffer.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_transferFunction/TransferFunction.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_math/Distribution2D.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_math/box.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/simpleAO/SimpleAOMaterial.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/Light.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_camera/OrthographicCamera.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/util.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/QuadLight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/amr/method_current.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/DirectionalLight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/SpotLight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/scivis/SciVisMaterial.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/Geometry.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Material.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_camera/Camera.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/AmbientLight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_camera/PanoramicCamera.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_common/Model.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/Slices.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_camera/PerspectiveCamera.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/Isosurfaces.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/structured/StructuredVolume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/unstructured/MinMaxBVH2.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/unstructured/tetrahedral/TetrahedralVolume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/GeometryLight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/Volume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/scivis/lightAlpha.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/amr/AMRVolume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Luminous.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/Instance.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/HDRILight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/amr/method_finest.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/amr/CellRef.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_transferFunction/LinearTransferFunction.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/Renderer.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/Spheres.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_lights/PointLight.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/structured/GridAccelerator.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/Cylinders.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Velvet.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Mix.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/simpleAO/SimpleAO.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Glass.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/scivis/SciVisRenderer.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Metal.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Alloy.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/amr/DualCell.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/StreamLines.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/scivis/volumeIntegration.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/ThinGlass.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/scivis/surfaceShading.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_fb/LocalFB.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/MetallicPaint.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/structured/bricked/BlockBrickedVolume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/OBJ.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/materials/Plastic.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/structured/shared/SharedStructuredVolume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/raycast/RaycastRenderer.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/amr/method_octant.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_geometry/TriangleMesh.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_volume/structured/bricked/GhostBlockBrickedVolume.dev.idep
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_render/pathtracer/PathTracer.dev.idep
[ 52%] Linking CXX static library ../../../../libgtest.a
[ 52%] Built target gtest
Scanning dependencies of target gtest_main
[ 52%] Building CXX object built_components/ospcommon/testing/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 54%] Linking CXX static library ../../../../libgtest_main.a
[ 54%] Built target gtest_main
writing dependencies to file /path/to/source/tree/ospray/build/ospray/local_texture/Texture2D.dev.idep
make[2]: *** [ospray/CMakeFiles/ospray.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/ospray_test_suite.dir/rule] Error 2
make: *** [ospray_test_suite] Error 2

**Comment by jeffamstutz** [comment]
Hi,

Thanks for the detailed report...I'm impressed you are trying to run our new run-time test suite, we haven't even advertised them yet! :)

For our upcoming ```v1.5.0``` release, we have re-targeted our run-time tests to our public sdvis.org web server (as you found links to). Back in the ```v1.4.x``` releases, those paths were setup as mount points in Docker containers we use for CI, so they are nonsense when invoked outside of our CI containers.

Could you try checking out the ```release-1.5.x``` branch to see if your build script/environment work? This issue may already be fixed: I just tried your cmake/make steps on my home machine, which worked for ```release-1.5.x``` but not ```v1.4.3```.

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
I'm also not sure if the ISPC issue is also related, but please let me know if that changed too...we may not have suppored ISPC ```v1.9.2``` yet back in ```v1.4.x```.

**Comment by jeffamstutz** [comment]
And FYI, the ```v1.5.0``` release looks like it will happen tomorrow, so if it is already fixed upstream it should be in imminently in an official release.

**Comment by TheOtherDave** [comment]
Oops, in the excitement of getting things working, I forgot to come back and share what the problem was.

If I remove the "-DISPC_EXECUTABLE=/opt/ispc-v1.9.2-linux/ispc" flag and let the system find ISPC on its own, it works with `make -j100' and `make test'. I can't figure out why that'd make a difference, though, since it then uses `/usr/bin/ispc', which is just a sym link to `/opt/ispc-v1.9.2-linux/ispc'... it's the same executable either way. Maybe some subtle pathing issue in make or cmake?

Also, FWIW, I can confirm that at least on my system, OSPRay 1.4.3 compiles with both ISPC v1.9.2 and v1.9.3dev (which is the latest branch in ISPC's GitHub repo, as of a few days ago).

**Comment by jeffamstutz** [comment]
Hmmm, that is indeed very strange. We simply use ```${ISPC_EXECUTABLE}``` to invoke ISPC, so I'm also not sure what else could be going on...perhaps just a quirk with CentOS 7 and the version of CMake you are using?

Regardless, it looks like you are now able to compile (and with ```v1.5.0``` now too?). Please re-open if there remain barriers for you.

**Comment by TheOtherDave** [comment]
Probably... CentOS is full of those (or, more likely, I just don’t know Linux & the build system(s) well enough to tell the difference).

I tried OSPRay 1.5.0 once, but it was before I figured out what was causing the problem. Once we get everything up & running, I’ll come back and start versioning everything.
