### ISSUE TITLE
FindTBB.cmake bad hints 

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#233]
Hi All

Recently I found that in `FindTBB.cmake` file there is a hint for TBB library

```cmake
SET(TBB_HINTS HINTS ${TBB_ROOT}/lib/intel64/gcc4.4 ${TBB_ROOT}/lib ${TBB_ROOT}/lib64 PATHS /usr/libx86_64-linux-gnu/)
```

However on some machines for example mine, there are three versions of TBB in the folder because I am using the tbb comes with intel parallel studio 18:

```
qwu@lagodelcielo [intel64]: ls
gcc4.1  gcc4.4  gcc4.7
```

Because my system is relatively new, the gcc4.7 is selected automatically, which makes cmake produces error like 
```
CMake Warning at components/ospcommon/cmake/macros.cmake:404 (ADD_EXECUTABLE):
  Cannot generate a safe runtime search path for target ospDistribViewerDemo
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libtbb.so] in /opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/intel64/gcc4.7 may be hidden by files in:
      /opt/intel/tbb/lib/intel64/gcc4.4
```

I believe there are better ways to hint TBB or at least searching system parameters first?

Thank you

Qi

**Comment by jeffamstutz** [comment]
Hi Qi,

I went ahead and added gcc4.7 as a hit for newer versions of TBB for the ```v1.5.0``` release, though I'm not sure if that will fix your issue. Could you update and give it a try again? I'm not sure of another solution right now, so I may have to go educate myself on what the "right" thing CMake wants here.

Jeff

**Comment by wilsonCernWq** [comment]
Hi Jeff

That fixed my problem, but I am not sure that's a fix for everybody (for example if someone has intel parallel studio 18 but selected gcc4.4 version, then its a problem again). However I think that's good enough for now ! Thank you !

Best

QI
