### ISSUE TITLE
Unstructured volume doc issues

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#235]
Under Unstructured Volumes on https://www.ospray.org/documentation.html it currently says

> Unstructured volumes can contain tetrahedral or hexahedral cell types, and are defined by three arrays: vertices, corresponding field values, and eight indices per cell (first four are -1 for tetrahedral cells). An **unstructred** volume type is created by passing the type string “unstructured_volume” to ospNewVolume.
> ...
> vec4i[] | **intices** | data array of tetrahedra indices (into vertices and field)

As the type of indices if vec4i does that mean always using two entries per cell with the first being 4x -1 for a tetrahedral cell? 

(In bold some spelling mistakes btw)

And is the hexahedral support usable atm? I'm having no luck yet in getting any visible output for a 512^3 volume. Is there an example somewhere?

**Comment by timrowley** [comment]
Correct, the current implementation uses 2*vec4i for both data types, with a 4x-1 in the first position indicating a tetrahedral cell type.  If we get feedback about memory usage a different internal representation can be considered.

Finding hexahedral examples for development wasn’t very fruitful- if you know of examples to test with I’d be interested in seeing them.  Current implementation works on the hexa.vtk file from the vtk test suite, and with testcases I generated locally.

Thanks for pointing out the typos.
