### ISSUE TITLE
Depth buffer pixel format

### ISSUE THREAD

**Issue by samcaulfield** [ospray/ospray#238]
Hi, I'm trying to visualise the depth buffer. I can't find any information about the depth buffer pixel format in the documentation other than it represents the "euclidean distance to the camera (not to the image plane)".

What is the pixel format of the depth buffer (bits per pixel etc.). I'm assuming 32-bit floating point given that the default clear value is INF. Is the depth encoding non-linear?

Thanks

**Comment by johguenther** [comment]
The depth is indeed in 32bit single precision float. It is essential the hit distance of the camera rays, thus the depth is linear.

**Comment by samcaulfield** [comment]
Thanks for the clarification
