### ISSUE TITLE
ospParticleViewer Question

### ISSUE THREAD

**Issue by vreyes23** [ospray/OSPRay#24]
In regards to the ospParticle viewer. is the Model class creating a model for each atom that is being created or is it just one model that has all the atoms or particles within it? We are trying to see if there is a way to manipulate the radius of particles independently of others that way we have variety with them. Thank you for any assistance.

Victor Reyes
Vareyes@miners.utep.edu

**Comment by johguenther** [comment]
While OSPRay supports an individual radius for each sphere the `ospParticleViewer` does not use this feature, i.e. its Model class currently only holds one radius for all atoms.

Depending on your use-case you could extend the particle viewer in different ways:
- If you just want a few different sizes (e.g. small, medium and large atoms) you can use three models, each having a different radius.
- If many atoms have different sizes you can use the `offset_radius` parameter of the 'spheres' geometry, which specifies the offset (in bytes) of each sphere's 'float radius' value within the data array `spheres`.

**Comment by ingowald** [comment]
Implemented in latest version of ospray; particle viewer can now specify radius per atom type, and ospray sphere geometry is now supporting this during rendering.
