### ISSUE TITLE
Docs feedback

### ISSUE THREAD

**Issue by samcaulfield** [ospray/ospray#240]
Hi,

I've been using OSPRay in a project for generating synthetic data sets for computer vision applications. Looks good so far. I have some feedback on the [docs](http://www.sdvis.org/ospray/download/OSPRay_readme_devel.pdf). Out of curiosity, are these docs publicly version controlled? I'd submit a PR for some of this stuff if I knew it was.

Page 26 - It doesn't state whether index buffers are required for triangle meshes. Some renderers don't require them. Also the description has an asterisk but I cannot find a corresponding note.

Page 29 - It doesn't state explicitly whether the scivis renderer supports materials other than OBJMaterial. My project crashes when using other materials with scivis so I assume not, unless I've made a mistake.

Page 45 - Pixel format of the depth buffer isn't specified. I've since learned that it's 32F. It would have been nice to have this in the docs since i'm using the depth buffer as synthetic depth sensor images.

Thanks

**Comment by johguenther** [comment]
Hi,
thanks for the feedback. The documentation source files have been in a separate, private repository, but we are currently moving them into the main OSPRay repo.

I included your suggestions. What materials are supported by the renderers is mentioned in the material description of each material.

Cheers,
  Johannes

**Comment by samcaulfield** [comment]
The diff looks good, much clearer now. Thanks for the clarifications. As for the materials, I assumed some of them (Metal etc.) would work with scivis since it wasn't explicitly stated otherwise. I noticed that the renderer would crash once pixels from an object with an unsupported material came on-screen. It would be nice if perhaps the material was ignored instead. Not a big deal though.

Thanks again!

**Comment by samcaulfield** [comment]
Whoops, just noticed the docs say "The call returns NULL if the material type is not known by the renderer type, or else an OSPMaterial handle to the created material". My bad!
