### ISSUE TITLE
refcount of model in v1.5.0

### ISSUE THREAD

**Issue by kobers** [ospray/ospray#242]
Hi, 

using ospray v1.5.0, I get the following issue:
when i create a model (with refcount 1) and set it in the renderer via 
`ospSetObject(renderer, "world", model);`
`ospSetObject(renderer, "model", model);`
the refcount of the model is increased to 3. I would expect that when the renderer is destroyed(via ospRelease), the refcount of the model is decreased to 1 again (as working in v1.4.3).
The refcount stays at 3 though, and even when calling ospRelease 3 times to destroy the model, not as much memory as in v1.4.3 is released.

Best, Stefan

**Comment by jeffamstutz** [comment]
Hi Stefan,

Sorry for such a delayed response: yes we see this bug too. We recently made some changes to how we build our documentation (doc sources are now in the main repo), so we may not have a fix for this in an "official" release until ```v1.6.0```. However, I can fix this ASAP and post it to ```devel```, which is our upstream branch for whatever the next minor release would be.

I'll report back here once a fix is implemented and pushed....thank you for letting us know!

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
Sorry for not mentioning this earlier, but I implemented fixes for this in ```devel``` a while back, and now it should be in the latest ```v1.6.0``` release.

Please re-open if you still find issues in your application...thanks!
