### ISSUE TITLE
#osp:PT: out of memory for shadingContext allocation!

### ISSUE THREAD

**Issue by geoxpeed** [ospray/ospray#243]
I've changed pc, the same scene same parameter with old pc it's all ok, in the new pc after 50 frames ospray show three line:
#osp:PT: out of memory for shadingContext allocation!
#osp:PT: out of memory for shadingContext allocation!
#osp:PT: out of memory for shadingContext allocation!
and after 55 frames another time show those three line error and then contiunue.

ospRay version 1.4.3.0
embree 2.17.0

New pc:
mac pro with bootcamp and win 10
Processor intel xeon W-2140B 8-core 3.2 GHz with turbo boost 4.2 GHz
32gb Ram ECC 2666MHz
1TB SSD Disk
Radeon Pro Vega 56 8Gb Ram HBM2

**Comment by johguenther** [comment]
Hmm, that's odd. Maybe your new PC now supports 8-wide SIMD (AVX), and thus the pathtracer materials need more memory. Still, the allocated memory scales with SIMD width and consequently we haven't seen this error a long time.

Anyway, could you try to increase the allocated memory by 2x in `ospray/render/pathtracer/bsdfs/ShadingContext.ih` (define `SHADINGCONTEXT_SIZE`) and see if the error is still there?

**Comment by geoxpeed** [comment]
Problem solved, thank you very much.
