### ISSUE TITLE
Ospray 2.0

### ISSUE THREAD

**Issue by straaljager** [ospray/ospray#244]
Hi, we're currently building our own client-server based API on top of Ospray for web based visualisation. Some of the API design decisions require a lot of code refactoring (and work). Our concern is that a large part of our API work may become obsolete once Ospray 2.0 is released. Would be helpful if we would know a rough ETA on when Ospray 2.0 is coming (if it's not within the next 2-3 months, we will continue on our work)

**Comment by jeffamstutz** [comment]
Howdy,

This sounds like a cool project! We are targeting an "alpha" preview of ```v2.0``` for ISC in June and a more solid "beta" (or release?) around SIGGRAPH in early August.

The biggest change for ```v2.0``` is that we are no longer using ISPC for vectorization, so we have lots of work to do in porting existing features to a pure C++ solution. Furthermore, we are also evaluating a stream-based approach instead of pure packets, which is another significant axis of change.

Regardless of either of the above changes, the public API will remain almost entirely the same: we are changing almost everything _underneath_ the API, but we don't have any major changes planned for the API applications will end up using. So far in our development, only the following are different:

- instances can be nested in other instances
- ```ospNewTexture2D()``` will now be ```ospNewTexture("texture2D"), which opens the door for other texture types/implementations in the future

...with the following being ideas we will likely implement:

- volumes can be properly instanced (and nested too, just like geometries)
- a top-level scene container (e.g. ```OSPScene```?) for ```ospRenderFrame()```, which guarentees to hold the entire scene, instead of ```OSPModel``` being a bit ambiguous

There may be other tweaks we make, but fundamentally we want to use as much of the ```v1.x``` API as possible. In fact, the process we are using to develop ```v2.0``` is to implement an ```OSPDevice``` which is completely independent of the ISPC device (i.e. ```v.1.x``` implementation), which helps us from deviating too much at the API level.

If you have any deeper concerns regarding ```v2.0```, please let us know! :)

Cheers,
Jeff

P.S. - if you are able and willing, please let us know how your web-based app goes with OSPRay!

**Comment by tomvierjahn** [comment]
Just curious, Jeff,
why are you abandoning ISPC for vectorization?

Cheers,
Tom

**Comment by jeffamstutz** [comment]
Hi Tom,

The decision to move off of ISPC is mostly driven by how few users are comfortable with it. OSPRay is more than just an API: it is general ray tracing infrastructure built to be extended. Connecting ISPC with C++ is a pain point which will not (AFAIK) be addressed in ISPC's future (e.g. parsing C++ headers by the ISPC compiler). This makes it rare for users to even try to extend OSPRay with new object types, let alone be successful in the endeavor. We hope that by using a well constructed C++ environment for writing renderers, we will see increased desire to extend OSPRay in new and interesting ways.

Part of this decision is also motivated by timing. OSPRay ```v2.0``` is our opportunity to move from a purely packet-based design to a ray-streaming design. Our goal is to have infrastructure for implementing AoS, AoSoA, and SoA ray streams, where the ray data layout choice would be driven by the rendering algorithm and comfort of the programmer. This is a much more achievable goal with a feature rich language in C++....having templates available are a BIG win for this.

Lastly, we believe that with a pure C++ approach, using a general SIMD abstraction to get similar syntax to ISPC (we are using [tsimd](https://github.com/ospray/tsimd) for that), that we will have more tight control over code generation. While we are first fleshing out features, later we can fine-tune certain kernels for performance, where ISPC is mostly just a "black box". This is more of an opinion than a measured fact, but I personally think that we can do better than ISPC in certain areas. We are moving to the same strategy that Embree uses for vectorizing its kernels (i.e. a C++ SIMD library), so there's some evidence that you can get VERY tight performing code out of this technique without sacrificing too much maintainability.

Hopefully that helps!

Jeff

**Comment by straaljager** [comment]
@jeffamstutz Thank you very much, this is very helpful info for our short term planning. Looks like we can keep building on top of the current API.

Also looking forward to the C++ vectorization.

Sam

**Comment by tomvierjahn** [comment]
Very helpful, indeed. Thanks Jeff.

**Comment by KyleFromKitware** [comment]
> The biggest change for `v2.0` is that we are no longer using ISPC for vectorization

@jeffamstutz Does this mean that Embree will not need to be built with ISPC support either (`-DEMBREE_ISPC_SUPPORT`)? I would like to create Debian packages for OSPRay and Embree, and I need to know if I will also need to create a package for ISPC so these packages can be built.

**Comment by jeffamstutz** [comment]
That should be correct: for the sake of packaging OSPRay and Embree, OSPRay ```v2.0``` should no longer depend on Embree's ISPC API altogether.

**Comment by KyleFromKitware** [comment]
Excellent! That will make things a lot easier. Thank you Jeff!

**Comment by oscarbg** [comment]
any news on Ospray 2.0? some alpha release at Siggraph?

**Comment by oscarbg** [comment]
Hi,
thanks for informative response..
No specifics and no pressure for the ISPC move off:
only wanted to evaluate how dropping ISPC changed the complexity from the builds side of things and also to see if performance was more or less the same..

will keep and eye on Siggraph as a non atendee for press releases, presentation slides, etc..
