### ISSUE TITLE
Feature request: API fct to query OSPRay version during runtime

### ISSUE THREAD

**Issue by ingowald** [ospray/OSPRay#25]
Would be nice to be able to query ospray version during runtime; something like
char *ospGetVersionString();
that returns "release-v0.8.2-osx", "devel-<dateortag>-linux" or something like that.

**Comment by ingowald** [comment]
Similarly useful to have compile-time constants.

**Comment by jeffamstutz** [comment]
Issue closed as this is implemented in the installed 'version.h' file.
