### ISSUE TITLE
mac osx sierra, dyld library not loaded

### ISSUE THREAD

**Issue by mikowiec** [ospray/ospray#251]
Precondition:
- mac osx Sierra 10.12.6
- ospray installed to custom folder `ospray`
- libs installed to `ospray/opt/local/lib`
- folder `/opt` is absent on Sierra
- ospExampleViewer should load demo scene "Sponza" and command line parameters

issue: 
"dyld: Library not loaded: /opt/local/lib/libospray_imgui3d_sg.0.dylib"
"  Referenced from ospExampleViewer"

**Comment by jeffamstutz** [comment]
Hi,

I'm not able to reproduce this on my end with either the pre-built binary packages nor a build/install of my own from source. Two questions that may help me reproduce:

- Are you building from source or using binary packages?
- Which version of OSPRay are you trying to run?

Cheers,
Jeff

**Comment by mikowiec** [comment]
OSPRay v1.5.0, binary installation `ospray-1.5.0.x86_64.dmg `

**Comment by jeffamstutz** [comment]
We just re-enabled our dmg binary releases, please let us know (either here or in a new issue) if you find any issues. They seem to work for us!
