### ISSUE TITLE
Embree3.2.1

### ISSUE THREAD

**Issue by csverma610** [ospray/ospray#254]
Hello,

I am unable to use Embree3.2.1 with OSPRay latest version. The cmake gives message
for embree_DIR when Embree3.2.1 is used. Also, there are some filters in Embree2.* which
are not available in Embree3.2.1.

Is there a way to use the latest versions of both the software?

Thanks

**Comment by jeffamstutz** [comment]
Hi,

Could you provide some context of your build environment? Are you using an Embree binary release or building it yourself? (compiler/OS/cmake versions may be useful too)

Also, what do you mean by filters in Embree v2.x?

FWIW, I am able to build OSPRay v1.6.0 using the latest version of Embree (v3.2.0 at the moment) on multiple platforms, using both hand compiled and binary tar releases of Embree.

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
Great! As always, let us know if you have any other issues.

**Comment by csverma610** [comment]
Hello Jeff,

I do not know if it is a relevant question here.  Does OSPRay /Embree
support Sparse Voxels similar to GigaVoxels software?

csv


On Wed, May 16, 2018 at 9:34 AM, Jefferson Amstutz <notifications@github.com

**Comment by johguenther** [comment]
Ah, almost forgot: and with the above volumes, OSPRay supports shadows and AO, something which GigaVoxels cannot do.

**Comment by johguenther** [comment]
There is only slight overhead, the main memory footprint is just the volume data itself (which can be shared between the application and OSPRay). Thus, 2k<sup>3</sup> float (or a 3k<sup>3</sup> byte) volume should be possible to render with 64GB RAM, with enough margin.

**Comment by ingowald** [comment]
Could you give us some more info on what you are trying to achieve? That’ll make it easier to give the (hopefully) right answers :-)
