### ISSUE TITLE
Viability of adding a new Structured Volume type

### ISSUE THREAD

**Issue by JaapSuter** [ospray/ospray#261]
Hi,

I'm trying to visualize a large volume stored in a cylindrical coordinate system (its cartesian shape is an annulus, with inner and outer radius, but its raw voxels are stored with 256 voxels radially, 384 voxels circumferentially, and anywhere from 1024 up to 60.000 slices axially).

We have our own in-house volume renderer that can draw this kind of dataset. Here's an example:

![3d-example](https://user-images.githubusercontent.com/44677/42840219-f4682db0-89ba-11e8-8be0-063e520a5988.png)

To deal with the large amount of slices (up 60.000 in our current datasets) we have your typical streaming LOD/mipmap/clipmap system that loads whatever is nearest to the camera. That's not really what this question is about.

Mine is more about the cylindrical coordinate system. Here's an example slice in Cartesian space (image downsized):

![2d-slice](https://user-images.githubusercontent.com/44677/42842384-ed100a72-89c1-11e8-9eb6-900d82ee6999.png)

All the black pixels in this image (the inner circle, and the four corners) are all black (zero). That's why we store the dataset in its cylindrical raw form, where a slice might looks like this (not the same slice as the one above):

![23638382739459](https://user-images.githubusercontent.com/44677/42842617-896ff68e-89c2-11e8-8b82-ddf80ee59b25.jpg)

All raymarching happens in cartesian space, and only as the very last step, when we're trying to get the scalar value of a voxel in the innermost loop inside a pixel shader, do we convert to a polar coordinate-system to sample the texture. This works great; we get to keep the size of our dataset on disk and in GPU memory significantly smaller, and we can thus load more of it at once. Furthermore, any raymarch steps that step through the zero voxels can very quickly skip this empty space (well before sampling the texture).

Strictly speaking the texture sampler's bilinear interpolation is no longer 'mathematically correct', since neighbours aren't perpendicular like they are in Cartesian space, but the results are visually close enough. We do some extra math for our gradient approximation using central differences to handle the Cartesian/Polar issue.

The reason we're looking at OSPray is because we'd like to bring some "physically based rendering" qualities to our visualizations -- for some definition of "physically based" anyway, considering we're drawing ultrasound datasets captured deep underground where there is no light, heh 😄.

We've done some test renders with "scan-converted" subsets of our data (i.e., converted from cylindrical to cartesian space, with all the empty space taking up valuable memory), and the results are promising.

These two images were actually taken using Mitsuba and Exposure, but OSPray got similar ones (sorry I don't have any at hand), and we feel OSPray is the most malleable open-source project of those three:

![image 3](https://user-images.githubusercontent.com/44677/42843354-b0d123cc-89c4-11e8-9727-7f90ca569e8f.png)
![hetvol](https://user-images.githubusercontent.com/44677/42843355-b1cbe5e6-89c4-11e8-8e9d-23e8e7289462.png)

Anyway, all that brings me to my final question (sorry for the long winded introduction).

I'm considering to add a new type of structured volume to OSPray (and obviously contribute it back to the project if the implementation ends up good enough for your taste) that would do its sampling in a cylindrical space. It may also handle the streaming aspects for large number of slices, although that's not my initial priority.

Would you say that is:

- A dumb idea, practically impossible, given the existing OSPray code?
- Totally doable, just copy-paste the existing structured volume code, add some extra parameters that specify how the X and Y dimensions map to an annulus ring with `inner` and `outer` diameter, and run `atan2` on the voxel's X and Y location whenever OSPray asks for its value... (I'm hand-waving here, but you get the gist, maybe. I'm the guy that wrote the in-house raymarch visualizer, using DirectX 12, so there's some experience there.)
- May be possible, but don't expect any help from us -- nor would we have an interest in such a thing since it's fairly niche.

Note, I don't expect help with it -- my company allows me to spent time on this. Judging from a quick look at the code, I'm fairly certain this is doable. The main thing I'm after is a quick confirmation that there are no immediate deal-breakers that blow this idea out of the water.

So thoughts are welcome, but I understand your time is valuable and you guys are plenty busy.

Thanks,

Jaap Suter

**Comment by jeffamstutz** [comment]
I would say this is totally doable! Basically volumes in OSPRay have the following 2 questions to answer for the renderer:

1. Given a 3D point in world coordinates: what is the volume's interpolated sample value for that point?
2. Given a ray and a distance along the ray: what should be the distance to the next sample point given a user supplied sampling rate?

If whatever type of data is able to answer those two questions then you can easily fit inside everything OSPRay has to offer, including our scaled out MPI offload rendering (where scene gets replicated on all nodes to scale up performance)...for free :)

This is EXACTLY what we want users to do: implement the one (or couple of) missing parts inside OSPRay that you need for your specific application and let us do everything else. Thanks for being able to take the lead on it...but know we are here to help you if you get stuck fitting into the bigger picture. ISPC can certainly have some "gotchas", but if you have shader experience with DX12 then you should feel right at home.

Note that this can be done either as a stand alone "module" or done right inside your client application. The module approach makes it easier to share with others, but that decision is totally up to you, no pressure! We can help in guidance (and even bug fixing our stuff) in either approach.

**Comment by carsonbrownlee** [comment]
Cool!  To add a little to Jeff's comments - I would say the implementation is fairly "trivial", beyond the unfortunately requirement for writing ISPC code as Jeff mentioned.  It should be mostly copy and paste.  The structuredvolume_sample() function already maps from world coordinates to cartesian- you will need to modify that mapping of world to local coordinates and vise versa.  You will also likely need to modify the interpolation in that same sample function.  That in theory should be it really, the underlying OSPData storage and other interactions with the volume shouldn't know or care about how you are representing the data.

**Comment by carsonbrownlee** [comment]
And also as far as modules go - I would highly recommend using the module interface even if you do not decide to share your code.  It will make maintaining your code contribution with the latest OSPRay updates far easier.

**Comment by ingowald** [comment]
Option b - quite doable, using pretty much the math you outlined :-).

The abstraction to a volume is “sample(world sample pos) -> scalar field value”, so as long as _you_ can map that 3D world pod to a value everything is easy...

**Comment by JaapSuter** [comment]
Great to hear guys. I'll start taking a stab and it and share updates here. Feel free to close this issue for now if you don't want to clutter the open-issue list. Thanks for the positive comments, very encouraging.
