### ISSUE TITLE
Viability of Win 32-bit port

### ISSUE THREAD

**Issue by nenad-vujicic** [ospray/ospray#264]
Hello everyone,

I see the OSPRay platform requirements are 64-bit only. Before contemplating a port to Windows x86 (32-bit) with some restricted features, what is the reason or decision behind 64-bit only? Is it a hard technical blocking issue in the dependencies, or another reason please? Some background would be much appreciated, thanks. If feasible, any pointers to key areas?

Thanks,
Nenad.

**Comment by jeffamstutz** [comment]
Hi,

There are a number of limitations associated with 32-bit OS support (mainly memory allocation size limits), as well as OSPRay requiring at least SSE4.2 which has 64-bit support. The vast majority of our users are on Linux, and all Windows users we have encountered are running 64-bit. Given that 32-bit only environments are relatively rare and that the limitations it imposes have been solved for a long time (i.e. 32-bit it is not the future), we've ignored it.

Of course, OSPRay is open source and you are free to use/modify it as you see fit! However, it's very unlikely that limitations that arise from a 32-bit only OS won't be interesting for us to spend any time on solving.

Hope that helps!

Cheers,
Jeff
