### ISSUE TITLE
Scaling artifacts

### ISSUE THREAD

**Issue by karjonas** [ospray/ospray#274]
Hi,

It seems OSPRay does not handle some scaling well. When scaling the “NASA Streamlines” demo to 0.1 in all directions artifacts start to appear. See image:

![image](https://user-images.githubusercontent.com/754587/46609978-bb297280-cb09-11e8-9635-9d331a0928cd.png)

**Comment by carsonbrownlee** [comment]
hi karjonas,
thanks for letting us know.  When you say scaling, what and how are you scaling exactly?  Is this "scale resolution"?

**Comment by carsonbrownlee** [comment]
I see, we suspect that it's a precision issue that was fixed in spheres/cylinder intersections but not brought over to streamlines.  I'm looking into it bringing those changes over now.

**Comment by carsonbrownlee** [comment]
also, you can click "smooth" and it will enable using curves to represent the streamlines which fixes this issue for now, though it will be slower.

**Comment by carsonbrownlee** [comment]
@johguenther was just working on a fix for precision issues with the sphere primitives that may fix this issue.  Johannes?

**Comment by carsonbrownlee** [comment]
@johguenther can you please advise whether your changes fix this issue?  We tried for spheres based on your branch and it seemed to scale correctly, I am assuming you are applying those to streamlines as well.

**Comment by johguenther** [comment]
Good that you confirm that it fixes the issue (I still have troubles with a reproducer). I'll port the fix to streamlines as well, but it can take until next week.

**Comment by johguenther** [comment]
Well, it took a bit longer, but the fix is now in branch `devel`. (The issue will be closed automatically once merged into `master`, i.e. with the next release.)
