### ISSUE TITLE
Missing header when installing from master branch

### ISSUE THREAD

**Issue by hernando** [ospray/ospray#275]
In the current master, math.ih includes sobol.ih, but that header is not listed in the OSPRAY_INSTALL_SDK_HEADER macro for the math subdirectory. I would submit a PR, but the current devel branch is quite different from master and the header is gone.

**Comment by jeffamstutz** [comment]
We try to close issues when things are in ```master```, and sorry for inconvenience. We'll do a ```v1.7.1``` release soon: we want to make sure any other bug fixes that have cropped up can also make it into that.

**Comment by jeffamstutz** [comment]
Also, thanks for the bug report. :)
