### ISSUE TITLE
Epsilon calculation for cylinder intersection test is bogus

### ISSUE THREAD

**Issue by hernando** [ospray/ospray#279]
Commit 8a8f84ae tries to solve an unspecified problem with secondary rays, but in doing so it takes code used for spheres that is actually broken for cylinders whose radius is smaller than 1.
What I'm observing is that primary rays that should hit the cylinder at the interior surface are not giving a positive intersection test because the epsilon added at Cylinders.ispc:131 is too large. Let's take 0.5 as an example, in that case the epsilon that is calculated is ~1.442.

**Comment by Twinklebear** [comment]
In 83b3e68b286d06787bb5d8ee2085af6b5bf1f21c I added a check that tries to keep the epsilon for spheres from getting too big (to avoid the same issue you describe but on the Sphere geometry). We could probably add the same check for the Cylinders as well.

**Comment by hernando** [comment]
In my opinon, the code in Spheres.ispc looks like three hacks in a row. Why not replacing lines 372-379 with:

    self->epsilon = log (self->radius + 1);

and if necessary scale the result of `log(self->radius + 1)`?

I've just tested it and it works fine for a scene I've created with spheres of different radii (100/(2^i), i in [0, 10])

**Comment by johguenther** [comment]
It also breaks under scaling, because ray-space is not taken into account (i.e. when ray dir is not normalized).

**Comment by hernando** [comment]
The fix I propose doesn't work under scaling, but the problem comes from somewhere else. Could you please at least comment on the correctness of the proposed solution in the absence of scaling. We want to replace our custom cylinder code with OSPray's one, but this issue is a blocker. If the proposed fix goes in the right direction, we could temporarily use a branch in our fork until a proper solution is found.

**Comment by johguenther** [comment]
I'll remove that extra epsilon altogether. The cylinder and sphere intersection code will be updated soon (featuring improved precision, see also #274).

**Comment by johguenther** [comment]
The fix is now in `devel` / ff711c506d745d474179a0f40d92944907c2fd86, reworking the epsilon handling in general. Could you please verify it works for you?
