### ISSUE TITLE
Multivariate volume rendering support

### ISSUE THREAD

**Issue by ukabuer** [ospray/ospray#280]
I have a multivariate scalar field and I want to render several variables as one volume, but I didn't find any related information in the documentation. Does OSPRay support multivariate volume rendering?

**Comment by johguenther** [comment]
Currently OSPRay only supports scalar volume data, but we plan to add multivariate volumes (no concrete ETA yet).

**Comment by carsonbrownlee** [comment]
multivariate scalar fields are on our short list of features.  The main complication is figuring out how we want to support all the various blending operations, or if we need a programmable sampling function.

**Comment by jeffamstutz** [comment]
There are several options here moving forward:

- use shared `OSPData` arrays with stride to reference which channel of the volume you wish to renderer, which will avoid the need to copy data
- use more than one volume on top of each other to see them visualized concurrently (using the above strided data technique, if so desired)
- write a custom renderer that combines each channel according to your desired visualization
- filter your data as a pre-processing step into a final volume for visualization (which would be a scalar volume)
