### ISSUE TITLE
[1.7.1] Calling ospShutdown() results in "#osp: INITIALIZATION ERROR"

### ISSUE THREAD

**Issue by samcaulfield** [ospray/ospray#281]
Hi,

Calling ospShutdown at the end of my application results in the following message being printed:

`#osp: INITIALIZATION ERROR --> OSPRay not yet initialized (most likely this means you tried to call an ospray API function before first calling ospInit())(pid 11405)`

ospShutdown() is the very final statement in my application and ospInit is unconditionally called at the start of my application. I'm not calling ospShutdown() twice or anything like that. My program otherwise performs as expected. Is this a known problem? If not, I can attempt to produce a minimal example (unfortunately the application I'm working on is not open source).

OSPRay version: 1.7.1
Embree version: 3.2.4

**Comment by jeffamstutz** [comment]
Howdy!

This sounds like static object lifetimes calling destructors after main() has completed. If you use any sort of object wrappers that call ```ospRelease()``` on destruction, that will cause the above error messages after ```ospShutdown()```.

This can also happen if you are using the scene graph (```ospray_sg```).

**Comment by samcaulfield** [comment]
Yes, you're totally right. No issue with OSPRay here, the problem was that an implicit destructor call for the FrameBuffer was occuring after ospShutdown(). That's what I get for mixing the C and C++ API's in the same program. Thanks!
