### ISSUE TITLE
Attempt to terminate non-local scheduler instance

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#282]
Hi 

I noticed that if I run OSPRay in debug build, I will get the following error 

```
/home/qadwu/Work/projects/ospray/builds/ospray-master-build/ospExampleViewer
Assertion is_set(s) failed on line 209 of file ../../src/tbb/governor.cpp
Detailed description: Attempt to terminate non-local scheduler instance
Signal: SIGABRT (Aborted)
```
It seems that the issue came from [those two lines](https://github.com/ospray/ospray/blob/master/components/ospcommon/tasking/detail/tasking_system_handle.cpp#L97-L98) where (I suppose) we are trying to terminate the tbb task created automatically and recreate a new one. I am not sure if this is the correct way but it seems TBB doesn't like it.

To avoid this issue and allow debugging other ospray components, I believe we have to **always** link against the non-debug version of TBB. So actually if we change the code from [here](https://github.com/ospray/ospray/blob/master/components/ospcommon/cmake/FindTBB.cmake#L100-L103) to 

```cmake
FIND_LIBRARY(TBB_LIBRARY tbb PATHS ${TBB_ROOT}/lib NO_DEFAULT_PATH)
FIND_LIBRARY(TBB_LIBRARY_DEBUG tbb PATHS ${TBB_ROOT}/lib NO_DEFAULT_PATH)
FIND_LIBRARY(TBB_LIBRARY_MALLOC tbbmalloc PATHS ${TBB_ROOT}/lib NO_DEFAULT_PATH)
FIND_LIBRARY(TBB_LIBRARY_MALLOC_DEBUG tbbmalloc PATHS ${TBB_ROOT}/lib NO_DEFAULT_PATH)
```
And the code fro [here](https://github.com/ospray/ospray/blob/master/components/ospcommon/cmake/FindTBB.cmake#L81-L84) to

```cmake
FIND_LIBRARY(TBB_LIBRARY tbb ${TBB_LIB_HINTS})
FIND_LIBRARY(TBB_LIBRARY_DEBUG tbb ${TBB_LIB_HINTS})
FIND_LIBRARY(TBB_LIBRARY_MALLOC tbbmalloc ${TBB_LIB_HINTS})
FIND_LIBRARY(TBB_LIBRARY_MALLOC_DEBUG tbbmalloc ${TBB_LIB_HINTS})
```

Then the problem might be **kind of** fixed ... until there is a better solution. This saved me from debugging ospray :D

Qi

**Comment by jeffamstutz** [comment]
We have this [in ospcommon](https://github.com/ospray/ospcommon/blob/master/cmake/FindTBB.cmake). Please report there if the issue persists.
