### ISSUE TITLE
[1.7.1] Possible incorrect documentation of Texture2D size parameter

### ISSUE THREAD

**Issue by samcaulfield** [ospray/ospray#283]
Hi,

When porting an application from an older version of OSPRay to v1.7.1 I encountered some strange behaviour when using the new texture API.

The "size" parameter of the Texture2D is documented as having type "vec2f" at http://www.sdvis.org/ospray/download/OSPRay_readme.pdf. However, when I use a vec2f for the texture size I get untextured meshes as a result. When I use a vec2i the texture is rendered as expected. The former texture API expected a vec2i which leads me to believe that there is an error in the new documentation.

**Comment by johguenther** [comment]
Good catch and thanks for reporting!
We'll change the docu to the correct `vec2i`.

**Comment by samcaulfield** [comment]
No problem, happy to help!
