### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by Jrwilliams43** [ospray/ospray#285]
Hello,
I download the precompiled binaries from ospray-1.7.2.x86_64.linux.tar.gz 

When I run my code I get these errors

dlerror() = libospray_module_mpi_native_float.so: cannot open shared object file: No such file or directory
dlerror() = libospray_module_mpi_native_float.so: cannot open shared object file: No such file or directory
dlerror() = libospray_module_mpi_native_float.so: cannot open shared object file: No such file or directory
dlerror() = libospray_module_mpi_avx_float.so: cannot open shared object file: No such file or directory
dlerror() = libospray_module_mpi_avx_float.so: cannot open shared object file: No such file or directory
dlerror() = libospray_module_mpi_avx_float.so: cannot open shared object file: No such file or directory
#osp: INITIALIZATION ERROR --> could not open module lib ospray_module_mpi: libmpifort.so.12: cannot open shared object file: No such file or directory
dlerror() = libospray_module_mpi_sse4_float.so: cannot open shared object file: No such file or directory

After checking my lib directory I can not find these libraries
cmake                             libospray_module_ispc.so
libembree.so                      libospray_module_ispc.so.0
libembree3.so.3                   libospray_module_ispc.so.1.7.2
libospray.so                      libospray_module_mpi.so
libospray.so.0                    libospray_module_mpi.so.0
libospray.so.1.7.2                libospray_module_mpi.so.1.7.2
libospray_app.a                   libospray_mpi_common.so
libospray_common.so               libospray_mpi_common.so.0
libospray_common.so.0             libospray_mpi_common.so.1.7.2
libospray_common.so.1.7.2         libospray_mpi_maml.so
libospray_imgui.so                libospray_mpi_maml.so.0
libospray_imgui.so.0              libospray_mpi_maml.so.1.7.2
libospray_imgui.so.1.7.2          libospray_sg.so
libospray_imgui3d_sg.so           libospray_sg.so.0
libospray_imgui3d_sg.so.0         libospray_sg.so.1.7.2
libospray_imgui3d_sg.so.1.7.2     libospray_tfn.so
libospray_imgui_util_sg.so        libospray_tfn.so.0
libospray_imgui_util_sg.so.0      libospray_tfn.so.1.7.2
libospray_imgui_util_sg.so.1.7.2  libtbb.so
libospray_json.so                 libtbb.so.2
libospray_json.so.0               libtbbmalloc.so
libospray_json.so.1.7.2           libtbbmalloc.so.2

How can I obtain these libraries

**Comment by johguenther** [comment]
When loading a module OSPRay tries different names for the dynamic library. The output you see is mostly warnings, except the one with `ERROR`: It looks like you try to use MPI based parallel rendering, thus the module `ospray_module_mpi` is needed, which is included in the tar-ball. However, a dependency is not met: `libmpifort.so.12` could not be found, which is part of the Intel MPI library. Do you have it installed, and sourced the `mpivars` script?

**Comment by Jrwilliams43** [comment]
I do not have the Intel MPI library installed. Is it possible to use openmpi instead?

**Comment by Jrwilliams43** [comment]
Thank you. I will try compiling OSPray.
