### ISSUE TITLE
Provide exported targets in ospray-config.cmake

### ISSUE THREAD

**Issue by mathstuf** [ospray/ospray#286]
It would be nice to have OSPRay install exported targets for `find_package(ospray)` consumers. This would allow for `target_link_libraries(mytgt PRIVATE ospray)` to get the library and include directories automatically.

**Comment by wilsonCernWq** [comment]
I previously submitted a [pull request](https://github.com/ospray/ospray/pull/263) for adding modern cmake support. Maybe the feature will be available soon.

**Comment by mathstuf** [comment]
Thanks for the pointer. Should have searched PRs as well. I'll take a look.

**Comment by jeffamstutz** [comment]
This is implemented in `v1.8.0`. Please let us know if you run into any issues!
