### ISSUE TITLE
Segfault with --animation OBJ-cts

### ISSUE THREAD

**Issue by DarkFlink** [ospray/ospray#288]
![default](https://user-images.githubusercontent.com/31723721/48976985-4521a080-f0a2-11e8-9bc7-bc875808e077.png)

Problem with animation here. I tried to create frame-based animation in ospExampleViewer. When I import a sequence of static OBJ files it's OK, but, when I use --animation to create animated scene that segfault happens. I don't know where this exception was thrown. What's the problem?

**Comment by carsonbrownlee** [comment]
hello, animations were broken on devel a while back.   It should work with an older version.  I can fix it, but I believe exampleViewer is currently being phased out in favor of "OSPRay Studio", which unfortunately does not currently support animations.

**Comment by DarkFlink** [comment]
Ok, I see. Thank you
