### ISSUE TITLE
Incorrect unstructured volume rendering with uchar type, but not with float

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#289]
With 1.7.2 I see a strange issue when using an unstructured volume and voxel data type uchar. This is with a regular structured grid of data (128^3 values) represented using an unstructured grid of hexahedrons (to work around #159). 

When the data type is uchar the volume is incorrectly duplicated 4x4 times in a smaller format. When I use the exact same data values in the volume, but represented as floats, the rendering is correct. See images.

![wrong](https://user-images.githubusercontent.com/1408287/49537244-c65e0c00-f8c8-11e8-8339-ce28d666f9a6.png)

![correct](https://user-images.githubusercontent.com/1408287/49537243-c65e0c00-f8c8-11e8-8ac1-d8725c212ebe.png)

**Comment by paulmelis** [comment]
Hmmm, here's a similar error I get when using the same uchar data, represented as an unstructured volume but this time rendered as isosurface for a single value. Given the weird nature of the output I suspect the error is not in my code, but I'm still not sure.

![isoerror](https://user-images.githubusercontent.com/1408287/49539365-c7456c80-f8cd-11e8-9173-41eda5e92d88.png)

**Comment by jeffamstutz** [comment]
Hi,

Our unstructured volumes currently only support ```float``` field values. We could generalize this to the same supported field types as our structured volumes in a future release.

I'm fascinated by the fact that it didn't crash, but that's the nature of undefined behavior! :)

Cheers,
Jeff

**Comment by paulmelis** [comment]
Argh, how did I miss that?! Well, probably by starting out with a structured uchar volume and then moving it to unstructured without checking the docs thoroughly enough.

Oh, and this might also explain the occasional segfault I get :wink:

I'll close this one
