### ISSUE TITLE
intrinsics

### ISSUE THREAD

**Issue by bilgili** [ospray/OSPRay#29]
Hi,

As it can be seen below the GNU stdc++ headers are colliding with the ones from ospray. I can simply work over for our case but it seems like it will be a long term problem. I think those functions has to be moved into embree space or renamed or put into conditions, but I am not sure about the side effects ( meaning I dont have all the possible hardware to test, especially the MIC ).

/gpfs/bbp.cscs.ch/apps/viz/bbp/dev/ospray/0.8.2/include/ospray/embree/common/sys/intrinsics.h: In function ‘uint64 __rdtsc()’:
/gpfs/bbp.cscs.ch/apps/viz/bbp/dev/ospray/0.8.2/include/ospray/embree/common/sys/intrinsics.h:291:46: error: ‘uint64 __rdtsc()’ redeclared inline without ‘gnu_inline’ attribute
 __forceinline uint64 __rdtsc()  {
                                              ^
In file included from /gpfs/bbp.cscs.ch/apps/viz/bbp/dev/gcc/4.8.3/lib/gcc/x86_64-unknown-linux-gnu/4.8.3/include/x86intrin.h:27:0,
                 from /gpfs/bbp.cscs.ch/apps/viz/bbp/dev/gcc/4.8.3/include/c++/4.8.3/x86_64-unknown-linux-gnu/bits/opt_random.h:33,
                 from /gpfs/bbp.cscs.ch/apps/viz/bbp/dev/gcc/4.8.3/include/c++/4.8.3/random:51,
                 from /gpfs/bbp.cscs.ch/apps/viz/bbp/dev/gcc/4.8.3/include/c++/4.8.3/bits/stl_algo.h:65,
                 from /gpfs/bbp.cscs.ch/apps/viz/bbp/dev/gcc/4.8.3/include/c++/4.8.3/algorithm:62,

**Comment by jeffamstutz** [comment]
I believe I fixed this in our next release branch (release-0.8) with a namespace. For now, try that branch...everything in that will end up in 0.8.3, which should be out soon...

Over the long term, we will be evaluating how embree is integrated in the project build as the internal version of embree is a little old. I am trying to stay afloat on as many versions of gcc/icc/clang as possible. What OS distro are you running? I see that it's gcc-4.8.3.

**Comment by bilgili** [comment]
We are using the Red Hat Enterprise Linux Server release 6.7 (Santiago)
But we are using GNU modules on top of it. The gcc compiler is version 4.8.3.

I saw the changes. With latest changes in Ospray, there seems to be changes needed on our side too. I will let you know.

**Comment by jeffamstutz** [comment]
Closing the issue as it isn't reproduceable in the latest OSPRay release. Will reopen if it can be reproduced.

**Comment by bilgili** [comment]
It is now working. Thanks for the support !
