### ISSUE TITLE
ospray_Exports.cmake includes hard reference to /home/visuser/builds/ZzUs3xsc/0/sdvis

### ISSUE THREAD

**Issue by jfavre** [ospray/ospray#298]
The hard-coded reference makes my VTK build fail. I build with cmake 3.12.1 and CMAKE_BUILD_TYPE=RelWithDebInfo

I hand-edited ospray_Exports.cmake , changing
`
set_target_properties(ospray::tasking PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OSPRAY_TASKING_TBB"
  INTERFACE_LINK_LIBRARIES "\$<\$<NOT:\$<CONFIG:DEBUG>>:/home/visuser/builds/ZzUs3xsc/0/sdvis/ospray/deps/tbb2019_20181203oss/lib/intel64/gcc4.7/libtbb.so.2>"
`

(more pathes deleted from the message)

to
`
  INTERFACE_LINK_LIBRARIES "/local/apps/ospray-1.8.0.x86_64.linux/lib/libtbb.so;/local/apps/ospray-1.8.0.x86_64.linux/lib/libtbbmalloc.so"
`

in order to get through.

**Comment by jeffamstutz** [comment]
Thanks for the bug report, we can fix this ASAP in a `v1.8.1` release.

**Comment by jalevine** [comment]
I noted the same problem with ospray-1.8.0.x86_64.macosx.tar.gz and ospray-1.8.0.x86_64.dmg, but was fixable by hand-setting the path the same as jfavre

**Comment by jeffamstutz** [comment]
Quick update: working on these issues this week. The issue centers around the `ospray::tasking` target we use to abstract away the includes/libs/definitions surrounding the tasking library used by `ospcommon`. I'm making some progress, but need to make sure that everything checks out. :)

**Comment by jeffamstutz** [comment]
This is enough to generate a `v1.8.1` release, which will be cut once things look good.

**Comment by jeffamstutz** [comment]
This should be fixed now in `v1.8.1`, please let us know if you run into any other issues!
