### ISSUE TITLE
Hardcoded path to C:\tbb2018_20170919oss\lib\intel64\vc14\tbb_debug.lib

### ISSUE THREAD

**Issue by acdemiralp** [ospray/ospray#299]
Windows 1.8.0 installer contains a hardcoded path to the given URI above.

**Comment by acdemiralp** [comment]
Similarly, the Windows 1.8.0 does not contain the Embree library, which prevents building anything with it.

**Comment by acdemiralp** [comment]
Also source build leads to:
CMake Error at library/cmake/FindOSPRay.cmake:43 (load_cache):
  load_cache Cannot load cache file from
  C:/development/build/_external/ospray-1.8.0/msvc141/Release/CMakeCache.txt

There is no way to use Ospray 1.8.0 for Windows at the moment.

**Comment by jeffamstutz** [comment]
Thanks for reporting this! This is a duplicate to #298, so we will use that issue to track when it is fixed.
