### ISSUE TITLE
find . -name \*1.8.0\*

### ISSUE THREAD

**Issue by jfavre** [ospray/ospray#301]

**Comment by jeffamstutz** [comment]
Howdy,

Did you find something from `v1.8.0` in the `v1.8.1` release? And find/grep command didn't come up with anything 1.8.0 related in a fresh build/install of 1.8.1 or in the binary packages.

**Comment by jfavre** [comment]
bad noise. one too many mouse click? I don't remember. Let's ignore this. Sorry.

**Comment by jeffamstutz** [comment]
no problem, just making sure there wasn't an issue. :)
