### ISSUE TITLE
Example illustrating offline render ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray#305]
Hi,

  I am looking for some C/C++ example which illustrate the OSPRay API in setup and render of some simple object and cleanup without any OpenGL or interactive display.

  Are there any such examples ?

Cheers

**Comment by jeffamstutz** [comment]
Yup! Have a look at [ospTutorial.c](https://github.com/ospray/ospray/blob/master/tutorials/ospTutorial.c)
