### ISSUE TITLE
find_package(ospray) has side effects and can't be called twice

### ISSUE THREAD

**Issue by hernando** [ospray/ospray#307]
The macro `ospray_create_tasking_target` creates a target called `ospray_tasking`. When find_package(ospray) is called twice from client projects, which may happen when a depedent CMake project has a depended project where both depend on OSPRay, the second call fails because it can't redefine the target. Something similar happens with `ospray_create_embree_target`.

**Comment by jeffamstutz** [comment]
We are about to do a v1.8.3 release, so I can get a fix in for this ASAP (both `ospray_tasking` and `embree` targets). Thanks for reporting this, and sorry for the inconvenience!

**Comment by hernando** [comment]
You can use [this commit](https://github.com/BlueBrain/OSPRay/commit/4d198ec39c2aac52b3a0ab456f4ed44f748259e9) as reference.

**Comment by jeffamstutz** [comment]
FYI, I have a fix for this on `release-1.8.x` (tested with my minimal [ospTutorial](https://github.com/jeffamstutz/ospTutorial_external) app).

**Comment by hernando** [comment]
Great, thanks!
