### ISSUE TITLE
Support for double volume

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#309]
Hi All,

Recently we are rendering a double type volume. However this volume has a very strange value range: (1e-15 to 1e-13). Values outside this region are not looking good so we simply want to remove them.

When I put this volume in OSPRay (OSPRay supports double I know), I was getting wired, noisy images. The reason was that, the transfer function API cannot correctly understand my value range. I can only have the volume correctly rendered if I manually scale the volume up by a factor of 1e15. 

I know ISPC might not like double, which is probably why we does not have a `ospSet1d` call in the API. But logically if we say ospray supports double, we should at least have a double-typed transfer function support. 

So here I simply want to open a discussion about this issue and potential solutions.

Best

Qi

**Comment by johguenther** [comment]
Although OSPRay accepts `double` as data type when the volume is created, during rendering/sampling only `float` is used internally. Thus, supporting only float for the transferfunction is "fine". Also, the values around 1e-15 can be well represented in (even normalized) float. Which means we need to have a closer look what produces the noise artifacts.

**Comment by wilsonCernWq** [comment]
I agree with you. 1e-15 is actually not that small. That was something confused me as well. I can make a dummy test case to see if I can repeatedly produce this error.

**Comment by wilsonCernWq** [comment]
Hmm I think when I am looking at this issue again, the problem actually disappeared. Maybe it was caused by a totally different bug I wrote ... I will let you guys know if I can confirm this is actually a problem with ospray. Thanks.
