### ISSUE TITLE
Unable to do initial compile

### ISSUE THREAD

**Issue by tomtsops** [ospray/OSPRay#31]
I've just downloaded the latest repository and the latest intel ispc.

When i follow the directions, and I try to use ccmake, I get this error:

 CMake Error at CMakeLists.txt:20 (CONFIGURE_OSPRAY):
   Unknown CMake command "CONFIGURE_OSPRAY".

I don't know how to get around this.  Can somebody please help?

Thanks,
Tom T.

**Comment by jeffamstutz** [comment]
Can you list what environment you're working in? OS, version of CMake, which compiler, and verison of the compiler would all be helpful.

And just to be specific, you're working from the 'master' branch?

**Comment by tomtsops** [comment]
Hi Jeff,

My apologies, i was not in the correct hierarchy when I tried to make.  And to top it off, I was using RedHat which was giving me all sorts of other issues with missing libraries.  I switched over to CentOS and I was able to get things to compile, well at least its in the middle of compiling :)

Thanks for the quick reply.
