### ISSUE TITLE
ospSet1b and ParameterizedObject::getParam inconsistency

### ISSUE THREAD

**Issue by karjonas** [ospray/ospray#314]
Hi,

After OSPRay 1.8.3 there is some inconsistencies when using ospSet1b and ParameterizedObject::getParam. Since using ospSet1b will implicitly set an int, when you later try to read the parameter as a bool with getParam the type check fails. Maybe setParam and getParam should be overloaded to convert the boolean to an int instead of doing it in ISPCDevice::setBool?

Regards, Jonas

**Comment by jeffamstutz** [comment]
We have this fixed in a pending internal merge to `devel`, where all bool parameters will actually require the use of `ospSet1b()` and no longer allow `ospSet1i()`. That is a bigger/breaking change, but I think the right thing to do for the future.

The safest thing for `v1.8.x` is to use the `getParam*()` functions in `ManagedObject` (where there's no `getParam1b`, so you must use `getParam1i`) instead of the generic version found in the base `ParameterizedObject`. For `v2.0`, the type correctness will be fixed so this inconsistency is avoided to allow accessing parameters at either object level.

**Comment by jeffamstutz** [comment]
Well, we may do a `v1.8.5` release soon, so I can toss your idea in. :)

**Comment by karjonas** [comment]
Cool, thanks :)

**Comment by jeffamstutz** [comment]
Sorry we are taking our sweet-old-time getting `v1.8.5` out, we are finding a few other unrelated things to update. The fix for this is at least on `release-1.8.x` now, if you'd like to use it right away.

**Comment by jeffamstutz** [comment]
This is now in `v1.8.5`.

**Comment by karjonas** [comment]
It seems the inconsistency is still here, for some reason when I call ospSet1b it ends up in the templated setParam in ParameterizedObject.h. But when I then use getParam it uses the specialized method in Managed.h. I fixed this by simply moving the specializations to ParameterizedObject.h.

**Comment by jeffamstutz** [comment]
What compiler are you using? I just confirmed that `ospSet1b` in ospTutorial.c does end up calling the specialization in `Managed.h` (which just does setParam<int> instead of setParam<bool>), and that `getParam<bool>`, `getParam<int>`, and `getParam1i` all correctly gets this value.

**Comment by karjonas** [comment]
I use both gcc and clang. I think the difference is that I use ```getParam``` inside of a custom renderer that inherits from ```ospray::Renderer```. I cannot understand why this gives different behaviour though.

**Comment by jeffamstutz** [comment]
It may be that the specialization is only visible in the `ospray` namespace? There are some C++ template specialization rules here that may be causing issues.

One quick test would be if you could wrap your renderer in the `ospray` namespace to see if that makes a difference?

**Comment by karjonas** [comment]
I tried also calling ```ospSet1b``` in ospTutorial.c and actually end up in the wrong place here as well.

I added ``` ospSet1b(camera, "my_test", 1);``` on line 97 and then I get this backtrace:

```
#0  ospcommon::utility::ParameterizedObject::setParam<bool> (this=0x55555577f540, name="my_test", t=@0x7fffffffd214: true)
    at /home/jkarlsso/Work/ospray/components/ospcommon/../ospcommon/utility/ParameterizedObject.h:95
#1  0x00007ffff5d93503 in ospray::api::ISPCDevice::setBool (this=0x55555577c590, _object=0x55555577f530, bufName=0x555555555ca0 "my_test", b=true)
    at /home/jkarlsso/Work/ospray/ospray/api/ISPCDevice.cpp:237
#2  0x00007ffff7b890d3 in ospSet1b (_object=0x55555577f530, id=0x555555555ca0 "my_test", x=1) at /home/jkarlsso/Work/ospray/ospray/api/API.cpp:780
#3  0x000055555555575e in main (argc=1, argv=0x7fffffffd598) at /home/jkarlsso/Work/ospray/tutorials/ospTutorial.c:97
(gdb) l
90	
91	    template<typename T>
92	    inline void ParameterizedObject::setParam(const std::string &name,
93	                                              const T &t)
94	    {
95	      findParam(name, true)->set(t);
96	    }
97	
98	    template<typename T>
99	    inline T ParameterizedObject::getParam(const std::string &name,
(gdb) 
```

So it seems we have different behaviour for some reason I cannot explain.
