### ISSUE TITLE
White pixels in render output

### ISSUE THREAD

**Issue by hieronymusanthonius** [ospray/ospray#316]
Can somebody explain how those white pixels occur ? ( and how to reduce them )

![Knipsel](https://user-images.githubusercontent.com/49530817/55974897-92cd2d00-5c80-11e9-987a-ae56d86ccbf2.PNG)

Thanks in advance

**Comment by jeffamstutz** [comment]
The amount of artifacts you are seeing is definitely not normal and looks like something is wrong (maybe a bug?).

Can you provide any details about what you are rendering? (ex: spp, number of frames refined, lights/materials used, etc.) Ideally we would like to reproduce this ourselves, either by directly rendering your scene (if allowed) or in a small proxy scene representative of what you are doing.

@johguenther thoughts or ideas?

**Comment by hieronymusanthonius** [comment]
I am using a spotlight and an ambient light in the scene. When I remove the spotlight the effect is gone.


The geometry is constructed from custom 3D file format , but are all triangles. 
 
I used mostly obj materials with 2d textures.

**Comment by johguenther** [comment]
A workaround is (probably) to set the renderer parameter "`maxContribution`" to something like 5. Does the spotlight have a `radius` > 0?

**Comment by hieronymusanthonius** [comment]
The radius was always set to 1, when I increase the artifacts disappear, thanks a lot
