### ISSUE TITLE
Library unload crash

### ISSUE THREAD

**Issue by karjonas** [ospray/ospray#317]
Hi,

After upgrading from OSPRay 1.7.2 to 1.7.3 I get segmentation faults. I guess it is because OSPRay is now calling ```dlclose``` on the libraries it loads. If I set the variable ```freeLibOnDelete``` to false then there are no more segmentation faults. Could this be related to the fact that ```ospray_module_ispc``` is loaded both by OSPRay and by my calling library? This crash is quite sporadic and happens only on certain systems and certain compilers.

**Comment by jeffamstutz** [comment]
It sounds like you are on the right track. Are you just doing `ospLoadModule("ispc")` in your app?

**Comment by karjonas** [comment]
No. What I do is I load a plugin dynamically with dlopen which in turn has a dependency on ospray.

**Comment by karjonas** [comment]
So I "solved" this problem by simply using a newer compiler, and since I do not think this is an issue on your part I will close this issue.
