### ISSUE TITLE
Ospray on iOS

### ISSUE THREAD

**Issue by hieronymusanthonius** [ospray/ospray#319]
Thank you very much for the great effort.
I have a question. I request you to help. Sorry for asking my question as a "issue". I could not find any option to mark it as a request/question. 

Would it be theoretically possible to compile OSPRAY for iOS?  **Feature**

**Comment by johguenther** [comment]
I doubt that: OSPRay and Embree require SSE instruction set, which is not supported on ARM. However, what should work well is to use an iOS device for remotely viewing OSPRay renderings (see e.g. the [Tapestry](https://seelabutk.github.io/tapestry/) project.

**Comment by BruceCherniak** [comment]
I don’t know about iOS specifically, but you might take a look at the work that Syoyo Fujita has done on the Android/aarch64 version of Embree, and ispc.

https://github.com/lighttransport
https://github.com/lighttransport/embree-aarch64

https://github.com/syoyo/repositories
https://github.com/syoyo/ispc-aarch64
https://github.com/syoyo/tbb-aarch64

Cheers,
Bruce

On Apr 29, 2019, at 5:01 AM, Johannes Günther <notifications@github.com<mailto:notifications@github.com>> wrote:


I doubt that: OSPRay and Embree require SSE instruction set, which is not supported on ARM. However, what should work well is to use an iOS device for remotely viewing OSPRay renderings (see e.g. the Tapestry<https://seelabutk.github.io/tapestry/> project.
