### ISSUE TITLE
Running the tutorial provided - getting error

### ISSUE THREAD

**Issue by tomtsops** [ospray/OSPRay#32]
Hello,

I'm able to compile the tutorial doing the following:

g++ ../apps/ospTutorial.cpp -I ../ospray/include -I .. -I ../ospray/embree/common  ./libospray.so -o ospTutorial

But when I try to execute it, i get the following error:

./ospTutorial: error while loading shared libraries: libospray.so.0: cannot open shared object file: No such file or directory

the libospray.so.0 exists in that directory, so I'm not sure what the issue is.  My apologies in advance for this basic question!  

thanks,
Tom

**Comment by johguenther** [comment]
Hi Tom,
which branch are you using? `master`?
`libospray.so.0` is usually just a symbolic link to e.g. `libospray.so.0.8.2`, which could be missing (but then compilation of `ospTutorial` would already have failed).
What is the output of `ldd ./ospTutorial`?

Best regards,
	Johannes

**Comment by tomtsops** [comment]
I believe its the master, i did git clone, followed the steps described on this site.

the libosprasy.so.0.8.2 looks to be thre:

2167875  Nov 25 14:59 libospray.so.0.8.2
18            Nov 25 14:59 libospray.so.0 -> libospray.so.0.8.2
14            Nov 25 14:59 libospray.so -> libospray.so.0

when i do ldd ./ospTutorial i get:

$ ldd ./ospTutorial 
	linux-vdso.so.1 =>  (0x00007fff2cb85000)
	libospray.so.0 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd63d14e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd63ce4c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd63cc36000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd63c874000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd63d46b000)

So, I'm not sure why it is not seeing the file, which is in the same directory.

Thanks,
Tom

**Comment by johguenther** [comment]
OK, I think we got it. Two solutions:
 1. use `export LD_LIBRARY_PATH=.` to hint that the dynamic lib can be found in the local directory
 2. append `-Wl,-rpath,.` to the command line when compiling

Thanks for reporting, I will update the documentation accordingly.

**Comment by tomtsops** [comment]
Perfect!  Thanks you, both solutions worked.

Seeing as I'm new to ospray, is there documentation that describes all the various functions available?

thanks,

Tom

**Comment by johguenther** [comment]
You can use Doxygen to generate documentation (`make doc`). We also work on improving the documentation for the next release.
