### ISSUE TITLE
API reuse rtc objects

### ISSUE THREAD

**Issue by Tradias** [ospray/ospray#323]
The following use case describes a potential API extension point that allows users of both Embree and OSPRay to achieve higher performance.

In my application, I am directly constructing rtcDevice, rtcScene, rtcGeometry and similar objects from the Embree library for use in ray tracing calculations. Now I would like to use OSPRay to create images of the the geometries. Do you plan on adding either:

* a possibility to pass a rtcScene to the OSPRay API (I am fine with those objects becoming unusable for me afterwards)

or

* a possibility to steal the rtcScene from an OSPRay object?

That would spare the cost of recalculating the BVH for the same geometries which is high compared to the few, small images that I create of them with OSPRay.

**Comment by johguenther** [comment]
Interesting usecase. The first option probably won't work, because to generate images with OSPRay more than just the rtcScene is needed (e.g. an OSPWorld, and OSPRay extends geometries to have `postIntersect` functions, which are important for shading).

Thus the second idea seems more realizable. In fact, you could even implement that yourself with a plugin: e.g. a renderer module has access to the `World` and thus also to the `RTCScene`.

**Comment by Tradias** [comment]
Cool, didn't know that plugins might be capable of doing it. I will check them out.

I wonder how these `postIntersect` functions would affect the ray traces I perform on the obtained `RTCScene`. Also what happens when I set up my own `rtcIntersectionFilterFunction`. Overall, this workflow sounds rather complex and difficult to implement for the user.

Do you think api v2.0 of OSPRay could provide more fine grained control that would grant users better interoperability between Embree and OSPRay?

**Comment by johguenther** [comment]
We currently have no plans to add API support in v2 to allow for sharing of scenes between Embree and OSPRay. Note that this is actually quite hard to get right for the general case (just exchanging the `RTCScene` in not sufficient): for example OSPRay adds own `RTCFiterFunctions` (and, as said, needs more data that what is on the Embree side). Not to speak of the distributed rendering modes.

So, I think something could be hacked for your specific usecase (e.g. drilling a hole to pass the RTCScene to OSPRay's OSPWorld), but not as a robust, general solution.

But maybe that is not necessary at all. I understand that you are mostly worried about the cost to build the BVH a second time? That should not be a problem, BVH build usually takes just a fraction of a second (or just few seconds even for huge scenes). Also memory should not be an issue if your application shares the geometry with Embree and also with OSPRay.

**Comment by jeffamstutz** [comment]
We can't implement this officially as only one of our backends assumes that there are local `rtc*` objects at all. However, if you are always using our `cpu` device, then you can use the SDK headers to cast the `OSPWorld` to an `ospray::World` to get access to Embree objects that OSPRay is creating. Beware that we only guarantee API compatibility between releases of the public API found in `"ospray.h"`, though I don't see our Embree object layouts changing at all during the `v2.x` release lifetime.
