### ISSUE TITLE
Benchmark fails with exit code 1 on windows10 x64

### ISSUE THREAD

**Issue by 111alan** [ospray/ospray#325]
Just begun to mess around with ospray to do a performance test. Most scenes and tool in the bin folder(example viewer, spheres, bouncing spheres, structuredvolume, subdivision and unstructuredvolume) works without problem, but the ospbenchmark.exe and runbenchmark.py fails. I was able to captured the screen quickly enough and saw the fail message with exit code 1.

I already tried installing TBB, embree and opengl, even mpi library. Is there anything else I could do to fix this? 

Currently using a precompiled 1.8.5 zip package. The CPU is xeon platinum 8180 for now. Thank you.

![ospray](https://user-images.githubusercontent.com/30613544/58671585-c457a000-8375-11e9-87e1-6b274f19ef69.JPG)

**Comment by jeffamstutz** [comment]
It appears that these scripts assume that `ospBenchmark` is on your PATH when invoked. Can you run `ospBenchmark.exe` manually?

**Comment by 111alan** [comment]
I didn't noticed that I have to move the batch file to the bin folder to get it working until I look into the file. Thank you for the attention :X
