### ISSUE TITLE
vector subscript out of range?

### ISSUE THREAD

**Issue by tom-sakai601220** [ospray/ospray#326]
When I run ospTutorialBouncingSpheres() debug build,
Debugger suggest 
"
Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
"
void PathTracer::commit()
{
  &areaPDF[0]<----uninitialized()
}

**Comment by johguenther** [comment]
Thanks for reporting. I think this is a false positive, as we do not actually access the first element (even when the vector is empty). Anyway, the current implementation (for the next release) already changed this passage, thus I'll close.

**Comment by crowbar27** [comment]
There is a similar one in `components/ospcommon/utility/ParameterizedObject.cpp:63`. `&paramList[0]` can be replaced by `paramList.data()` as in a303a25 to fix it.
