### ISSUE TITLE
Backend loading should not be attempted if CPU support isn't there

### ISSUE THREAD

**Issue by mathstuf** [ospray/ospray#327]
If the CPU doesn't support AVX or any other available backend, OSPRay should error out instead of ending up triggering a `SIGILL` upon loading an unsuitable backend.

Cc: @chuckatkins

**Comment by jeffamstutz** [comment]
What was the situation that this occurred? By default we build all targets, which should support anything you throw at it.

**Comment by mathstuf** [comment]
I'm waiting for information on the affected machine, but here's the bottom of the stacktrace (with pointer values removed):

```
16      ospInit + 6153
15      ospLoadModule + 205
14      ospray::loadLocalModule(std::string const&) + 92
13      ospcommon::LibraryRepository::add(std::string const&) + 74
12      ospcommon::Library::Library(std::string const&) + 270
11      dlopen + 65
10      /lib64/libdl.so.2(+0x1665)
9       _dl_catch_error + 132
8       /lib64/libdl.so.2(+0xf96)
7       /lib64/ld-linux-x86-64.so.2(+0x13be9)
6       _dl_catch_error + 132
5       /lib64/ld-linux-x86-64.so.2(+0x14469)
4       /lib64/ld-linux-x86-64.so.2(+0xfce6)
3       /lib64/ld-linux-x86-64.so.2(+0xfbda)
2       /scratch1/Applications/ParaView/ParaView-5.6.1-1737-g555a362-MPI-Linux-64bit/bin/../lib/libembree3.so.3(+0x3a9c8)
1       /scratch1/Applications/ParaView/ParaView-5.6.1-1737-g555a362-MPI-Linux-64bit/bin/../lib/libembree3.so.3(+0xe5257)
0       /lib64/libc.so.6(+0x361a0)
(   2.259s) [paraview        ]                       :0     FATL|
Signal: SIGILL
Illegal instruction (core dumped)
```

**Comment by jeffamstutz** [comment]
Very interesting, it appears that Embree is actually the culprit. If that is the case, I am not sure how to guard against this within OSPRay itself.

My guess is that AVX512 compatibility being split between KNL and SKX means that they may not be able to coincide in the same binary. Could be wrong, but that's my first hunch.

**Comment by mathstuf** [comment]
Here is the relevant information from `/proc/cpuinfo` on the affected machine:

```
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
```

**Comment by jeffamstutz** [comment]
It looks like the ParaView superbuild [explicitly turns off < AVX support](https://gitlab.kitware.com/paraview/paraview-superbuild/blob/master/projects/embree.cmake), thus creating an incompatible library. I'm not sure OSPRay can detect at runtime that Embree is going to be incompatible, given that it loads it with `dlopen()` as seen in the stack trace.

I'm not sure what the right answer is.

**Comment by mathstuf** [comment]
Hmm, OK. I think we can just leave it to the docs that < AVX is not supported on macOS (for other reasons), but reenable it on other platforms. Thanks.
