### ISSUE TITLE
How can I run the simple tutorial on linux?

### ISSUE THREAD

**Issue by fdvty** [ospray/ospray#328]
I have compiled the source code and got 'ospTutorial'. How can I make it work? 
I tried: # ./ospExampleViewer ./ospTutorial
but it returned "unsupported file format" and nothing was shown in my window.
What should I do?

**Comment by jeffamstutz** [comment]
Hi,

`ospTutorial` and `ospExampleViewer` are both executables. If you just run `./ospTutorial`, you'll get two .ppm images as explained in our [documentation here](http://www.ospray.org/documentation.html#Examples).

`ospExampleViewer` takes 3D scene data files on the command line and shows them in an interactive window. Have a look at our [demos page](http://www.ospray.org/demos.html) to see some examples to work with.

**Comment by fdvty** [comment]
Thank you SO MUCH! It works!

**Comment by jeffamstutz** [comment]
:)
