### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ucmsuri** [ospray/OSPRay#33]
$ ospModelViewer fiu-groundwater.xml --renderer obj --sun-dir -1.5 -1 -1
#ospModelViewer: starting to process cmdline arguments
#ospModelViewer: done parsing. found model with
  - num meshes   : 2 [699706][7682241]
  - num instances: 2 [699706][7682241]
  - num unique triangles   : 8381947
  - num instanced triangles: 8381947
#ospModelViewer: number of instances matches number of meshes, creating single model that contains all meshes
#ospModelViewer: adding parsed geometries to ospray model
#ospModelViewer: committing model
#ospModelViewer: done creating ospray model.
#ospModelViewer: Adding a hard coded directional light as the sun.
#ospModelViewer: done creating window. Press 'Q' to quit.
#ospModelViewer: set world bounds [(-386.703, -228.986, -884.183); (391.012, 227.57, -20.6256)], motion speed 1.24861
Illegal instruction (core dumped)

**Comment by ucmsuri** [comment]
i am using ubuntu 14.04 LTS

**Comment by johguenther** [comment]
Hi,
which branch are you using? What is the setting of `OSPRAY_BUILD_ISA`? What CPU do you use?

**Comment by ucmsuri** [comment]
I am using v0.8.3. 
OSPRAY_BUILD_ISA                 ALL
 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

**Comment by jeffamstutz** [comment]
Hi ucmsuri,

Sorry for a late response. There isn't anything obvious from your configuration which would indicate why bad instructions would be emitted on Ubuntu 14.04 (assuming gcc as your compiler).

Have you tried updating to our latest release (0.9.0)? I would be interested in knowing if the issue has continued for you on 'master' and/or our next release branch 'release-0.9'.

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
Closing the issue as it can't be reproduced in the latest release (v0.10.0) with the same CPU.
