### ISSUE TITLE
Can not find a way to set the texture parameters using scene Graph

### ISSUE THREAD

**Issue by xziayro** [ospray/ospray#330]
Hello, 

I'm using the scene graph to render some object with texture coordinates. However, i did not find anything in the scene graph code in order to set the texture position and scale. Is the sceneGraph support textureParameters? 

Regards,
Stéphane

**Comment by jeffamstutz** [comment]
We have moved `ospray_sg` out of this project, but it will live on in [OSPRay Studio](https://github.com/ospray/ospray_studio). However, we need to rewrite its core to base it on the new `v2.0.0-alpha` API changes.
