### ISSUE TITLE
Model reference other model

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#336]
The documentation states:

> Models are a container of scene data. They can hold the different geometries and volumes as well as references to (and instances of) other models.

However it does not appear possible to add a model to another. Instancing appears to be a workaround but I cannot get it to work.

**Comment by johguenther** [comment]
You need to wrap the model into a geometry with `ospNewInstance` first, then you can add that geometry to another model.

**Comment by StasJ** [comment]
I tried that and it does not work.

World Model -> Instance -> Model -> Volume: Nothing rendered
World Model -> Volume: Renders volume

**Comment by johguenther** [comment]
Ah, you want to instance Volumes and not Geometries? Then unfortunately you need to wait for the next release (v2.0), because this is not supported in v1.8.
