### ISSUE TITLE
Adding multiple gradient effects 

### ISSUE THREAD

**Issue by tapaswenipathak** [ospray/ospray#337]
Hey folks, I was using ospray for visualisation for large-scale and interactive ray-tracing of neurons. I want the output like

![img](https://user-images.githubusercontent.com/4143778/61045651-e1fa3980-a3f8-11e9-8ef3-76cc994310b4.png)

Do you have any sample for this? I am v. curious if ospray have gradient setting feature? I was finding like [this](https://github.com/search?q=Ospray+gradient&type=Code) but great if you can let me know if you have such feature, I didn't find any tickets in the repository or a sample implementation.

**Comment by tapaswenipathak** [comment]
https://github.com/search?q=Ospray+gradient&type=Code

**Comment by johguenther** [comment]
OSPRay is successfully used to render neurons (see e.g. [Brayns](https://github.com/bluebrain/Brayns "bluebrain/Brayns")).

OSPRay can also render volumetric datasets, optionally with gradient shading, see `gradientShadingEnabled` at http://www.ospray.org/documentation.html#volumes.
