### ISSUE TITLE
Volume lighting broken near NAN values

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#341]
#141 

### Off

![off](https://user-images.githubusercontent.com/2772687/62151011-98e12b00-b2bc-11e9-91a2-1af2e508c3fc.png)

### On

![on](https://user-images.githubusercontent.com/2772687/62151013-9aaaee80-b2bc-11e9-8596-1b3ba048b089.png)

**Comment by jeffamstutz** [comment]
See #335 for general explanation.

Our plan is to have this repaired in v2.0. We will keep this open until it can be confirmed to be fixed.

**Comment by johguenther** [comment]
We have several fixes for NaN-values from volumes in place now. Can we close?

**Comment by johguenther** [comment]
Closing now. Please re-open if there are still issues.
