### ISSUE TITLE
samplingRate does not affect isosurfaces

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#342]
### Unstructured Volume
![uns](https://user-images.githubusercontent.com/2772687/62247017-2a769880-b3a2-11e9-89b7-808dfb80e20b.png)

### Structured Volume
![str](https://user-images.githubusercontent.com/2772687/62247033-36625a80-b3a2-11e9-87dd-97482360140d.png)

Notice the jagged edged and misses caused by low sampling rate. Sometimes whole chunks will be missing. "samplingRate" has no effect.

**Comment by timrowley** [comment]
Hi.  Sorry for the delay getting back to you.  Volume rendering is undergoing large changes in OSPRay 2.  I'm working on the unstructured volumes and we are working on sampling improvements for these.  From the issues you've been filing it appears you have some interesting unstructured datasets.  Would it be possible to share any of them with us for internal testing?  Thanks!

**Comment by paulmelis** [comment]
Is the v2 API with respect to volumes currently in flux as well? For example, parameters `gradientShadingEnabled`, `singleShade` and `adaptiveSampling` all seem to be missing from the code, `preIntegration` is now a parameter on the transfer function instead of the volume, etc.

**Comment by StasJ** [comment]
@timrowley I have some unstructured datasets I can gladly share with you, however I cannot post them publicly. Please let me know where I should contact you by email.

**Comment by jeffamstutz** [comment]
All sampling rate concerns are now a renderer parameter and intentionally do not affect isosurfaces, as isosurface intersection is now entirely Open VKL's job. We have made improvements with VKL's isosurfacing code, so testing again on OSPRay v2.0 should show improvements.

Pinging @gregjohnson here for reference.
