### ISSUE TITLE
Isosurface with unstructured wedge grid render hangs

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#343]
I have an unstructured grid with 5218112 wedge cells for which I am trying to render an isosurface (1spp, no ambient occlusion). 80% of renders take less than a second. 20% of the time `ospRenderFrame` will never return.

This problem does not appear to occur when rendering a volume of the same grid. It also does not appear to be a problem with hexahedral cells.

I also tried reversing the winding order to no avail.

**Comment by johguenther** [comment]
Quick update: we can reproduce the hang (right now only when using the pathtracer, but should be the same root cause).

**Comment by johguenther** [comment]
Several issues related to hangs with isosurfaces of Unstructured volumes are resolved now. We still witness extreme performance drops  (10x to 100x) in some situations (e.g. camera is close to the isosurface, with shadows enabled).
