### ISSUE TITLE
Ambient occlusion does not work on volumes

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#345]
In my current setup, ambient occlusion works with geometries.

`aoTransparencyEnabled` does not have an impact
`singleShade` does not have an impact
`gradientShadingEnabled` is set to true

If only one sample is used, black spots appear on the border of the volume but these go away as samples are increased.

![ao](https://user-images.githubusercontent.com/2772687/62400972-765e4480-b53e-11e9-8034-3df3d16efcec.png)

The white area is the same bug as in #335

**Comment by jeffamstutz** [comment]
All ambient lighting features in volumes are implemented in the `pathtracer`, thus this is now obsolete.
