### ISSUE TITLE
Embree 3.6.0 not compatible with OSPRay

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#349]
After upgrading my Arch Linux home system I noticed none of my OSPRay renderings where showing anything anymore, not even the samples included with OSPRay itself. Turned out I was suddenly using OSPRay against Embree 3.6.0. Downgrading Embree to 3.5.2 gave me back correct rendering. 

This might be a quirk in my particular setup, as my Embree, ISPC and TBB come from Arch packages, while I build OSPray manually. I did not recompile OSPRay against the new Embree version, perhaps that would have solved the issue?

**Comment by jeffamstutz** [comment]
It looks like Embree v3.6.0 broke binary compatibility with Embree v3.x (unintentional), so we are internally figuring out how to best handle this.

On top of that, it looks like Embree v3.6.0 changes don't compile with OSPRay at all, so there may need to be additional changes necessary to at least enable compiling against it.

In the mean time, staying on Embree <= v3.5.2 is the only option. Once we do have fixes, it will at least require updates to OSPRay, which at this point will only be on `devel` (no back porting to v1.8.x is planned).

We will use this thread to keep people up to date with this issue, sorry for the hassle!

**Comment by jeffamstutz** [comment]
We now check during CMake build configuration if an incompatible Embree (i.e. `v3.6.0`) is used and generate an appropriate error in `v2.0.0-alpha`.
