### ISSUE TITLE
Update demos

### ISSUE THREAD

**Issue by pavolzetor** [ospray/OSPRay#36]
Some of the [examples](http://ospray.github.io/demos.html) (Heptane, Forrest, probably more) do not work with 0.9 version. Please update them.

**Comment by jeffamstutz** [comment]
We check all of the posted demos as a part of our release process. Do you have any additional information, such as build configuration or error messages?

**Comment by pavolzetor** [comment]
Sorry, it seems to work now and it was long ago I forgot what was the problem.
