### ISSUE TITLE
Question on new ospNewData signature

### ISSUE THREAD

**Issue by paulmelis** [ospray/ospray#363]
In bcecfe6577bad4b0a689196a3d6d485d1c4e1dd4 `ospNewData` was changed from

```
OSPRAY_INTERFACE OSPData ospNewData(size_t numItems,
                                      OSPDataType,
                                      const void *source,
                                      uint32_t dataCreationFlags OSP_DEFAULT_VAL(0));
```

to 

```
OSPRAY_INTERFACE OSPData ospNewData(OSPDataType,
      uint32_t numItems1,
      uint32_t numItems2 OSP_DEFAULT_VAL(1),
      uint32_t numItems3 OSP_DEFAULT_VAL(1));
```

But in, for example, `apps/tutorials/ospTutorialStructuredVolume.cpp` I see calls like https://github.com/ospray/ospray/blob/9527f27984f6ba7daeb3d64df7c0d4615866ddab/apps/tutorials/ospTutorialVolumePathTracer.cpp#L189

How can that work (and compile) given the `uint32_t` parameters on `ospNewData`? Shouldn't that give precision errors on 64-bit systems due to a pointer having more bits than an `uint32_t`? 

I'm mostly trying to understand why it works :)

**Comment by paulmelis** [comment]
With respect to the explanation in the porting guide of

```
ospSetObjectAsData(group, "geometry", OSP_GEOMETRIC_MODEL, model);
```

being equal to 

```
OSPData geometricModels = ospNewSharedData1D(&model, OSP_GEOMETRIC_MODEL, 1);
ospSetObject(group, "geometry", geometricModels);
ospRelease(geometricModels);
```

The use of `ospNewSharedData1D` is a bit confusing as it suggests that `&model` must keep pointing to a valid object even after `ospSetObjectAsData()` has returned (as the lifetime of the `geometricModels` array isn't exactly known).

But looking at https://github.com/ospray/ospray/blob/9527f27984f6ba7daeb3d64df7c0d4615866ddab/ospray/api/ospray_util_impl.cpp#L156-L164

and 

https://github.com/ospray/ospray/blob/9527f27984f6ba7daeb3d64df7c0d4615866ddab/ospray/api/ospray_util_impl.cpp#L182-L196

the actual behaviour of `ospSetObjectAsData` is to copy into an opaque array

```
    OSPData src = ospNewSharedData(&model, OSP_GEOMETRIC_MODEL, 1);
    OSPData data = ospNewData(OSP_GEOMETRIC_MODEL, 1);
    ospCopyData(src, data);
    ospRelease(src);
    ospSetObject(group, "geometry", data); 
    ospRelease(data); 
```

so the normal reference counting ways can be used. Which is what I see here

https://github.com/ospray/ospray/blob/9527f27984f6ba7daeb3d64df7c0d4615866ddab/apps/ospray_testing/geometry/Boxes.cpp#L84-L89

I'm actually not even sure I convinced myself with the above explanation but I'm trying to get my head around the `ospNewSharedData1D` use

**Comment by jeffamstutz** [comment]
We ended up settling on 64-bit sizes for data arrays for `v2.x`.

Shared data represents memory from the application that OSPRay can read, which is trivially cheap to call. However, the constraint is that the application must keep that memory around as long as the OSPRay data looking at it is also valid. Opaque data objects allow these lifetimes to be separated, but populating the opaque data requires copying from a shared data (i.e. the shared data just describes the input, which could be strided!).

Hope this helps anyone reading this!
