### ISSUE TITLE
Build error: usleep(): no such symbol

### ISSUE THREAD

**Issue by ncos** [ospray/OSPRay#39]
Hi, 

When building OSPRay with MIC support, the compiler (gcc 4.9.1) says that symbol 'usleep' in /ospray/ospray/embree/common/sys/platform.cpp file is undefined. (at least in v0.9.0RC1). When I add '#include <unistd.h>' to this file, the error goes off. 

Is it my environment, or it is a bug?

**Comment by jeffamstutz** [comment]
It's a bug that is fixed in my changes to fix KNC. Will close the issue when merged.

**Comment by jeffamstutz** [comment]
This issue should be fixed now in the latest release-0.9 branch. Let us know if you continue to have issues compiling OSPRay in your environmnt.
