### ISSUE TITLE
Curves tangent buffer format

### ISSUE THREAD

**Issue by burlen** [ospray/ospray#391]
OSPRay throws an exception when "Curves" geometry supplies a tangent buffer not in `vec3f` format. However, Embree requires this buffer in `vec4f` format.

#390 fixes this issue by making OSPRay check for `vec4f`.

from the Embree docs:

`Similarly, the tangent buffer stores the derivative of each control vertex (x, y, z, r order and RTC_FORMAT_FLOAT4 format)`

https://www.embree.org/api.html#rtc_geometry_type_curve

**Comment by johguenther** [comment]
Fixed in `release-2.0.x`.
