### ISSUE TITLE
libimf.so now required for OSPray 2.0 usage?

### ISSUE THREAD

**Issue by michaellarabel** [ospray/ospray#398]
Hi, congrats with the OSPray 2.0 release.

When trying to run the OSPray 2.0 release binaries for Linux, I now get errors over being unable to load libimf.so. Is this an intentional change moving forward that the Intel compiler needs to be installed on the local systems for running OSPray?

With OSPray 1.x release binaries I never ran into this issue over libimf.so (and normally not installing the Intel compiler on those systems), so just checking if this change is intentional or was an oversight in how the OSPray 2.0.0 release binaries were generated.

Thanks,
Michael

**Comment by jeffamstutz** [comment]
This looks like an oversight, thanks for reporting it! We have a few bug fixes that warrant a v2.0.1 patch release very soon, so we will make sure this is part of it.

**Comment by michaellarabel** [comment]
Good to hear, thanks.

**Comment by michaellarabel** [comment]
Can confirm this issue is now fixed with the new OSPray 2.0.1 release binaries, thanks!
