### ISSUE TITLE
superbuild issue on mac

### ISSUE THREAD

**Issue by aowen87** [ospray/ospray#405]
I'm running into issues with the superbuild on mac. The build will complete without any errors, and I can compile an external project. However, when I try to run my project, I get the following error:

```
#ospray: INITIALIZATION ERROR --> could not open module lib ospray_module_ispc: dlopen(libospray_module_ispc.dylib, 5): Library not loaded: @rpath/libopenvkl_module_ispc_driver.dylib
  Referenced from: /Users/maguire7/Desktop/OSPRay/ospray/build2/install/ospray/lib/libospray_module_ispc.dylib
  Reason: image not found
```

Also, if I try to run one of the compiled tutorials that comes with ospray, I get a similar error:
```
dyld: Library not loaded: @rpath/libospcommon.dylib
  Referenced from: /Users/maguire7/Desktop/OSPRay/ospray/build2/install/ospray/bin/./ospTutorialCpp
  Reason: image not found
Abort trap: 6
```

I had previously installed an older version of OSPRay and did not run into these issues. Any ideas?

**Comment by aowen87** [comment]
It looks like the LD_LIBRARY_PATH just needed to be updated.

**Comment by johguenther** [comment]
Glad that it works now :-)
