### ISSUE TITLE
PluggableGeometryExample not building, Segmentation Fault and General Question

### ISSUE THREAD

**Issue by GTO2013** [ospray/ospray#407]
Hi,
I am currently researching how to build an ospray module. I have tried to compile the bilinear_patch module but it doesn't compile when you set the `OSPRAY_MODULE_BILINEAR_PATCH `flag. This is because in script/superbuild/build_ospray.cmake you are using the `BUILD_OSPRAY_CI_TESTS `cmake variable in line 144. Is this intended? 

I have also tried to run ospExamples, which ran fine on v2.0. The recent version depends on OIDN now. I have set the flags to compile that module, but when I run the ospExamples I just get a segmentation fault.

I also have a basic question: How do you do a partial build (only on changed files) without a full rebuild? 

Thank you!

**Comment by johguenther** [comment]
A very late reply, so sorry about that.

The crash of  `ospExamples` when OIDN could not be found is fixed.

Then, superbuild. It is mainly for "build once". If you like to play around with OSPRay's CMake options, you need to do that in the `ospray/build` subfolder (which superbuild created), *not* in the top-level build directory. Building there is also incremental, i.e. only changed files are re-built.
