### ISSUE TITLE
Failed to init the ospray device

### ISSUE THREAD

**Issue by iamkang2** [ospray/ospray#409]
I've got the newest source code from this git and it was built as well without any error.
But, I cannot execute the example and tutorial programs which is provided with the source in debug mode. (works fine in release mode)
All programs stopped at ospInit() function and  return  OSP_INVAILD_OPERATION (3).
What do I have to check to fix this problem?

**Comment by johguenther** [comment]
I could not reproduce the issue on Linux. If the problem still persists, try setting `OSPRAY_LOG_LEVEL=debug` and also `OSPRAY_ERROR_OUTPUT`/`OSPRAY_LOG_OUTPUT` to get more details about the error.

**Comment by johguenther** [comment]
We successfully run the `ospTestSuite` with a Debug build. Please reopen if there is sill an issue.
