### ISSUE TITLE
gradient shading of volume

### ISSUE THREAD

**Issue by iamkang2** [ospray/ospray#410]
I am trying to visualize a structured volume using `scivis` renderer.
But I couldn't find any way to enable gradient shading. 
Where can I find a description of `gradientShadingEnabled`?
I already checked the [document](http://www.ospray.org/documentation.html#volumes).

**Comment by johguenther** [comment]
Sorry for the huge delay. With version 2.0 we removed the option for gradient-based shading of volumes. You can still visualized structured volumes, maybe try the `pathtracer` (which supports volume rendering now)?

**Comment by johguenther** [comment]
FYI: we are evaluating if and how to re-add gradient shading for the SciVis renderer in OSPRay v2.x

**Comment by johguenther** [comment]
Gradient shading is now back (since v2.3). Set `gradientShadingScale` to `1.0f` on the VolumetricModel to enable it for that volume.
