### ISSUE TITLE
Why 2.0.x remove sg::importOBJ?

### ISSUE THREAD

**Issue by josenora** [ospray/ospray#423]
Hi,

I am trying to load an obj file in OSPRay 2.1.0, but realize that the sg::importOBJ had been remove since 2.0.x. 
May i ask the reason?

**Comment by johguenther** [comment]
OSPRay should focus on being the (core) rendering library, thus we split up heavier application-side code like the scene graph, file importers and the example viewer into an own project (currently alpha), OSPRay [Studio](https://github.com/ospray/ospray_studio). Please have a look there, besides the OBJ importer there is now also a (basic, continuing to be improved) glTF importer.
