### ISSUE TITLE
Suggest truncating API "changelog" in OSPRay 2.x docs PDF

### ISSUE THREAD

**Issue by tachyon-john** [ospray/ospray#424]
A very minor nit:  
  I noticed that the OSPRay 2.1.1 docs PDF posted on the web site still lists the changelog going all the way back to OSPRay 0.7.x.  Since OSPRay 2.x is a major version with non-trivial API changes, I would suggest chopping out all of the pre-2.0 material there since it's all water under the bridge now.

This would shorten the PDF as a whole by 12 pages, that at present, because they are in the front matter, everyone has to scroll past.  I don't know if Intel has a standardized corporate API doc format that requires this structure, but another scheme would be to relocate the changelog toward the end of the document, so that a new reader doesn't need to scroll past this.

I mention it since I find myself using in-browser PDF readers on an increasing basis, and while generally good, they don't always process document ToCs and intra-document linkage properly, so I sometimes end up scrolling rather than jumping to the appropriate docs section, and it's nice not to have to scroll past 20 pages of historic material that's not really what I'm usually looking for.

**Comment by johguenther** [comment]
Good point. I already shortened the changelog at the [web page](http://www.ospray.org/), should indeed do the same for the pdf.
