### ISSUE TITLE
OSPRay 2.x ospSetParam(), ospSetXxxx() don't emit error output or callback for unknown param ID strings

### ISSUE THREAD

**Issue by tachyon-john** [ospray/ospray#427]
The OSPRay 2.x documentation in the Objects section describes the details of how ospSetParam() works in the Parameters paragraph.  The docs say:
  "...  unknown parameters will simply be ignored (though a warning message will be posted). "

In my testing, neither OSPRay itself, nor my registered error message callback yield any output when I pass clearly bogus parameter ID strings, e.g.:
`
ospSetFloat(ospRenderer, "completelybogus", 37.0);      
int bogosity = 42;
ospSetParam(ospRenderer, "alsobogus", OSP_INT, &bogosity);
ospCommit(ospRenderer);
`

I noticed this simply because I continue to find places in my OSPRay 2.x renderer implementation where I still had an out-of-date parameter string leftover from OSPRay 1.x.

Best,
  John

**Comment by paulmelis** [comment]
@tachyon-john I guess this could be the same underlying issue with `logLevel` as in #428 causing lack of error reporting?

**Comment by tachyon-john** [comment]
Yes, it seemed so in my testing last night.

**Comment by johguenther** [comment]
OK, closing this as duplicate and re-purpose #428 to fix documentation of loglevel.
