### ISSUE TITLE
OSX distributed binaries missing/broken symlinks

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#435]
In the `ospray-2.1.1.x86_64.macosx.zip` and `ospray-2.1.0.x86_64.macosx.zip` distributions, some symlinks are missing and some are broken causing the linker to fail.

**Comment by Twinklebear** [comment]
@jeffamstutz I remember we had the same issue on the Linux tarball releases, but forget the fix we found there (some flag for tar?)

**Comment by StasJ** [comment]
The same issue exists for the 2.2.0 release.
