### ISSUE TITLE
SciVis ambient occlusion does not work for volumes

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#438]
None of the AO parameters make any difference.

**Comment by carsonbrownlee** [comment]
gradient shading and volumetric lighting were taken out of ospray 2, which ao was tied to for volumes previously in scivis.  Gradient shading will be added back in upcoming releases, but it isn't clear if we will add AO back in scivis.  For more advanced lighting with volumes, we would recommend using the path tracer.

**Comment by StasJ** [comment]
@carsonbrownlee I see. I knew that lighting was removed from volumes in the SciVis renderer but I interpreted the documentation as saying that AO was still supported for volumes:

> SciVis [...] supports volume rendering and ambient occlusion (AO)

For our application, AO is less important however we are looking forward to the re-addition of gradient shading!

**Comment by johguenther** [comment]
Implemented in v2.3.
