### ISSUE TITLE
Running the debug version of ospModelViewer crashes on Windows

### ISSUE THREAD

**Issue by florianlink** [ospray/OSPRay#44]
The problem is that rtcSetErrorFunction is called at multiple places before rtcInit() is called,
namely in 

Device::Device() 
LocalDevice::LocalDevice(int *_ac, const char **_av)

This will then run into assert(g_device);

RTCORE_API void rtcSetErrorFunction(RTCErrorFunc func) 
  {
    RTCORE_CATCH_BEGIN;
    RTCORE_TRACE(rtcSetErrorFunction);
    assert(g_device);
    if (g_device) g_device->error_function = func;
    RTCORE_CATCH_END(g_device);
  }

**Comment by johguenther** [comment]
Hi Florian,
this issue is already fixed in branch `devel` and `release-0.9`. To have the fix in `master` as well please `cherry-pick` commit bb346459.

Best regards,
  Johannes
