### ISSUE TITLE
Enabling a clipping geometry for a volume breaks map_maxDepth

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#445]
Volume with an OpenGL rendered plane inside of it:

![ok](https://user-images.githubusercontent.com/2772687/86855828-63ba8c80-c078-11ea-98d2-29363e0ae81e.png)

After enabling clipping geometry for the volume:

![bad](https://user-images.githubusercontent.com/2772687/86855857-73d26c00-c078-11ea-9e22-c26672dfe1aa.png)

Clipping geometry (normals inverted so outside is clipped):

![geom](https://user-images.githubusercontent.com/2772687/86855869-7b921080-c078-11ea-980f-79b001763651.png)

**Comment by johguenther** [comment]
Fixed in `devel` (66ed5bfd0116164b72eb268696ad08a92f0aa8f8).
