### ISSUE TITLE
x3d files larger than 2GB can not be loaded on Windows

### ISSUE THREAD

**Issue by florianlink** [ospray/OSPRay#45]
The problem is the usage of ftell() in apps/common/XML.cpp, which only support 32 bits.

**Comment by florianlink** [comment]
I attached a patch:

[xml.txt](https://github.com/ospray/OSPRay/files/136424/xml.txt)

**Comment by johguenther** [comment]
Hi Florian,
thanks for reporting. The fix is in `release-0.9` and in `devel`.

Best regards,
  Johannes
