### ISSUE TITLE
Unable to build ospTutorial.cpp following your instructions, neither on Windows nor on Linux

### ISSUE THREAD

**Issue by cwxcwx0319** [ospray/ospray#451]
I have succeeded in building ospray using super build.
However I was unable to build some examples.

Following your instructions in ospTutorial.cpp:
/* This is a small example tutorial how to use OSPRay in an application.
 *
 * On Linux build it in the build_directory with
 *   g++ ../apps/ospTutorial/ospTutorial.cpp -I ../ospray/include \
 *       -I ../../rkcommon -L . -lospray -Wl,-rpath,. -o ospTutorial
 * On Windows build it in the build_directory\$Configuration with
 *   cl ..\..\apps\ospTutorial\ospTutorial.cpp /EHsc -I ..\..\ospray\include ^
 *      -I ..\.. -I ..\..\..\rkcommon ospray.lib
 */

The first issue: The code in ospTutorial.cpp does not seem to include headers of rkcommon, so the compiler showed error "error: ‘rkcommon’ has not been declared"
The next issue: I manually added "#include <rkcommon/common.h>" and "#include <rkcommon/math/vec.h", the compiler said "error: static assertion failed: Only types corresponding to OSPDataType values can be set as elements in OSPRay Data arrays. NOTE: Math types (vec, box, linear, affine) must be inferrable as OSP_* enums, which are defined by the OSPTYPEFOR_SPECIALIZATION() macro."

These issues occur both on Windows(Visual Studio 2019 toolchains) and Linux(GCC/G++ toolchains). Similar issues also come from ospExample.cpp.
 
What should I do?

**Comment by cwxcwx0319** [comment]
Examples which does not directly use rkcommon could be compiled successfully.

**Comment by johguenther** [comment]
Thanks for reporting and sorry for the inconveniences. 

The build instructions in `ospTutorial.cpp`  assume that [rkcommon](https://www.github.com/ospray/rkcommon) is present in a directory right "next to" the OSPRay directory, because OSPRay does not ship with rkcommon headers.

**Comment by johguenther** [comment]
I added some clarifications to the documentation. Please re-open if there are further questions.
