### ISSUE TITLE
AMR tests not exercised

### ISSUE THREAD

**Issue by timsandstrom** [ospray/ospray#452]
[which is an awesome capability to have, thanks!]

none of the tests exercise the AMR capability, and I know this because 

ospray/apps/common/ospray_testing/builders/GravitySpheresVolume.cpp 

has a small typo [which I found by setting asAMR=true]

volume.setParam("block.cellWidth", cpp::CopiedData(cellWidths));

which should probably be [or similar]:

volume.setParam("cellWidth", cpp::CopiedData(cellWidths));

**Comment by johguenther** [comment]
wow, thanks for reporting &ndash; an oversight when we changed the volume parameter name
