### ISSUE TITLE
Feature Request: Add Height/Bump Mapping to Principled Material

### ISSUE THREAD

**Issue by mconti1527** [ospray/ospray#458]
I am a heavy user/developer of OSPRay on Paraview and one feature that would be great to have is have principled materials support height/bump mapping as it would greatly add to the realism we could achieve.

As far as I am aware there is no way to do this with the current architecture, but if I am wrong please let me know.

https://en.wikipedia.org/wiki/Heightmap

Thanks,
Marston

**Comment by johguenther** [comment]
Hi Marston,
Principled already supports bump mapping (*normal* mapping), e.g. using a (three channel) texture `map_baseNormal`, for multiple layers (e.g. also `map_coatNormal`). But you are specifically referring to (Blinn) *height* mapping (single channel texture)? Easiest way would then be to convert the height map into a normal map (there are many tools for that).

Cheers,
  Johannes

**Comment by johguenther** [comment]
Please re-open if there are further questions.
