### ISSUE TITLE
Product design : NURBS & trim curves

### ISSUE THREAD

**Issue by nyue** [ospray/ospray#461]
Hi,

  I understand from a recent webinar that OSPray is used in product design and car companies (e.g. Bentley) are using it.

  Will NURBS surface and trim curves be supported geometry in the future for OSPray ?

Cheers

**Comment by johguenther** [comment]
Well, I don't think so, at least not in the near future. Best way is to tessellate NURBS into triangles (or bilinear patches). It is not clear that direct ray intersection of NURBS provides benefits over a pre-tessellated representation.
