### ISSUE TITLE
Iso-surfaces with volume texture color incorrect 

### ISSUE THREAD

**Issue by MengjiaoH** [ospray/ospray#462]
Hi, 

I am trying to render isosurfaces with volume texture so that iso-surfaces' color can correspond to volume transfer function. But the rendering result is showing colors to white. OSPRay is the master branch. I am wondering if the way of using volume texture is wrong. 
The following is the code: 
```cpp
        auto colormap = transferFcnWidget.get_colormap();
        ospray::cpp::TransferFunction transfer_function = makeTransferFunction(colormap, range);
        //! Volume
        ospray::cpp::Volume osp_volume = createStructuredVolume(volume);
        //! Volume Model
        ospray::cpp::VolumetricModel volume_model(osp_volume);
        volume_model.setParam("transferFunction", transfer_function);
        volume_model.commit();
        // gather all iso-values 
        ospray::cpp::Texture volume_texture("volume");
        volume_texture.setParam("volume", osp_volume);
        volume_texture.setParam("transferFunction", transfer_function);
        volume_texture.commit();

        ospray::cpp::Material mat("scivis", "obj");
        mat.setParam("map_kd", volume_texture);
        mat.commit();

        std::vector<float> iso_values = getAllIsoValues(volume, default_iso);
        ospray::cpp::Geometry isoGeom("isosurface");
        float temp = 0;
        isoGeom.setParam("isovalue", ospray::cpp::CopiedData(temp));
        isoGeom.setParam("volume", osp_volume);
        isoGeom.commit();

        ospray::cpp::GeometricModel isoModel(isoGeom);
        isoModel.setParam("material", mat);
        // std::vector<vec4f> colors = {vec4f(3/255.f, 15/255.f, 252/255.f, 1.f)};
        // isoModel.setParam("color", ospray::cpp::CopiedData(colors));
        isoModel.commit();

        // put the model into a group (collection of models)
	ospray::cpp::Group group;
	// group.setParam("volume", ospray::cpp::CopiedData(volume_model));
        group.setParam("geometry", ospray::cpp::CopiedData(isoModel));
	group.commit();
```
       
Thanks a lot.
![Screenshot from 2020-11-01 21-16-14](https://user-images.githubusercontent.com/21250565/97829866-7d678b80-1c88-11eb-8ddf-847d07afac98.png)

**Comment by johguenther** [comment]
The code example looks ok, except maybe that `transfer_function` and `osp_volume` is not `commit`ed. If you use the same volume for the isosurface and for the texture, then the color of the isosurface is constant by definition; thus, instead using a volume texture, it should be faster to just set the corresponding color (to the isovalue via the transfer function) to the geometric model (however, this needs some lines of code on the application side to update).

**Comment by Twinklebear** [comment]
If I remember correctly this was actually a bug in the app @MengjiaoH was writing that we resolved. Could we close this issue @MengjiaoH ?

**Comment by MengjiaoH** [comment]
Yes. This can be closed. 
Using volume texture is still not working, but it is not required for the app now. 
Thanks for helping.

**Comment by Twinklebear** [comment]
Ah I misunderstood then, we should keep this issue open if volume textures aren't working in OSPRay

**Comment by johguenther** [comment]
Please have a look at [`apps/ospTestSuite/test_volumetric.cpp`:L145ff](https://github.com/ospray/ospray/blob/master/apps/ospTestSuite/test_volumetric.cpp#L145), how volume textures are created (this is part of our test suite). Please reopen if there are still issues.
