### ISSUE TITLE
Question: Two layer material support?

### ISSUE THREAD

**Issue by WhitePhoera** [ospray/ospray#465]
I need material to draw some decals and rust above usual model texture, i can dynamically change texture of cource, but i would like to avoid it.
I read docs, but did not saw anything like that(may be missed it thou..).

from sources i saw Mix material, but for it to work it need to have map for factor, not fixed value as it now.

Anything to help me there? or at least some consideration for future?(for example i think it must not be hard to upgrade Mix to use map for factor)

**Comment by johguenther** [comment]
The Mix material already supports a texture for "`factor`" (named "`map_factor`").

**Comment by WhitePhoera** [comment]
i overlooked that. thanks for pointing that out.
