### ISSUE TITLE
Volume rendering of 16bit data

### ISSUE THREAD

**Issue by florianlink** [ospray/OSPRay#47]
I noticed that the volumes only support "uchar", "float" and "double".
I would like to use it for medical data, which is typically 16bit (or 12bit), so "uint16" would be great to have. Would it be possible to support uint16 as well?

(Currently I convert my data to float, but since that takes 32bits per voxel, I would prefer to stay at uint16).

**Comment by johguenther** [comment]
Support for short int voxel type (16bit) is already planned and will come soon.

**Comment by florianlink** [comment]
That is great news!

**Comment by jeffamstutz** [comment]
This is implemented in the latest release (v0.10.0).

**Comment by florianlink** [comment]
Thanks, that's great news!
