### ISSUE TITLE
Setting texture dimensions using c interface 

### ISSUE THREAD

**Issue by hieronymusanthonius** [ospray/ospray#473]
I got ospray running in a UWP app with a few issues. I am using the c interface and I cannot figure out how to set the texture dimensions ? Anybody a hint please?

**Comment by johguenther** [comment]
Texture dimensions are inferred from the `data` array, thus for textures use a 2D array with the dimensions of the texture image:
```
OSPData data = ospNewSharedData(texturePtr, type, width, 0, height);
```
"Type" should be a compatible type to the texture `format`, e.g.  `OSP_VEC4UC` for `OSP_TEXTURE_SRGBA`.

**Comment by johguenther** [comment]
Please reopen if you have further questions.
