### ISSUE TITLE
Using Ospray in UWP application

### ISSUE THREAD

**Issue by hieronymusanthonius** [ospray/ospray#474]
I enjoy using Ospray and I would like to use it in a UWP application for demonstration purposes.

I manage to get OSPray working on a Xbox Series X ( in developer mode).

When I want to generate a package and submit it to the Windows Verification tool I get a message that certain libraries use the desktop version of the DLLs. Would it be possible to rebuild Ospray from sources and link them with the UWP versions?

Can i use Osrpray without the ISPC, TBB, VKL  and IMGUI dlls?

**Comment by johguenther** [comment]
Yes, you can rebuild OSPRay yourself to have more control over the dependencies:
- ISPC is still required, but this is a compiler and the small runtime code is statically linked (no extra DLLs needed)
- you can avoid TBB by using the internal tasking system (controlled via CMake in rkcommon `RKCOMMON_TASKING_SYSTEM=Internal` and also in Embree `EMBREE_TASKING_SYSTEM=INTERNAL`)
- IMGUI is only needed for the example applications, disable via CMake `OSPRAY_ENABLE_APPS=OFF`
- VKL is needed for volume rendering. If you don't use volumes it is OK to don't ship the VKL DLLs. However, you'll get an error during startup that VKL could not be initialized (can be ignored, but OSPRay will crash if you use volumes). To remove the error message comment out [ospray/api/SPCDevice.cpp:L215-L255](https://github.com/ospray/ospray/blob/master/ospray/api/ISPCDevice.cpp#L215-L255). We should better add a CMake option to cleanly disable volumes.

**Comment by johguenther** [comment]
Did it work for you? Please reopen if there are further questions.

**Comment by johguenther** [comment]
The latest release v2.11 introduced the CMake variable `OSPRAY_ENABLE_VOLUMES`; disabling it removes the dependency to Open VKL.
