### ISSUE TITLE
Checking [x] show depth in ospExamples gives red frame

### ISSUE THREAD

**Issue by estan** [ospray/ospray#475]
It seems no matter which combination of scene/renderer I pick, when I check [x] show depth in ospExamples, I get a completely red frame:

![bild](https://user-images.githubusercontent.com/86675/111865286-748d0300-8966-11eb-8b8a-43c1b7af2a03.png)

Should I not get the depth channel visualized somehow?

**Comment by johguenther** [comment]
Yes, you should. And it's actually showing. The issue is, that we do not map the depth range, i.e. for objects further away than 1.0 just the saturated color is shown. It works e.g. for the `cornell_box` and moving into it a bit.

**Comment by estan** [comment]
Ah indeed:

![image](https://user-images.githubusercontent.com/86675/112196335-39f7c480-8c0b-11eb-9b9d-f0c46db00dba.png)

I was just thinking a little outside the box there.

Closing issue.
