### ISSUE TITLE
Superbuild - command line cmake flags do not get passed down to children

### ISSUE THREAD

**Issue by ARSanderson** [ospray/ospray#477]
The OS particulars:
- OS X Big Sur 11.2 
- Xcode 12.4 
- Compiler clang : Apple land version 12.0.0 
- CMake 3.19.5
- OSPRay 2.5 release

The  cmake command:
%cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ../scripts/superbuild

The issue:
rkcommon, embree, openvkl, and ospray will all fail to link their respective compiler test program because their individual and respective cmakes do get the two cmake flags set on the command line (the actual error is moot). If I edit each CMakeCache.txt and set the variables then the test file links and everything is built as expect.

The proposed fix:
The top level cmake should parse the flags it needs and pass the remaining flags down to each child.

**Comment by johguenther** [comment]
We currently forward several CMake variables of the superbuild to the CMake configuration of dependencies, including `CMAKE_PREFIX_PATH`, `CMAKE_BUILD_TYPE`, `CMAKE_CXX_COMPILER`, and `CMAKE_C_COMPILER`. This selection is manual, we could e.g. add `CMAKE_CXX_FLAGS` to this list, but this is error-prone. Is there as better (automagic) way?

**Comment by johguenther** [comment]
The top-level CMake (superbuild) file should not forward arbitrary variables. For your usecase just set the environment variables `CXXFLAGS` and `MACOSX_DEPLOYMENT_TARGET` &ndash; those will then be regarded for all (sub) projects and linking should succeed.
