### ISSUE TITLE
Supporting a transformation matrix for the volume renderer

### ISSUE THREAD

**Issue by florianlink** [ospray/ospray#48]
I did not find a discussion forum, so I write this as an issue instead.

The volume renderer seems to only support a world origin and voxel size, but not a complete
transformation matrix. When dealing with medical data, there is typically a DICOM world coordinate system, into which the volume should be transformed. This includes a translation, rotation and scale.

Does OSPRay support adding such a transformation matrix?
If not, it would be a great feature.

I am not sure if OSPRay already supports multiple volumes. If it does, the transformation matrix would
also be useful for correct rendering of multiple volumes.

**Comment by johguenther** [comment]
What should already work is to add the volume to a model and then instance that model with a transformation matrix via `ospNewInstance`.

**Comment by florianlink** [comment]
Ok, I will give that a try! So you already support multiple volumes?

**Comment by johguenther** [comment]
Yes, you can have multiple volumes in one model and also multiple models instantiated.

**Comment by florianlink** [comment]
I tried the following, but I don't see my volume (I also tried getWorldToVoxelMatrix and the transposed matrix). If I don't use the instancing and add the volume to the world, it works fine.
Did I miss something that I need to do?

 ...
 ospCommit(_volume);
  _volumeModel = ospNewModel();
  ospAddVolume(_volumeModel, _volume);
  ospCommit(_volumeModel);
  
  float mat[16];
  osp::affine3f xfm;
  inVolume.getVoxelToWorldMatrix(mat);
  xfm.l.vx = { mat[0],mat[4],mat[8] };
  xfm.l.vy = { mat[1], mat[5], mat[9] };
  xfm.l.vz = { mat[2], mat[6], mat[10] };
  xfm.p = { mat[3], mat[7], mat[11] };
  _instance = ospNewInstance(_volumeModel, xfm);
  ospCommit(_instance);
  ospAddGeometry(_world, _instance);
  ospCommit(_world);

**Comment by ingowald** [comment]
But I don't think you can currently have volumes -in- instances.

**Comment by florianlink** [comment]
I don't really need the instancing, only the transformation of the volume.

How about supporting a affine3f transformation property on volumes, instead of "gridSpacing" and "gridOrigin"?

The origin would then be affine3f.p and the grid spacing would be the length(xfm.vx), ...
This would add the missing rotation, at the extra cost of the matrix multiplication.
But maybe you can pre-transform the rays, so that this would not come at an extra cost?

**Comment by laurent-renard-int** [comment]
The affine transform on volume would be a nice feature.
Currently I modify the volume size, origin and spacing as well as the camera to take the affine transform into account but it is not a nice code and it forces me to mix data parameters (size, origin and spacing) with view parameters.

**Comment by florianlink** [comment]
Yes, I thought of such workarounds as well, but it will not work for 
multiple volumes
and it would force me to pre-transform meshes or other geometry to the 
volume voxel coordinates as well.

So affine transform would really make sense!

Am 5/19/2016 um 10:44 AM schrieb laurent-renard-int:

**Comment by laurent-renard-int** [comment]
My use case is simpler since I have only one volume. But I would totally appreciate an affine transform to clean my code.

**Comment by carsonbrownlee** [comment]
We will indeed be adding affine transforms for the volume and this is also a requirement for the VTK implementation.  This may not make it in until after our 1.0 release however.

**Comment by florianlink** [comment]
Any news on affine transformations for volumes?

**Comment by jeffamstutz** [comment]
A fix for this was implemented by @wilsonCernWq in #165.

Currently the transform is done manually as vec3f parameters on the volume, but paves the way to do this generically through ```ospNewInstance```. Converting from the current solution to use instances should be trivial for client apps wanting to transform volumes.

**Comment by johguenther** [comment]
Now supported via Groups containing Volumes and Instances (for the transformation).
