### ISSUE TITLE
Difference between "geom" and "geomAPI"?

### ISSUE THREAD

**Issue by gralkapk** [ospray/ospray#483]
During group commit, `createEmbreeScene` loops over the geometries (a bunch of curves).
However, the geometry data is stored in the `geomAPI` entry. The function, which I have referenced, fetches the `geom` entry, which is `NULL`.
Am I missing some operation that fills the `geom` instead of the `geomAPI` entry?
(Using release-2.6.x)

https://github.com/ospray/ospray/blob/6462fd89e9bd0b4692db01199f3a8651664d5496/ospray/common/Group.cpp#L17

**Comment by johguenther** [comment]
`geom` is set in `GeometricModel::commit`:

https://github.com/ospray/ospray/blob/6462fd89e9bd0b4692db01199f3a8651664d5496/ospray/geometry/GeometricModel.cpp#L27-L30

This is for backward compatibility: `geomAPI` is the geometry assigned during creation of the `GeometricModel` (the original way), which we relaxed later, where the geometry can be set as a parameter.

**Comment by gralkapk** [comment]
Thanks. Then I believe to know what the problem is.
