### ISSUE TITLE
GCC11 compilation error due to missing header "limits" in benchmark_register.h

### ISSUE THREAD

**Issue by benradel** [ospray/ospray#485]
Compilation error due to missing header "limits" in benchmark_register.h

Compiling ospray (Version 2.5, 2.6 and master) with gcc 11.1.0 leads to compilation error:

> ospray/apps/common/external/benchmark/src/benchmark_register.h:22:30: error: 'numeric_limits' is not a member of 'std'
>        22 | static const T kmax = std::numeric_limits<T>::max();

This fix adds the required header to benchmark_register.h #484

**Comment by johguenther** [comment]
Thanks for the report and PR! We are working on moving to a newer version of Google Bench, which fixed this issues with the `<limits>` header. I think this is more robust compared to patching our old copy.

**Comment by johguenther** [comment]
fixed in v2.7.0 via f82253b8201e7fd1c5885c4f6a8ec5a5ca473d57
