### ISSUE TITLE
Initialization w/o VKL

### ISSUE THREAD

**Issue by bhe-gtk** [ospray/ospray#486]
With OSPRay 2.6 the VKL libs (openvkl_module_cpu_device _*. dll) became quite large.
We don't use VKL at all. So it would be handy if OSPRay's initialization just logged an error instead of failing without the VKL DLLs.
Alternative would late binding of the VKL drivers.

**Comment by johguenther** [comment]
We are already working on a CMake configuration to have VKL support optional (see also #474). Furthermore, the huge DLLs of VKL are reduced again in its `devel` branch, thus the next release they will be of more manageable size.

**Comment by bhe-gtk** [comment]
Size has been reduced with 2.7.

**Comment by johguenther** [comment]
FYI, we'll still pursue the CMake option to optionally not depend on VKL.

**Comment by bhe-gtk** [comment]
Good to know, thank you!

**Comment by johguenther** [comment]
The latest release v2.11 introduced the CMake variable `OSPRAY_ENABLE_VOLUMES`; disabling it removes the dependency to Open VKL.
