### ISSUE TITLE
Any plans to get UDIMs working with hdOspray?

### ISSUE THREAD

**Issue by DanEnglesson** [ospray/ospray#487]
Hi,

Just wanted to check if there are any plans to get udim textures going with hdOspray?
We rely heavily on Udims in VFX and would be interesting to test out hdOspray hydra delegate with our USD assets.

Cheers,
Dan

**Comment by carsonbrownlee** [comment]
hi Dan,
thanks for the feature request, though for future issues this is better directed to the hdospray github issue list.  It doesn't seem like a major effort to add.  We'll look more into it in an upcoming overhaul.

**Comment by johguenther** [comment]
"moving" the request to  ospray/hdospray#5
