### ISSUE TITLE
Different transfer function for "slices" geometry

### ISSUE THREAD

**Issue by florianlink** [ospray/ospray#49]
I am really impressed of the various features that you added to the volume renderer!

I started using the slices geometry with the same volume that I do volume rendering on.
Since the transfer function for volume rendering and the slices is the same, I am somewhat restricted.
I would require an extra transfer function for the slices. Or is there a "cheap" way of copying the volume and setting a different transferfunction?

The same applies to the "isovalus" feature, I think it would be better to provide either an extra transferfunction for it, or to provide a list of colors with the isovalues, one color per isosurface.

**Comment by timbiedert** [comment]
What's the status on this?   A separate transfer function for isosurfaces (or as proposed simply a list of value/color pairs) would be great!

**Comment by jeffamstutz** [comment]
Hi,

We are tracking this feature request, but it hasn't been prioritized yet. We have limited resources to be able to handle all the feature requests we get, which is not limited to the list here posted on Github. I'd like to point out that we have made good progress on and will continue to support the ability to extend OSPRay within client applications, either through using the OSPRay SDK (found in the OSPRay include/ dir from an install) or by writing an "OSPRay module".

An example of a simple OSPRay module can be found here: https://github.com/jeffamstutz/module_nanort

The example implements a triangle mesh which forwards ray intersection calls to a small, header-only ray tracing library called NanoRT. While the geometry type _itself_ is not related to this topic, it is a fairly small example of how to extend OSPRay in the source tree and use it in the sample viewer. Any object type (including the implicit isosurfaces geoemtry type!) which doesn't meet your needs, you can substitute your own instead.

As always, of course, pull requests are welcome. :)

Cheers,
Jeff

**Comment by jeffamstutz** [comment]
UPDATE: we are planning on this for `v2.0`. We are going to change the nature of how objects are instantiated in a scene, making it much easier to implement this than in the current `v1.x` API.

**Comment by jeffamstutz** [comment]
UPDATE: this is implemented on `devel`, as `slices` now take an `OSPVolumeInstance` which can be a different instance than is used to render the volume itself. `OSPVolumeInstance` adds the transfer function to the volume, instead of it being a parameter on the volume itself.

**Comment by jeffamstutz** [comment]
This is officially in the `v2.0.0-alpha`.
