### ISSUE TITLE
ARM64/aarch64 support ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray#491]
I see a mention of NEON and ARM and was hoping to build OSPray on my Jetson Nano via superbuild but I got the following error.

Are the ARM building process only applicable to Apple Silicon chip and MacOS ?

```
/piconfs/systems/OSPray/head/ispc/bin/ispc: 1: /piconfs/systems/OSPray/head/ispc/bin/ispc: ELF: not found
/piconfs/systems/OSPray/head/ispc/bin/ispc: 2: /piconfs/systems/OSPray/head/ispc/bin/ispc: @@@@@@00pp@p@@@�HQ�HQ: not found
/piconfs/systems/OSPray/head/ispc/bin/ispc: 3: /piconfs/systems/OSPray/head/ispc/bin/ispc: �: not found
/piconfs/systems/OSPray/head/ispc/bin/ispc: 4: /piconfs/systems/OSPray/head/ispc/bin/ispc: Syntax error: "(" unexpected
CMake Error at common/cmake/ispc.cmake:53 (MESSAGE):
  Error executing ISPC executable
  '/piconfs/systems/OSPray/head/ispc/bin/ispc': 2
Call Stack (most recent call first):
  CMakeLists.txt:455 (INCLUDE)
```

Cheers

**Comment by Twinklebear** [comment]
Hi @nyue it is supported on any ARM CPU; however, for non Apple Silicon systems you have to build an ARM binary of the ISPC compiler: https://ispc.github.io/ first. On Apple Silicon systems you can get around this because the x86-64 binary release of the ISPC compiler runs under Rosetta 2.

**Comment by Twinklebear** [comment]
I forgot to mention, ISPC does provide a build script that'll pull LLVM and build ISPC which will make that step easier: https://github.com/ispc/ispc/blob/main/scripts/build.sh
