### ISSUE TITLE
pathtracer: colors look faded (desaturated)

### ISSUE THREAD

**Issue by baloe** [ospray/ospray#492]
With the OSPRay pathtracer (in Paraview 5.9.1) I am observing that surfaces are generally less saturated than the actual color they are painted with.

I am providing a demo over at https://discourse.paraview.org/t/7951

@demarle had a closer look at it and [wrote](https://discourse.paraview.org/t/7951/2):

> I thought at first that this was due to secondary lighting effects. That is ParaView’s default background and lights are set up nicely for primary illumination but result in too much energy overall when the secondary rays are added in. I.e. the default lights and colors are too white for the path tracers.
> 
> However I wasn’t able to compensate for that by doing things like making the environmental color black and replacing the lightkit with a single white headlight light. Also, the OSPRay ray caster and OptiX path tracers both make better, more saturated colors than OSPRay path tracer does.
> 
> So I think this is an aspect of OSPRay’s OBJ material implementation. [...]
> 
> Note to self, simply bypassing the normalization [here ](https://github.com/ospray/ospray/blob/master/ospray/render/materials/OBJ.cpp#L34) doesn’t help.

**Comment by johguenther** [comment]
Could be a gamma / sRGB conversion issue. Let me check with @demarle.

**Comment by baloe** [comment]
this is possibly the same issue here: 
https://discourse.paraview.org/t/7282

**Comment by johguenther** [comment]
Dave and I suspect it may be the missing linearization (from sRGB) for the transfer function, we continue to look into it to verify.
