### ISSUE TITLE
How to test OSPRAY_MODULE_BILINEAR_PATCH ?

### ISSUE THREAD

**Issue by nyue** [ospray/ospray#493]
I am building ospray manually (not via superbuild)

I see this option.

It builds the module so file

I noticed that when I do `make install`, the *.so file is not installed in the installation location.

Is there are particular test that will exercise this module ?

Cheers

**Comment by johguenther** [comment]
The main purpose of the bilinear patch is the demonstration of how to write a module, a plugin to extend OSPRay. We test its compilation to catch that this module needs to adapt to internal changed, but not more.

I just realize that its `README` outdated regarding loading it in `ospExampleViewer`... I think it's rather easy to adapt some of the builders in `apps/` to serve some vertex arrays to the bilinear geometry. Many of the features of former `ospExampleViewer` are now found in [OSPRay Studio](http://www.ospray.org/ospray_studio/), but not yet the bilinear patch.

**Comment by iqch** [comment]
superbuild lacks control rules to build this module. Can you add it?

**Comment by johguenther** [comment]
In the superbuild the bilinear patch module is activated via `BUILD_OSPRAY_CI_EXTRAS`.

**Comment by iqch** [comment]
Ok. It is built. But not installing. Just not copied from
building directory to CMAKE_PREFIX_INSTALL/bin
Win10/MSVS2019/tbbH18.5.672

пт, 17 сент. 2021 г. в 14:15, Johannes Günther ***@***.***>:

**Comment by johguenther** [comment]
Yes, as said, the module servers as example how to write modules. The bilinear patch geometry is not indented as first class geometry.

Is this rather a feature request, i.e., do you have use cases for bilinear patches and like to have that geometry included in the native build?

**Comment by iqch** [comment]
No, I seem, there no need to put this implementation to production, really it may be used just as a template.
To be true - it is one of hardest expansion module development process I've deal with.

**Comment by johguenther** [comment]
To install your own module you could use `ospray_install_library`, see e.g. `modules/multiDevice/CMakeLists.txt`.

We are happy to improve the dev process based on your suggestions. Please note that when writing custom modules we cannot generally guarantee that used internal APIs stay stable (which is why we encourage checking versions during module init).
