### ISSUE TITLE
Can't run ospMPIDistribTutorial on Windows with Intel oneAPI Tools

### ISSUE THREAD

**Issue by smallling** [ospray/ospray#496]
I compile **ospMPIDistribTutorial.cpp** and **ospMPIDistribTutorial.c** with Intel oneAPI Tools and run them with command **mpiexec -n 2 ospMPIDistribTutorial.exe** but failed:

> Exception thrown at 0x00007FFC812F14E9 (ospray_module_mpi.dll) in ospMPIDistribTutorial.exe: 0xC0000005: Access violation writing location 0x0000009D854963C0.

How can I fix this?

**Comment by johguenther** [comment]
Hmm. Do other MPI tutorials work, like the `ospMPIDistribTutorialSpheres`?

**Comment by smallling** [comment]
`OspMPIDistribTutorialSpheres` and `ospMPIDistribTutorialVolume` failed too. Only `ospMPIDistribTutorialReplicated` succeeded.

**Comment by Twinklebear** [comment]
I think these are probably due to the same issue as #495, but I haven't tested out my fix on Windows yet. I'll take a look there to see if that fixed it, or what else might be going on.
