### ISSUE TITLE
Provisional ANARI 1.0 API support?

### ISSUE THREAD

**Issue by oscarbg** [ospray/ospray#506]
Hi,
seems spec 1.0 API has been released:
and an Intel implementation seems coming soon based on Ospray:
"Intel supports the ANARI API with an open-source implementation based on Intel® OSPRay (part of the Intel® oneAPI Rendering Toolkit)" from:
"https://www.khronos.org/news/press/khronos-announces-public-release-of-the-anari-1.0-provisional-specification"
so just opening issue to get notified when is posted.. :-)
thanks..

**Comment by johguenther** [comment]
:-) good idea

**Comment by johguenther** [comment]
An initial (and incomplete) implementation is now available at [anari-ospray](https://github.com/ospray/anari-ospray). ANARI example scenes from the SDK all work.
