### ISSUE TITLE
Missing file in precompiled windows package?

### ISSUE THREAD

**Issue by sgpearse** [ospray/ospray#509]
Hi,

We're upgrading from Ospray 2.4 to 2.8.  In the 2.4 bundle, there is a file named `openvkl_module_ispc_driver.dll` that does not exist in the 2.8 bundle.  Our build on VisualStudio 2019 is failing, supposedly due to this missing file.  

I don't see this file referenced anywhere in our configuration, so I'm wondering if it's missing from the Windows .zip, [linked here](https://github.com/ospray/OSPRay/releases/download/v2.8.0/ospray-2.8.0.x86_64.windows.zip).

The VS2019 error message is below.  Thank you!

```
29>CPack: Create package using NSIS
29>CPack: Install projects
29>CPack: - Install project: VAPOR3 [Release]
29>CPack: -   Install component: Dependencies
29>CMake Error at C:/Users/pearse/VAPOR/build/cmake_install.cmake:36 (file):
29>  file INSTALL cannot find
29>  "C:/2019-Aug/Ospray/bin/openvkl_module_ispc_driver.dll": No such file or
29>  directory.
```

**Comment by johguenther** [comment]
In v2.8 the file is named `openvkl_module_cpu_device.dll`. Is that error coming from VAPOR's CMake files? In OSPRay we have renamed it already: [`cmake/ospray_redistribute_deps.cmake`](https://github.com/ospray/ospray/blob/master/cmake/ospray_redistribute_deps.cmake#L70).
