### ISSUE TITLE
Plane

### ISSUE THREAD

**Issue by GerryArk** [ospray/ospray#513]
I am struggling with a simple plane 

ospray::cpp::Geometry mPlane = ospray::cpp::Geometry("plane");
		rkcommon::math::vec4f plane_coefs = rkcommon::math::vec4f{ 0.0f, 0.0f, 1.0f, 0.0f };
		mPlane.setParam("plane.coefficients", plane_coefs   );
		mPlane.commit();
 

		cpp::GeometricModel model = cpp::GeometricModel(mPlane);
		OSPRayError = LastErrorMessage();
   
   this  error is printed             
    OSPRayError | #ospray: ospray::Planes must have 'plane.coefficients' 1D array with element type vec4f | QString

**Comment by johguenther** [comment]
You set a single `vec4f` value, whereas expected is an *array* of vec4f. Try changing the line to
```cpp
mPlane.setParam("plane.coefficients", ospray::cpp::CopiedData(plane_coefs));
```

**Comment by GerryArk** [comment]
Thanks,  a bit  strange to understand the array of vec4f,  but it works fine

**Comment by johguenther** [comment]
I'm glad that is works now. The rationale for the array is to allow for multiple planes within one geometry (like all other geometries support multiple primitives at once)).

**Comment by GerryArk** [comment]
Ok Clear, thanks again
