### ISSUE TITLE
SunSky help

### ISSUE THREAD

**Issue by GerryArk** [ospray/ospray#514]
I am a beginner with OSPray so putting all at work requires more than reading the docs     

Here is my SunSky  

		GetSunPosition(st.DateTime, st.latitude, st.longitude, st.north_offset, azimut, elev_angle, SunPlane);

		ospray::cpp::Light light = ospray::cpp::Light("sunSky");
 		light.setParam("direction",  Vector(SunPlane.zaxis)  );
 		light.setParam("up",  Vector(SunPlane.yaxis)  );
		light.setParam("turbidity",  st.turbidity );
		light.setParam("albedo", st.albedo );

		light.setParam("color", Color(ON_Color(200, 200, 200))); //testing this 

		light.setParam("intensityQuantity", OSP_INTENSITY_QUANTITY_SCALE);
		light.setParam("intensity", 0.025f / st.turbidity);
		light.commit();
		OSPRayError = LastErrorMessage();
		mlight_vector.push_back(light);

No error,  but in the rendering I do not see the sun light , nor  shadows, so something is wrong 
Any hint on how to detect the issue  ?

**Comment by johguenther** [comment]
Some things to check:
- The conveniance cpp-wrapper template function `setParam` deduces the `OSPDataType` from the 2nd argument via type traits. Thus, is e.g. `st.turbidity` of type `float`? And is a trait defined for `Vector` to map to `OSP_VEC3F`? For types from `glm` or `rkcommon` those are defined in headers in https://github.com/ospray/ospray/tree/master/ospray/include/ospray/ospray_cpp/ext (which need to be included).
- Is the light added to the `World` (directly, or indirectly via `Group`+`Instance`?
- Full illumination from the sky is only supported by the `pathracer` renderer.

**Comment by BruceCherniak** [comment]
Another quick check you might try.  OSPRay will set default values for all parameters.  If you comment out your parameters and simply create the `sunSky` light, do you see anything then?

**Comment by BruceCherniak** [comment]
You might check the `horizonExtension`.  Anything below the horizon is not part of the sky background.  But, you can stretch the sky dome with this value.  Or, make sure that you are looking above the horizon.

**Comment by johguenther** [comment]
Lights need to be `visible`, but this is the default. Which renderer do you use? SciVis needs to additionally have `visibleLights` on (which is off by default), the Path Tracer will show it always (if the light is `visible`). Also, if you have a bright / white `backgroundColor` set in the renderer then the sky will be "hidden".

**Comment by GerryArk** [comment]
I am using  the pathtracer ,  the background is always white in the rendering. I have set backColor to (0,0,0) 
One thing to underline is  that my environment  has Z  upvector , X-Y plane  of Horizon, how does the software get this info ?

**Comment by GerryArk** [comment]
Ok, sorry I have found again that the up vector was still wrong. Now it works fine. thanks  for your effort.
