### ISSUE TITLE
Orthographic camera & clipping geometry behaviour

### ISSUE THREAD

**Issue by NadirRoGue** [ospray/ospray#520]
Hello,
I have been testing clipping geometry with orthographic camera on our application. I found a strange behaviour when using a clipping plane that is completely perpendicular  to the orthrographic camera view.
* If the clipping geometry has inverted normals, everything is clipped until I move the camera so that is not perpendicular to the clipping plane
* If the clipping geometry does not have inverted normals, nothing is clipped until I move the camera so that is not perpendicular to the clipping plane.
I thought that might be a bug in our application, so I tried to reproduce it with the OSPRay appExamples executable. Using this patch on top of current version (2.9.0) I managed to replicate the bevaiour in the `clip_with_planes` scene

```diff
diff --git a/apps/common/ospray_testing/builders/ClippingGeometries.cpp b/apps/common/ospray_testing/builders/ClippingGeometries.cpp
index 0c0cf52e1..93b3b0fca 100644
--- a/apps/common/ospray_testing/builders/ClippingGeometries.cpp
+++ b/apps/common/ospray_testing/builders/ClippingGeometries.cpp
@@ -195,7 +195,7 @@ cpp::World ClippingGeometries::buildWorld() const
     geometry.commit();
     cPos = vec3f(-.3f, 0.f, -.3f);
   } else if (geomType == "plane") {
-    std::vector<vec4f> coefficients = {vec4f(1.0f, 1.0f, 1.0f, 0.0f)};
+    std::vector<vec4f> coefficients = {vec4f(1.0f, 0.0f, 0.0f, 0.0f)};
     geometry.setParam("plane.coefficients", cpp::CopiedData(coefficients));
     geometry.commit();
     cPos = vec3f(-.3f, .2f, -.3f);
@@ -219,7 +219,7 @@ cpp::World ClippingGeometries::buildWorld() const
   // Create clipping instance with model that has inverted normals
   {
     cpp::GeometricModel model(geometry);
-    model.setParam("invertNormals", true);
+    //model.setParam("invertNormals", true);
     model.commit();
 
     cpp::Group group;
diff --git a/apps/ospExamples/GLFWOSPRayWindow.cpp b/apps/ospExamples/GLFWOSPRayWindow.cpp
index d1923d61e..fa4f8303e 100644
--- a/apps/ospExamples/GLFWOSPRayWindow.cpp
+++ b/apps/ospExamples/GLFWOSPRayWindow.cpp
@@ -283,7 +283,8 @@ void GLFWOSPRayWindow::reshape(const vec2i &newWindowSize)
 void GLFWOSPRayWindow::updateCamera()
 {
   camera.setParam("aspect", windowSize.x / float(windowSize.y));
-  camera.setParam("stereoMode", cameraStereoMode);
+  //camera.setParam("stereoMode", cameraStereoMode);
+  camera.setParam("height", 10.f);
   const auto xfm = arcballCamera->transform();
   if (rendererType == OSPRayRendererType::PATHTRACER && cameraMotionBlur) {
     camera.removeParam("transform");
diff --git a/apps/ospExamples/GLFWOSPRayWindow.h b/apps/ospExamples/GLFWOSPRayWindow.h
index 0c13fbd25..035c11ccb 100644
--- a/apps/ospExamples/GLFWOSPRayWindow.h
+++ b/apps/ospExamples/GLFWOSPRayWindow.h
@@ -85,7 +85,7 @@ class GLFWOSPRayWindow
   cpp::Renderer rendererAO{"ao"};
   cpp::Renderer rendererDBG{"debug"};
   cpp::Renderer *renderer{nullptr};
-  cpp::Camera camera{"perspective"};
+  cpp::Camera camera{"orthographic"};
   cpp::World world;
   cpp::Light sunSky{"sunSky"};
   cpp::FrameBuffer framebuffer;

```
By commenting and un-commenting the `model.setParam("invertNormals", true);` line, I can achieve both behaviours, as showcased in the following screenshots.
* Without normals inverted:
* * Plane perpendicular to view: 
![view_perpendicular_to_plane_normals_not_inverted](https://user-images.githubusercontent.com/5183894/163426551-e4bfae7e-7c8e-42e6-8706-bbd876abdf0e.png)
* * As soon as I move the  camera a bit:
![view_not_perpendicular_to_plane_normals_not_inverted](https://user-images.githubusercontent.com/5183894/163426696-48d69f80-16c7-47ac-9ea5-3225d28ede0e.png)
 
* WIth normals inverted:
* * Plane perpendicular to view:
![Screenshot from 2022-04-14 17-40-21](https://user-images.githubusercontent.com/5183894/163426784-e741a31d-31c1-4024-bca7-4ec2c71b24a5.png)
* * As soon as I move the camera a bit:
![Screenshot from 2022-04-14 17-41-18](https://user-images.githubusercontent.com/5183894/163426821-6d720242-b783-4003-8efb-eae08b78d99f.png)

Furthermore, the clipping is not "symetrical". I would expect the second one (with inverted normals) to be the opposite clipping of the one without inverted normals, however, it seems to be clipped twice.

Am I setting something wrong or may this be a bug? If its the expected behaviour, how can I achieve clipping with orthographical camera when the planes are perpendicular to the view direction?

Kind regards.

**Comment by NadirRoGue** [comment]
I forgot to add that with perspective camera, the clipping behaves as expected, though.

**Comment by johguenther** [comment]
Thanks for reporting, this was a not-handled corner case (which however is rather common when using the orthographic camera). The fix is now in `devel` and will be part of the next release.

**Comment by NadirRoGue** [comment]
Thanks for the quick reply and support on this!.
