### ISSUE TITLE
Development branch : compilation errors

### ISSUE THREAD

**Issue by nyue** [ospray/ospray#527]
Hi,

  I am trying to build the dev branch in the hope of getting the recent MPI fixes.

  I am currently seeing the following compilation error and was wondering if there is some dependency update to build the dev branch

```
[  2%] Building ISPC object /data2/nyue/projects/OSPray/ospray/build/modules/cpu/local__render/debug/DebugRenderer.dev.o
/data2/nyue/projects/OSPray/ospray/ospray_git/modules/cpu/render/debug/DebugRenderer.ispc:9:10: fatal error: 'rkcommon/utility/random.ih' file \
not found
#include "rkcommon/utility/random.ih"
```

Cheers

**Comment by johguenther** [comment]
Please use the latest rkcommon v1.10.

**Comment by johguenther** [comment]
rkcommon v1.10 is now used in the superbuild
