### ISSUE TITLE
Installer for Ospray Studio

### ISSUE THREAD

**Issue by davidpwayne** [ospray/ospray#543]
OK, So, I'm not a developer but run a company with developers and hate to get them involved in Ospray Studio just yet. But is there an installer somewhere for Windows or Mac for Ospray Studio?  And does Ospray Studio incorporate the Intel Denoiser?

**Comment by BruceCherniak** [comment]
Hi David,

Yes, absolutely, OSPRay Studio includes installers for both Windows and macOS.  And yes, OSPRay Studio is able to use Intel Open Image Denoise.  Open Image Denoise is integrated at the OSPRay level, and OSPRay Studio takes advantage of that.  Any application that uses OSPRay is able to easily enable Open Image Denoise.

Here is a link to the most recent OSPRay Studio release and the install binaries:  https://github.com/ospray/ospray_studio/releases/tag/v0.11.1

If I may ask, why do you say "hate to get them involved in OSPRay Studio just yet"?  I am very happy to help with determining if OSPRay Studio is the right path and getting them started.  Feel free to file Studio specific issues to the Studio project (https://github.com/ospray/ospray_studio)

Best,
Bruce
