### ISSUE TITLE
transparency in scivisrenderer not right in 0.9.1

### ISSUE THREAD

**Issue by demarle** [ospray/OSPRay#55]
Looks like commit ae4890d broke transparency.
Compile vtk master against OSPRay and run ctest -R OSPRayRenderMesh to reproduce.

![screenshot from 2016-04-20 09-47-27](https://cloud.githubusercontent.com/assets/445592/14676782/f20b7260-06dc-11e6-8dd8-8bc512b2d9d7.png)

The gray sphere at 1,2 is too dark now and should look like this:
![screenshot from 2016-04-20 09-50-41](https://cloud.githubusercontent.com/assets/445592/14676883/5c95e39a-06dd-11e6-8817-6d38848d99d1.png)

**Comment by jeffamstutz** [comment]
This was fixed in commit eeb49db, which will end up in our next release (currently in devel). Thanks!

**Comment by demarle** [comment]
fix confirmed
