### ISSUE TITLE
Does the bin folder exist after compilation？

### ISSUE THREAD

**Issue by Xiong-JS** [ospray/ospray#555]
The bin folder does not exist after source code compilation and installation in the arm operating system

**Comment by johguenther** [comment]
I assume you use the `superbuild`? Variable `BUILD_DEPENDENCIES_ONLY` should be `OFF`, `BUILD_OSPRAY_APPS` should be `ON` and depending on `INSTALL_IN_SEPARATE_DIRECTORIES` the `bin` folder will be in `$CMAKE_INSTALL_PREFIX/bin` or `$CMAKE_INSTALL_PREFIX/ospray/bin`.

If this is still not the case please reopen.
