### ISSUE TITLE
Superbuild library directories are not consistent

### ISSUE THREAD

**Issue by mathstuf** [ospray/ospray#556]
When using the superbuild on a Red Hat-derived platform, some of the projects end up in `<prefix>/lib` (embree and tbb at least) while others show up in the right place (tbb (again?), openvkl, etc.). Telling projects to agree on a single `${CMAKE_INSTALL_LIBDIR}` should be preferred.

**Comment by demarle** [comment]
From: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9911
Thanks, looking...

**Comment by johguenther** [comment]
Hmm, all the superbuild dependencies get `CMAKE_INSTALL_LIBDIR` forwarded, but you explicitly need to set `CMAKE_INSTALL_LIBDIR` when configuring the supertbuild itself (which we do in the build scripts), otherwise that variable gets "randomly" set by the projects.

**Comment by mathstuf** [comment]
I tried setting it at the top level and it doesn't seem to have helped :/ . I'll need to debug what is happening in the build command a bit better later.

**Comment by demarle** [comment]
The setting only applied to depenecied that ospray's superbuild is told to build. For those that ospray's superbuild grabs binaries for, it the dependency's tarball is simply expanded.

**Comment by mathstuf** [comment]
Ah, that makes sense.
