### ISSUE TITLE
aarch64 redistributable binaries?

### ISSUE THREAD

**Issue by sgpearse** [ospray/ospray#559]
Hi, are there any plans to offer macos arm/aarch64 binaries like the one [offered for x86](https://www.ospray.org/downloads.html)?   Thanks!  Or should I rely on compiling Ospray for aarch64 for the foreseeable future?  Thanks!

**Comment by johguenther** [comment]
Turned out that Universal Binaries are not trivial to get for OSPRay, thus now separate packages for x86_64 and arm64 for OSX (like we plan for Linux and Windows).
