### ISSUE TITLE
Missing documentation.graphics.renderkit.ospray-website.git repository

### ISSUE THREAD

**Issue by Leengit** [ospray/ospray#564]
The top-level ospray repository file `.gitmodules` refers to URL `../documentation.graphics.renderkit.ospray-website.git` which is not a (publicly visible) repository relative to `github.com/ospray/ospray.git`.  Should `.gitmodules` be updated or deleted?  Although my Ubuntu build is working nonetheless, this is choking my build on Microsoft Windows.  (My build is somewhat complex in that ospray is a dependency of VTK, which is a dependency of my actual project...)

Or, if there is a build flag that disables the attempt to clone this module, would you document it somewhere?  (I tried `-DOSPRAY_INSTALL_DEPENDENCIES:BOOL=OFF` but that didn't help.)  Thank you!

**Comment by Leengit** [comment]
Is this issue deemed a mistaken report or was it addressed?  Either way please give some brief documentation here.

**Comment by johguenther** [comment]
We have a fix, but the issues was already closed automatically before I could push to this repo.

**Comment by Leengit** [comment]
I was able to disable the loading of all ospray submodules, which is just `../documentation.graphics.renderkit.ospray`, by adding `GIT_SUBMODULES ""` to the cmake `ExternalProject_Add(ospray, ...)` command in my enclosing project.  This approach requires cmake version ≥ 3.16 and `cmake_policy(SET CMP0097 NEW)`.

**Comment by johguenther** [comment]
In `devel` 2bd3b659cd7d25bc5cdb4fd26afa1238102b3184 I removed the submodule, which should solve the issue as well, shouldn't it?
