### ISSUE TITLE
Packaging failure on macOS arm64 for v2.12.0

### ISSUE THREAD

**Issue by p-linnane** [ospray/ospray#565]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging ospray v2.12.0 we are encountering a failure. We are building against ispc 1.20.0. When attempting to test the build we are receiving the following:

```
ISPCRT Error (1): Fail to load libispcrt_device_cpu.dylib library
```
It's worth nothing that this only happens on arm64, and not x86_64. Relevant GitHub Actions run can be found here: https://github.com/Homebrew/homebrew-core/actions/runs/5384684946

Relates https://github.com/Homebrew/homebrew-core/pull/134194

**Comment by johguenther** [comment]
There are no more details on why loading the dynlib fails? We have seen "undefined symbol `ISPCAlloc`" errors, which are related to https://github.com/ispc/ispc/issues/2540

**Comment by p-linnane** [comment]
I'm afraid I don't have any more details. It compiles fine. Here is the entire test block we are using to evaluate if `ospray` works correctly:
```
    (testpath/"test.c").write <<~EOS
      #include <assert.h>
      #include <ospray/ospray.h>
      int main(int argc, const char **argv) {
        OSPError error = ospInit(&argc, argv);
        assert(error == OSP_NO_ERROR);
        ospShutdown();
        return 0;
      }
    EOS

    system ENV.cc, "test.c", "-I#{include}", "-L#{lib}", "-lospray"
    system "./a.out"
```

**Comment by p-linnane** [comment]
One of our maintainers (@cho-m) fixed the issue, which indicates it's an issue with ispc:
```
    inreplace "ispcrt/CMakeLists.txt", "set(CMAKE_INSTALL_RPATH $ORIGIN)",
                                       "set(CMAKE_INSTALL_RPATH #{loader_path})"
```

**Comment by johguenther** [comment]
Thank you for the fix! I opened a ticket for ISPC.
