### ISSUE TITLE
Windows ospModelViewer.exe dependencies 

### ISSUE THREAD

**Issue by rvlietstra** [ospray/OSPRay#58]
Hi.
Great looking project!

I'm trying to get the windows binary to run.

1. I installed the intel redistributable to get libmmd.dll.

2. After that I also need embree.dll, which I got from https://github.com/embree/embree-renderer-bin/tree/v2.1_win 

3.  ospModelViewer.exe then crashes with "The procedure entry point could not be found"  which seems to be related to the embree dll being different to whats expected.

> OSPRay also heavily uses Embree; however, OSPRay directly includes its own copy of Embree, so a special installation of Embree is not required.

I assume thats not the case for the windows version ? Please help me to get this running.

Eventually I'd like to use the .lib and .h files and build a windows application with msvc, I don't have access to an intel compiler, I assume that should be possible with your binary windows release ?

Thanks!!

**Comment by johguenther** [comment]
Hi,
you used the installer / zip package of [OSPRay version 0.10.1](https://github.com/ospray/OSPRay/releases/tag/v0.10.1)? Better use it together with [Embree release 2.9.0](https://github.com/embree/embree/releases/tag/v2.9.0) – the newer (binary) versions of OSPRay do not contain Embree anymore.

Yes, you can use MSVC to develop applications using OSPRay.

(To optionally build OSPRay yourself you need CMake to create the solution files for MSVC (no Intel compiler required) and additionally ISPC and TBB, see [Building OSPRay from Source](http://www.ospray.org/getting_ospray.html#building-ospray-from-source) for details.)

**Comment by rvlietstra** [comment]
Hi,
Great thanks I built from source, for some reasons I thought I needed icc because of the ispc dependency.
