### ISSUE TITLE
superbuild for aarch64 picks wrong version of ispc

### ISSUE THREAD

**Issue by jfavre** [ospray/ospray#583]
cmake has correctly identified my system:

ccmake -DINSTALL_IN_SEPARATE_DIRECTORIES:BOOL=OFF -DBUILD_OSPRAY_APPS:BOOL=OFF  -DBUILD_GLFW:BOOL=OFF  -DBUILD_OIDN:BOOL=ON  -DBUILD_OIDN_FROM_SOURCE:BOOL=ON  -DBUILD_EMBREE_FROM_SOURCE:BOOL=ON  -DBUILD_TBB_FROM_SOURCE:BOOL=ON -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` -DDOWNLOAD_TBB=ON -DDOWNLOAD_ISPC=ON ../scripts/superbuild

BUILD_ISA_NEON=ON, yet it goes and downloads
https://github.com/ispc/ispc/archive/refs/tags/v1.20.0.zip
which fails to execute.

I manually downloaded https://github.com/ispc/ispc/releases/download/v1.22.0/ispc-v1.22.0-linux.aarch64.tar.gz and overwrote the installed ispc, which enabled me to compile ospray v2.12, which I have integrated, and tested successfully on a ParaView installation for NVIDIA GraceHopper superchips.

**Comment by johguenther** [comment]
Thanks for reporting! Fixed in 2258668f3fa0600464b584dc375297a17042c438, with that I could superbuild OSPRay on Aarch64 Linux without manual intervention.
