### ISSUE TITLE
compile problem with CLANG

### ISSUE THREAD

**Issue by hankchilds** [ospray/OSPRay#60]
I have a compile problem when building on my Mac 10.9.2 + Apple LLVM version 5.0 (clang-500.2.79).

In ospray/embree-v2.7.1/kernels/xeon/bvh/bvh.cpp, I get the compile error:

      no matching constructor for initialization of 'NodeArea'
    lst.push_back(NodeArea(root,empty));

followed by a series of additional (related) errors.  I played with the code and put each argument into its own type (to ensure this wasn't an issue of the compiler not being able to figure out which casts to perform) and had no luck ... that is, I believe the compiler has a bug.

I think the compiler is confused because the NodeArea struct is being defined within a routine in bvh.cpp.  My fix was to move NodeArea to the class definition in bvh.h.  When I did that, everything compiled fine.

**Comment by johguenther** [comment]
Hi Hank,
thanks for the report. Our plan is to not include Embree sources in OSPRay anymore, but rather directly use the [Embree packages](https://github.com/embree/embree/releases/). This already works with OSPRay v0.10.

Best regards,
  Johannes
