### ISSUE TITLE
Compile error due to ambiguous cos() call

### ISSUE THREAD

**Issue by paulmelis** [ospray/OSPRay#61]
Clang 3.8.0, CMake 3.5.2, Arch Linux. 

[ 35%] Building CXX object builddir/ospray/intel64/CMakeFiles/ospray.dir/lights/DirectionalLight.cpp.o
/data/c/ospray-git/ospray/lights/DirectionalLight.cpp:41:28: error: call to 'cos' is ambiguous
    const float cosAngle = cos(deg2rad(0.5f*angularDiameter));
                           ^~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/cmath:207:3: note: candidate function
  cos(float __x)
  ^
/data/c/ospray-git/ospray/common/../../common/math.h:100:23: note: candidate function
  __forceinline float cos  ( const float x ) { return ::cosf  (x); }
                      ^
/usr/include/bits/mathcalls.h:63:17: note: candidate function
__MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/data/c/ospray-git/ospray/common/../../common/math.h:123:24: note: candidate function
  __forceinline double cos  ( const double x ) { return ::cos  (x); }
                       ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/cmath:211:3: note: candidate function
  cos(long double __x)
  ^
1 error generated.
make[2]: *** [builddir/ospray/intel64/CMakeFiles/ospray.dir/build.make:2715: builddir/ospray/intel64/CMakeFiles/ospray.dir/lights/DirectionalLight.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: builddir/ospray/intel64/CMakeFiles/ospray.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by jeffamstutz** [comment]
Hi Paulmelis,

Thanks for the bug report! Our team saw that GCC 6 introduced some issues within OSPRay, this being one of them. We hope to have all GCC 6.x issues resolved soon before we release 1.0.

We will close this issue when it is fixed in our upstream branch, ```devel```. We will be sure to use Arch as our testing environment for this.

Cheers,
Jeff

**Comment by timbiedert** [comment]
Hi,
I'm getting the same error on Arch.  What's the status on this?
Thanks!

**Comment by jeffamstutz** [comment]
Thanks for the Edit: message, that should make it easy to fix ASAP. This is still on my short TODO list, but sounds like it's small enough to bang out today.

**Comment by jeffamstutz** [comment]
Should be fixed in ```release-1.0``` and ```devel```. Please let us know if you have any further issues!

**Comment by neok-m4700** [comment]
Hi, I have the same issue with gcc 6.2.0 clang 3.9.0 ospray release tag 1.0.0

```cpp
[ 45%] Building CXX object builddir/ospray/intel64/CMakeFiles/ospray.dir/render/simpleAO/SimpleAOMaterial.cpp.o
ospray/lights/DirectionalLight.cpp:41:28: error: call to 'cos' is ambiguous
    const float cosAngle = cos(deg2rad(0.5f*angularDiameter));
                           ^~~
<...>/gcc/lib/gcc/x86_64-pc-linux-gnu/6.2.0/../../../../include/c++/6.2.0/cmath:207:3: note: candidate function
  cos(float __x)
  ^
<...>/ospcommon/math.h:100:23: note: candidate function
  __forceinline float cos  ( const float x ) { return ::cosf  (x); }
                      ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:17: note: candidate function
__MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
<...>/ospcommon/math.h:123:24: note: candidate function
  __forceinline double cos  ( const double x ) { return ::cos  (x); }
                       ^
<...>/gcc/lib/gcc/x86_64-pc-linux-gnu/6.2.0/../../../../include/c++/6.2.0/cmath:211:3: note: candidate function
  cos(long double __x)
```

Is there any particular commit that solves the issue ?

**Comment by jeffamstutz** [comment]
Hi,

Please use our ```devel``` branch, as that represents everything that will go into our upcoming release (1.1.0), which will be out very soon. This issue should be fixed in that branch, though if you continue to see problems there, please let us know!

Cheers,
Jeff

**Comment by neok-m4700** [comment]
Thnaks @jeffamstutz, the commit fixing this issue is 23a5f89 on devel branch
