### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by rvlietstra** [ospray/OSPRay#62]
Hi.
I am rendering a volume in OSPRay which I write to a texture and then render on a full screen quad in OpenGL, I then draw other things. I need my OpenGL and OSPRay views to be the same. 

I'm having difficulty understanding why my two cameras differ. Should my model view matrix for my OpenGL camera be compatible with OSPRay ?

Thanks!

**Comment by johguenther** [comment]
Hi,
yes, it is possible to perfectly align an OpenGL camera and an OSPRay camera. For example, we do this to (depth-) composite OSPRay renderings and OpenGL renderings.
Have a look at `apps/volumeViewer/QOSPRayWindow.cpp::paintGL` and `modules/opengl/util.cpp::getOSPDepthTextureFromOpenGLPerspective` how to convert the `GL_PROJECTION_MATRIX` and `GL_MODELVIEW_MATRIX` to OSPRay's camera parameters.

Best regards,
  Johannes

**Comment by rvlietstra** [comment]
Great thanks!
