### ISSUE TITLE
Unknown DisplayCluster API call to dcStreamSetFrameIndex(..)

### ISSUE THREAD

**Issue by voidcycles** [ospray/OSPRay#64]
What version of DisplayCluster is supported?  I'm not finding a dcStreamSetFrameIndex() on any release for the tree hosted on GITHUB:

https://github.com/TACC/DisplayCluster

Is there a newer version of DisplayCluster available or pending update?  

Thanks!

**Comment by jeffamstutz** [comment]
Hi voidcycles,

A former team member had a fork of DisplayCluster with some additional changes, found here: https://github.com/gregjohnson/DisplayCluster

We are currently in the midst of re-evaluating our DisplayCluster support for our sample viewers and should hopefully have an update in OSPRay by the end of the summer. In the mean time, take a look at the above forked DisplayCluster.

Cheers,
Jeff
