### ISSUE TITLE
error: 'loadu' is not a member of 'embree::vint8

### ISSUE THREAD

**Issue by dkoerner** [ospray/OSPRay#65]
Hi,

Some internal embree avx2 headers ([vint8_avx2.h](https://github.com/ospray/OSPRay/blob/master/ospray/embree-v2.7.1/common/simd/vint8_avx2.h))  seem wrong/outdated which causes build errors when `__AVX2__` is defined by the compiler. In particular the method loadu is missing (there currently appears to be a uload function). The current version of this header file in embree seems to have this fixed: [embree:vint8_avx2.h](https://github.com/embree/embree/blob/master/common/simd/vint8_avx2.h#L77)

Best,
David

**Comment by jeffamstutz** [comment]
Hi David,

Do you have a compiler/OS combination that we could try? We have not run into this issue before with a number of different compilers (gcc, clang, icc, msvc) and various different ISAs (including AVX2).

Regardless, we will soon either update the internal Embree source, or require the use of an external Embree binary install (currently made optional with the OSPRAY_USE_EXTERNAL_EMBREE CMake flag).

Thanks,
Jeff

**Comment by dkoerner** [comment]
Hi Jeff,

short answer: 
I use gnu compiler wrapper provided by cray on version 4.9.3. I also tried 5.3 and got the same problem.

long answer:
I am trying to build ospray on crayxc40 using the gnu wrapper provided by cray:

> eslogin007:~/ospr/ospray-build> /opt/cray/craype/2.5.5/bin/CC --version
> g++ (GCC) 4.9.3 20150626 (Cray Inc.)
> ...

when forcing the native gnu compiler using CMAKE_CXX_COMPILER=g++ the error disappears:

> eslogin007:~/ospr/ospray-build> /opt/gcc/4.9.3/bin/g++ --version
> g++ (GCC) 4.9.3 20150626 (Cray Inc.)
> ...

The reason for that is that the wrapper provided by cray actually has `__AVX2__` defined while the native g++ version hasn't. This causes different branches in [avx.h](https://github.com/ospray/OSPRay/blob/master/ospray/embree-v2.7.1/common/simd/avx.h).

However, I need to be able to use the cray wrapper in order to get cmake detect MPI. This means that when forcing native g++ and setting OSPRAY_BUILD_MPI_DEVICE=ON, cmake will not find MPI and error out. Please let me know if you happen to have an answer to that...

Best,
David

**Comment by ingowald** [comment]
David,

First question: Do you by chance have a version of the intel compiler 
(and intel mpi) on that cray system? I know we are sometimes using a 
cray/aries based system at TACC, so I know it's possible to compile it 
(even including MPI); ... but using icc might be easier than dealing 
with possibly many different versions of gcc (we could then hunt down 
the gcc issue at our leisure, while you already have something that works.)

On a related note: would you be interested in a little offline email 
chat re what exactly you're trying to do w/ ospray? You're one of our 
first external users that I know of that uses a cray system, and I'd be 
curious to learn more re what exactly you want to do, and what you're 
getting out of it. If you're interested, my email is 
ingo.wald(at)intel.com...

Cheers,

Ingo

**Comment by jeffamstutz** [comment]
Hi David,

To answer your question about detecting MPI with CMake, I have had success with CMake detecting MPI  when the compiler wrappers exist in your PATH, even when CMAKE_CXX_COMPILER points to something else. However, that experience has worked with IMPI, MVAPICH2, and OpenMPI only, but I know we have successfully built OSPRay with Cray MPI at TACC (on Lonestar5). I think the key is that you always want CMAKE_C/CXX_COMPILER to be set to gcc/g++ (or icc/icpc) and have all MPI related executables (i.e. mpiexec, mpirun, etc..) on your PATH.

Normally we use environment modules that already exist on these big machines, so whatever details those may be hiding are worth documenting in our wiki. :)

Cheers,
Jeff

**Comment by Twinklebear** [comment]
Adding to what @jeffamstutz mentioned about the compiler vars OSPRay needs MPI with multithreading. I've found that for Cray MPI (at least on TACC's Lonestar5) you'll need to set `MPICH_MAX_THREAD_SAFETY=multiple` to enable thread multiple with Cray's MPICH library.

**Comment by johguenther** [comment]
Even when the MPI compiler wrappers are not in `PATH` you can manually hint their location for CMake in the variables `MPI_CXX_COMPILER` / `MPI_C_COMPILER`.

**Comment by dkoerner** [comment]
Hi Everybody,
thanks to your comments I now got ospray to compile successfully using g++/gcc with MPI. It runs on the cluster but fails to run through completely. I will investigate this more before I get back to you guys. Feels more like a problem on my end.

Thanks for pointing out the MPICH_MAX_THREAD_SAFETY variable. That saved me a lot of time!

@ingowald 
Cool, I will shoot you an email!

Best,
David
