### ISSUE TITLE
Missing cvt_uint32 that takes a float4 in DisplayWall.cpp

### ISSUE THREAD

**Issue by voidcycles** [ospray/OSPRay#66]
I can't find a definition for cvt_uint32(...) that takes a float4 as input.  Presumably this is packing and bitshifting the four channels into 4x 8bit values that fill the 32bit uint?

**Comment by carsonbrownlee** [comment]
hello, the displaywall code is considered unsupported and we are likely going to remove all  displaycluster code shortly in favor of a home grown solution. We may put it up, unmaintained, on a seperate repo for those interested.  We have just recently built and run ospray with display cluster recently, though it is very buggy.  You can fix the issue you are seeing with the below code as an example, however note that you will still need a custom repo of display cluster of GregP's to run it as the main repo on github will not work.  


/*! helper function to convert float-color into rgba-uint format */
inline uint32 cvt_uint32(const float f)
{
  return (int32)(255.f * clamp(f, 0.f, 1.f));
}

/*! helper function to convert float-color into rgba-uint format */
inline uint32 cvt_uint32(const vec4f &v)
{
  return 
    (cvt_uint32(v.x) << 0)  |
    (cvt_uint32(v.y) << 8)  |
    (cvt_uint32(v.z) << 16) |
    (cvt_uint32(v.w) << 24);
}

**Comment by voidcycles** [comment]
Great, thanks!  Yes, I'd be keen to test and contribute to your homegrown replacement depending on how it meets our needs!
