### ISSUE TITLE
Problems compiling OSPRay

### ISSUE THREAD

**Issue by samfux84** [ospray/OSPRay#67]
Hi,

I tried to compile OSPRay on our universities HPC cluster on a node, which supports avx, but not avx2. I got the following error messgage:

```
/cluster/apps/gcc/4.8.2/bin/c++  -fPIC  -fopenmp -fopenmp -fPIC -fno-strict-aliasing  -std=c++11 -Wno-narrowing -DNDEBUG -g -O3 -Wstrict-aliasing=1 -ffast-math   -shared -Wl,-soname,libospray_common.so.0 -o ../../../libospray_common.so.0.10.1 CMakeFiles/ospray_common.dir/common.cpp.o CMakeFiles/ospray_common.dir/FileName.cpp.o CMakeFiles/ospray_common.dir/sysinfo.cpp.o CMakeFiles/ospray_common.dir/malloc.cpp.o CMakeFiles/ospray_common.dir/library.cpp.o CMakeFiles/ospray_common.dir/thread.cpp.o CMakeFiles/ospray_common.dir/vec.cpp.o -ldl 
/tmp/ccLLpuDm.s: Assembler messages:
/tmp/ccLLpuDm.s:351: Error: no such instruction: `vinserti128 $1,%xmm0,%ymm0,%ymm0'
/tmp/ccLLpuDm.s:1339: Error: no such instruction: `vinserti128 $1,%xmm2,%ymm2,%ymm2'
/tmp/ccLLpuDm.s:2667: Error: suffix or operands invalid for `vpslld'
/tmp/ccLLpuDm.s:2676: Error: suffix or operands invalid for `vpor'
```

It seems that the make process tries to compile for avx2.

Do you have any idea on how to avoid this ?

Best regards

Sam

**Comment by johguenther** [comment]
Hi Sam,
that's a bit strange: gcc 4.8 supports AVX2 (and you see according code is generated), but the used `as` does not understand it, so it is probably some mismatch in the compiler/assembler tool-chain. (And even stranger: your posted line is the linking stage, compilation should already be done.)

Anyway, some workarounds:
- Set the CMake variable `OSPRAY_BUILD_ISA` to `AVX` to avoid using AVX2 altogether.
- ISA specific code is actually only used by the embedded Embree: you can also use a [precompiled Embree](http://embree.github.io/downloads.html) by setting `OSPRAY_USE_EXTERNAL_EMBREE` to `ON` (and maybe hinting its location with `embree_DIR`). This will also be the default way in newer OSPRay versions.

Best regards,
  Johannes

**Comment by samfux84** [comment]
Hi Ingo,

thank you very much for the reply. I understand, that I can also cross-compile a software with gcc/4.8.2 for several different architectures. Therefore I am also a bit surprised, that I was running into such an issue.

I tested setting OSPRAY_BUILD_ISA to AVX as you suggested. I encounter now a different problem:

```
[ 69%] Linking CXX executable ../../../ospTutorial
cd /scratch/appssf/OSPRay-0.10.1/build/builddir/ospray/intel64 && /cluster/apps/cmake/3.5.2/x86_64/bin/cmake -E cmake_link_script CMakeFiles/ospTutorial.dir/link.txt --verbose=1
/cluster/apps/gcc/4.8.2/bin/c++    -fopenmp -fopenmp -fPIC -fno-strict-aliasing  -std=c++11 -Wno-narrowing -DNDEBUG -g -O3 -Wstrict-aliasing=1 -ffast-math      CMakeFiles/ospTutorial.dir/__/apps/ospTutorial.cpp.o  -o ../../../ospTutorial -rdynamic ../../../libospray.so.0.10.1 ../../../libospray_common.so.0.10.1 ../../../libembree.so.2.7.1 ../../../libembree_sse42.a ../../../libembree_avx.a ../../../libsimd.a ../../../liblexers.a ../../../libsys.a -ldl -Wl,-rpath,/scratch/appssf/OSPRay-0.10.1/build 
../../../libembree.so.2.7.1: undefined reference to `embree::sse42::BVH4Triangle4Intersector4HybridMoeller'
../../../libembree.so.2.7.1: undefined reference to `embree::BVHN<4>::BVHN(embree::PrimitiveType const&, embree::Scene*)'
../../../libembree.so.2.7.1: undefined reference to `embree::sse42::BVH4Triangle4vMBIntersector4HybridMoeller'
../../../libembree.so.2.7.1: undefined reference to `embree::sse42::BVH4Triangle4Intersector4ChunkMoeller'
../../../libembree.so.2.7.1: undefined reference to `embree::sse42::BVH4Triangle4Intersector4ChunkMoellerNoFilter'
../../../libembree.so.2.7.1: undefined reference to `embree::sse42::BVH4VirtualIntersector4Chunk'
../../../libembree.so.2.7.1: undefined reference to `embree::TriangleMv<4>::Type::size(char const*) const'
../../../libembree.so.2.7.1: undefined reference to `embree::sse42::BVH4Triangle4iIntersector4ChunkPluecker'
../../../libospray.so.0.10.1: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unuavx'
../../../libembree.so.2.7.1: undefined reference to `embree::Bezier1i::type'
../../../libospray.so.0.10.1: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx'
```

Therefore I will try the second approach that you suggested and try to use an external precompiled version of embree. I will give you some feedback if this works, as soon as I could test it.

Best regards and thank you again.

Sam

**Comment by samfux84** [comment]
Hi Ingo,

I now used a precompiled version of embree, compiled tbb from source and afterwards OSPRay was compiling without any error message.

Thank you very much for your support.

Best regards

Sam
