### ISSUE TITLE
Missing methods in C++ wrapper interface

### ISSUE THREAD

**Issue by timbiedert** [ospray/OSPRay#70]
Since version 1.0.0 C++ users are encouraged to use the new OSPRay C++ wrapper classes in ospray_cpp.

When updating my (simple) volume rendering code, I noticed the corresponding methods for the following functions are missing:

- ospSetRegion
- ospRemoveVolume

**Comment by jeffamstutz** [comment]
Hi,

Thanks for the feedback! Those (and some other) missing functions have just been added to the ```devel``` branch and will be included in our next release. Some of the new functions will be tested via our sample apps before we make the next release, but they are at least accessible now if you build and install ```devel```. Thanks for "leaning forward" in adopting the C++ wrappers so quickly, and please let us know if you run into any further issues. Feel free to post here if you find any issues in your app.

Just FYI: there are enough small bug fixes we've been tracking that we anticipate a 1.0.1 release soon, which will include these changes. We will close this issue when they are in the next binary releases.

Cheers,
Jeff

**Comment by timbiedert** [comment]
Great, thank you! Keep up the good work! :-)

**Comment by jeffamstutz** [comment]
One additional comment to document here for others to see:

All API calls in OSPRay.h are compatible with the C++ wrappers via the .handle() call for each object. Thus to call ospSetRegion() using an ospray::cpp::volume, you could write:

```ospSetRegion(source, cpp_volume.handle(), regionCoords, regionSize)```

...where cpp_volume is an instance of ospray::cpp::volume.

**Comment by jeffamstutz** [comment]
This should be fixed now in our latest v1.1.0 release. As always, please let us know if you find any other issues!
