### ISSUE TITLE
Render subrect of framebuffer

### ISSUE THREAD

**Issue by timbiedert** [ospray/OSPRay#76]
Hi, 

is it possible to render only a given subrect of the framebuffer (for example defined by top/left and width/height)?

Thanks!

**Comment by johguenther** [comment]
Hi Tim,
this is currently not possible in OSPRay (i.e. this would be a feature request).
Do you want to refine / accumulate only some parts of the image?

Best regards,
  Johannes

**Comment by timbiedert** [comment]
Hi Johannes,
thanks for your feedback!  I want to restrict initial rendering and subsequent accumulation to a certain area of the framebuffer only.

Best,
Tim

**Comment by carsonbrownlee** [comment]
hi Tim,
this is actually enabled in OSPRay already for the perspective camera.  You can set the vec2f values "imageStart" and "imageEnd" from 0-1 to map to what region of the framebuffer to render to.  This should be moved to the other cameras at some point, but for now it is supported as long as you are using a perspective camera.

**Comment by timbiedert** [comment]
Hey, this is great! Thank you!  

Is there some kind of documentation covering all currently available parameters for the different objects in OSPRay?

**Comment by carsonbrownlee** [comment]
yes there is.  But it's not currently public unfortunately so not all that helpful:)
