### ISSUE TITLE
Overview of Voxel Rendering Structures

### ISSUE THREAD

**Issue by mrlukeparry** [ospray/OSPRay#79]
I am interested in implementing an interface for rendering the volume to use the openVDB .vdb data structures, which uses a sparse, tile based, multi-level voxel grid. Firstly are there any plans to implement a similar data structure in OSPRay? 

If not, I am trying to understand the structure of the 'volume' classes but I am unfamiliar with some of the terminology (structuredVolume, ghostBrick, blockBrick),  and an overall flow of how the volume rendering works within OSPRAY.

Do you have any information/slides or an overview that may help? I tried looking at the IDC 2015 slides, but it was more of an overview.

Kind Wishes,
Luke Parry

**Comment by ingowald** [comment]
Luke,

Well, as usual the answer is "it depends". The main (public) parts of ospray do not contain any volume types other than dense, structured volumes; but we do have some internal test modules that operate on AMR data and/or on some hierarchically compressed volume formats - that's not exactly the same as sparse, but almost ... so could probably be added rather easily.

If you're interested we can have a offline discussion on that (send me an email); I would, in particular, be interested in learning more about what exactly you'd like to do with those sparse data structures, what data you have, etc. Principally our main use cases do not need it (hence we do not support it yet), but given that we have some pieces that are very close I'd like to learn more to see what the trade-offs of adding that feature would be. Send me an email, I'd be happy to chat!

Ingo
