### ISSUE TITLE
"MIC support requires ICC" while using ICC w/Cmake

### ISSUE THREAD

**Issue by Kevo651** [ospray/OSPRay#87]
I have tried looking for this issue or answer so i am sorry if this has been answered. While compiling OSPRay 1.1.0 from source I am getting the error "MIC support requires the Intel Compiler" when I enable the option for MIC/COI support. I have Intel Parallel Studio installed and am changing the compiler option in Cmake to use ICC before I begin. I have tried using ICC for the C++ and C, only C++ and only C but the error remains the same. I am copying the git clone to a new directory each time and working from that.

MPSS is installed and working and I am able to use a pre-compiled OSPRay 0.8.0 with the COI option and it uses the MIC cards and works as it should.

What am I doing wrong?

**Comment by jeffamstutz** [comment]
Hi Kevo651,

You didn't do anything wrong, it was broken! We have created a new patch release of OSPRay fixing issues with KNC. The latest ```master``` branch should now build KNC and the COI device correctly. The way it sounds in your message above, you are doing the right things to get MIC/COI working: use ICC/ICPC via CMAKE_C[XX]_COMPILER variables, enable MIC, compile and run. Should you continue to have any issues, please let us know!

Cheers,
Jeff

P.S. - Volume rendering is still known to be broken on KNC. That issue will take more time to get working again.
