### ISSUE TITLE
make error w/icc

### ISSUE THREAD

**Issue by Kevo651** [ospray/ospray#89]
With 1.1.1 I am now able to get to the final step. But at around 2% I get an error while building "ospray/embree-v2.7.1/common/sys_xeonphi/CMakeFiles/sys_xeonphi.dir/sysinfo.cpp.o"
The error is "**icc: warning #10274: cannot find configuration for platform /intel/compilers_and_libraries_2017.0.098/linux/bin/intel64/x86_64-linux.env**
**icc: warning #10379: Problem with offload compilation environment. Offload target compiler or the supporting libraries not found**"

This looks like a problem with icc not being setup properly from what I can tell. I am using Intel Parallel Sudio 2017 and do not know it well. Is there something I need to do in order to generate the .env file?

**Comment by jeffamstutz** [comment]
Hmmm, I must admit I haven't tried the latest icc w/ our KNC build (all testing there done with 2015.3), but I haven't seen this issue before with any version of icc. Are you able to build without KNC enabled?

**Comment by Kevo651** [comment]
KNC disabled = MIC support OFF in ccmake, correct?

With this disabled the following error appears intermittently throughout the process after starting 'make'
"**icc: warning #10237: -lcilkrts linked in dynamically, static library not available.**"
But it will still finish to 100% rather than aborting.

One thing I did leave out last post by accident, I am using a trial version of Parallel Studio.

**Comment by jeffamstutz** [comment]
Correct, and the warning message #10237 is known and will be fixed. FYI, the trial version of Parallel Studio is the same a the full version, it just expires after 30 days.

My next question is: is the original icc warning causing any problems? I originally thought you were blocked by an error, but it appears to only be a warning. If it's an offload warning, it may be only a warning for icc features we are not using in OSPRay, such as the ```#pragma``` based offloading stuff. COI is a library based approach we used for offloading, which icc doesn't know about besides the library we build against.

I'll try to get the latest icc on a machine with MIC cards in it to replicate the problem soon, but it may be a week or two before I can get to it. The only suggestion I would have in the mean time would be to try using the version I've been using to check our KNC features, which is Parallel Studio 2015.3. That one worked with COI+MIC.

**Comment by Kevo651** [comment]
The original icc warning resulted in a stop of the make process, It never got past 2%. But with MIC support off it was able to finish. The #10237 was seen with MIC support OFF and still finished. While the #10274/10379 were during MIC support ON and the make process aborted there.

Would you happen to know if 2015 would still be available as a trial? I am only using it to compile for a demo so purchasing it to compile one thing is a bit much.

Thank you for your help so far btw.
