### ISSUE TITLE
Rendering using KNC coprocessor

### ISSUE THREAD

**Issue by pkudaiyar** [ospray/OSPRay#90]
How do I render those demo models shown in the web site using KNC cards? Are there any guides available?

**Comment by jeffamstutz** [comment]
Hi pkudaiyar,

If you build OSPRay and enabled the COI device (using COI from an MPSS installation), add "--osp:coi" to the command line for any of our sample viewers. That will require compiling with ICC and enabling OSPRAY_BUILD_COI_DEVICE and OSPRAY_BUILD_MIC_SUPPORT in your CMake configuration.

If you are using MPI to get to the card, you can use this guide on our wiki page here: https://github.com/ospray/OSPRay/wiki/Running-OPSRay-viewers-with-the-MPI-backend. You will still need to enable OSPRAY_BUILD_MPI_DEVICE and OSPRAY_BUILD_MIC_SUPPORT.

Let us know if you have any issues.

Cheers,
Jeff
