### ISSUE TITLE
OSPRay 1.1.1: cylinders render black when they should not

### ISSUE THREAD

**Issue by tachyon-john** [ospray/OSPRay#91]
I found that the cylinder color handling code in OSPRay 1.1.1
still seems broken in the same way that version 0.9 was earlier in the year.
Specifically, I get black cylinders even though I'm passing in a valid array of colors and color indices with the appropriate color offset.

I dug into the OSPRay code, and since I hadn't had these kinds of
problems with spheres, I compared the color handling logic in the ISPC
source code, and you can see that the spheres and cylinders
color assignment code paths are quite dissimilar:
https://github.com/ospray/OSPRay/blob/master/ospray/geometry/Spheres.ispc
https://github.com/ospray/OSPRay/blob/master/ospray/geometry/Cylinders.ispc

Spheres.ispc, line 61:
  if ((flags & DG_COLOR) && self->color_data) {
Cylinders.ispc, line 137:
  if ((flags & DG_COLOR) && self->color) {

I'm not sure why one is testing "color_data" and the other is testing
for "color", that doesn't seem to make sense, since they ought to work
in essentially the same way, they continue to diverge from there:
Spheres.ispc, lin 61:
  if ((flags & DG_COLOR) && self->color_data) {
    uint32 colorID = 0;
    if (self->offset_colorID >= 0) {
      uniform uint8 *varying spherePtr =
          self->data + self->bytesPerSphere*ray.primID;
      colorID = *((uniform uint32 *varying)(spherePtr+self->offset_colorID));
    } else {
      colorID = ray.primID;
    }
    uint32 colorAddr = self->color_offset+colorID*self->color_stride;
    dg.color = *((vec4f *)(self->color_data+colorAddr));
  }

Cylinders.ispc, line 137:
  if ((flags & DG_COLOR) && self->color) {
    if (self->offset_colorID >= 0) {
      uniform uint8 *cylinderPtr = self->data + self->bytesPerCylinder*ray.primID;
      uint32 colorID = *((uniform uint32 *varying)(cylinderPtr+self->offset_colorID));
      dg.color = self->color[colorID];
    } else {
      dg.color = self->color[ray.primID];
    }
  }

**Comment by jeffamstutz** [comment]
Hi John,

I got a chance to sit down and look at both OSPRay and VMD to see what's going on. Now without building and running VMD, I *think* I have narrowed down the issue you're having with cylinder geometry being a bug in VMD's construction of the cylinder geometry. By inspection of OSPRay, the code indeed looks correct: the difference in self->color_data and self->color is only the member variable's name (a poor inconsistency), but it is indeed used the same way in both. We are inconsistent in allowing a color array striding with spheres but not in cylinders, but it appears that VMD isn't using that feature anyway.

I believe the desired outcome is to color cylinders in the same way spheres are colored, using a per-cylinder color. (?) The easiest way to do this is to setup your cylinders the same way you do with spheres: let the primitive's index in the cylinder array be the implicit index into the color array you set. This 1) makes your spheres and cylinders setup in the same way (for the sake of consistency), 2) saves memory by not needing to have the primitiveID stored with each cylinder (the "offset_colorID" parameter on the geometry), and 3) simplifies your code which sets up cylinders (it is significantly more complicated than your spheres with offsets and indexing everywhere, which means there may be an elusive bug).

The fix should be somewhat straightforward for you to fix. Please let us know if you continue to have issues!

Cheers,
Jeff

P.S. - I will be out this week (moving), so I will likely only have very spotty access to email/code this week. Any last-minute discussion/fixes will have to come from others this week. After that I'm back in business. :)

**Comment by tachyon-john** [comment]
Jeff,
  The color-per-cylinder code in VMD is actually from Louis originally.  I think the only updates I've made were changes required to get it to compile as API changes were made to OptiX itself.  In my testing, it has always had this issue of rendering black cylinders from the outset until now, but at some point it had been working for Louis.  If the colorID field is not being used correctly, then I will take the flamethrower to this code and rewrite it from scratch in the same pattern used for spheres at present.  Like I say though, the existing color-per-cylinder code originated with Louis, and it was working for him at some previous point in time, although I have always gotten black cylinders out of it with the official OSPRay builds I have tested.  I will try rewriting per your suggestion and see if it helps.

**Comment by tachyon-john** [comment]
Jeff, Louis,
  I have rewritten the color-per-cylinder code per Jeff's suggestion, eliminating the use of the colorID field and making it follow the same pattern as the spheres do.  Having done this, I have cases where some of the cylinders are correctly rendered, and others are still rendered black.  At present, I'm not sure what could explain this remaining issue.  I'll work on it with Louis and see if we can resolve the remaining problem.

**Comment by johguenther** [comment]
Fixed in 25479b8c.

**Comment by johguenther** [comment]
I heard that commit 25479b8 fixes most, but not all black cylinders. Is the a reproducer (e.g. a cylinder start and end point plus radius) to help fix the remaining issues?

**Comment by tachyon-john** [comment]
I haven't tried your new version 25479b8 yet, so you may need to check that with whoever says it doesn't cure the problem fully.  Louis perhaps?  How does this version differ from his issue-108 branch?
I'm out of time for testing until the end of next week (preparing for a funding renewal site visit) so I'd double check your version against the issue-108 branch Louis made.  The issue-108 branch that Louis made seemed to work fine for the cases I have tried thus far.
