### ISSUE TITLE
OSPRay 1.1.1 emits console messages for spheres when diagnostic output is not enabled

### ISSUE THREAD

**Issue by tachyon-john** [ospray/OSPRay#92]
I'm getting console messages out of some internal OSPRay sphere code even though I don't have any diagnostic output enabled:

#osp: creating 'spheres' geometry, #spheres = 0
#osp: creating 'spheres' geometry, #spheres = 3762

**Comment by tachyon-john** [comment]
Apparently OSPRay is also emitting console output for cylinders as well...
#osp: creating 'cylinders' geometry, #cylinders = 2
#osp: creating 'cylinders' geometry, #cylinders = 6
#osp: creating 'cylinders' geometry, #cylinders = 3
#osp: creating 'cylinders' geometry, #cylinders = 3

**Comment by tachyon-john** [comment]
I'm still seeing this in the issue-108 branch Louis made for the cylinder fixes, BTW:
#osp: creating 'spheres' geometry, #spheres = 0
#osp: creating 'spheres' geometry, #spheres = 4
#osp: creating 'spheres' geometry, #spheres = 8
#osp: creating 'spheres' geometry, #spheres = 6
#osp: creating 'spheres' geometry, #spheres = 41571
#osp: creating 'spheres' geometry, #spheres = 358400
#osp: creating 'spheres' geometry, #spheres = 27525
#osp: creating 'cylinders' geometry, #cylinders = 2
#osp: creating 'cylinders' geometry, #cylinders = 6
#osp: creating 'cylinders' geometry, #cylinders = 3
#osp: creating 'cylinders' geometry, #cylinders = 3
#osp: creating 'cylinders' geometry, #cylinders = 921600
#osp: creating 'cylinders' geometry, #cylinders = 921600

**Comment by johguenther** [comment]
Fixed in 5c6d3666.
