### ISSUE TITLE
OSPRay 1.1.1 shades handles shadows from partially transparent surfaces differently for AO vs. direct lighting

### ISSUE THREAD

**Issue by tachyon-john** [ospray/ospray#94]
OSPray appears to treat transparent geometry differently for shadows resulting from direct lighting (e.g. from a directional light) vs. AO lighting.  For direct lighting, things appear to work more or less as I might expect.  For AO lighting, the transparent geometry seems to be treated as a complete occlusion rather than taking into account the opacity of the geometry when integrating the AO samples.

**Comment by johguenther** [comment]
Right, OSPRay intentionally treats all geometry as fully opaque for AO. Taking transparency into account as well will impact performance significantly – which would not be be acceptable for some usecases.

**Comment by tachyon-john** [comment]
For typical VMD use cases, the current behavior would be viewed by users as "broken", and they will then have to use Tachyon or OptiX to get an image that meets their expectations.  I fully understand the performance cost of taking into account the opacity of occluders when performing AO, I had to write the code for this twice already for the two renderers above, but it's a necessity for our user community.  VMD users frequently intentionally create scenes where exterior molecular surface geometry is assigned a partially transparent material, and interior molecular structures are drawn opaque.  The exterior partially transparent surface provides important context, but the interior is typically the main focus of attention, so as you might guess, it is not acceptable to have it rendered all black.  I can't think of a scenario where VMD users would accept that an RT engine would consider transparent surfaces as if they were opaque for lighting purposes.  For our purposes it would be best if VMD could enable opacity modulation of AO occlusion rays despite the performance cost, as the users will consider anything else to be "broken".

**Comment by johguenther** [comment]
I agree that black AO is quite useless. Besides transparent "hulls" the same situation is with interiors / rooms. The typical workaround (which BTW also boosts performance) is to use a short-ranged AO by lowering `aoDistance`.

Additionally we could introduce a new renderer parameter to enable slower but transparent AO.

**Comment by tachyon-john** [comment]
Yeah, I'm aware of the range-limited AO occlusion test, it was one of the OSPRay features I asked for (last year) that is also needed by VMD, in particular for doing renderings on the inside of virus capsids, proto-cells, and other scenes where the camera lies inside either a fully or mostly-closed-off region of structure that would be like standing in a closet.  Another case where I use range-limited AO is in conjunction with a clipping sphere so the user can fly down into dense molecular geometry, which is clipped away in the vicinity of the camera, and the lit from the interior for the same reasons.

For VMD it will be best to have a mode that allows proper handling of transparent surfaces, as the range-limited AO approach won't work well for cases when the user draws solvent-accessible molecular surfaces with contained atomic representations, as the boundary surface can often get very close to the geometry.  Another such case that would be problematic would be for renderings of all-atom structures docked into CryoEM density maps, where some of the atomic structure/geometry will inevitably end up in close contact or even protrude through the surface of the density map.  These are cases where you'd have to set the AO max occlusion distance to an extremely low value, to such a value that it wouldn't really behave like normal AO anymore, and there would still be weird shadows where the interior structure contacts or protrudes from the outer transparent surface.

**Comment by carsonbrownlee** [comment]
John, 
does vmd also typically use colored shadows/ao?  Or is just transparent grayscale ok?  I've been debating this for the volume renderer.

**Comment by tachyon-john** [comment]
At present VMD would be happy with transparent grayscale, and I don't expect that to change in the short-term future.  While it is easy enough to add colored shadows/AO, I think that in general the performance cost would likely outweigh its value for scientific visualization usage as in VMD.  In something like a path tracer I would expect colors to be handled correctly, but for scientific visualization I think that some of these kinds of shortcuts are appropriate.

**Comment by johguenther** [comment]
Currently all transparencies (wrt. shadows) in the SciVis renderer are grayscale, so this will also be the case for AO for consistency reasons. Actually I don't think that colored shadows will have a performance impact. The challenge is rather to provide the color information: right now we only have the alpha (scalar) channel in vertex colors and materials.

**Comment by tachyon-john** [comment]
I chose to have my RT engines use scalar alpha to save on memory bandwidth and register activity on the theory that every little bit helps.  I've had no reason to pursue RGB shadow filtering for the existing or near-term usage of my renderers, but I'd be curious to know if the folks that primarily do volume rendering (weather, CFD, etc)  think it is important for their scenes.

**Comment by tachyon-john** [comment]
Do we get a new release w/ this implemented pretty soon?   Just wondering what the release schedule looks like since this is a big deal for VMD users...

**Comment by jeffamstutz** [comment]
Perfect timing on your question. :)
