### ISSUE TITLE
OSPRay 1.1.1 linux binary releases, add symlinks from libxxx.so.2 files to libxxx.so ...

### ISSUE THREAD

**Issue by tachyon-john** [ospray/ospray#95]
To avoid troubles with linking using conventional Makefile approaches...
I believe this was mainly needed for the TBB and Embree library components packaged in the binary releases.  I don't have the package in front of me as I write this, but it'll be obvious what is needed here.

**Comment by johguenther** [comment]
Hmm, actually it is not clear to me what is needed. There are already symlinks for all `libosprayXXX.so` to `libosprayXXX.so.0` and `libosprayXXX.so.1.1.1`. There is no symlink for the (in the `tar.gz`) included `libtbb.so.2`, but this is also not required, because `libosprayXXX.so` depend on `libtbb.so.2` and not on `libtbb.so`.

**Comment by tachyon-john** [comment]
When I went to link VMD against OSPRay 1.1.1, I had to link against the libtbb stuff also to satisfy the dependencies OSPRay has on TBB, otherwise I get a linkage failure.  Since the file is named "libtbb.so.2" the linker ignores it with a normal link line, and says it can't find it.  This is why most packages create symlinks from libXXX.so.Y to libXXX.so, so that one can link simply with "-lXXX" in their Makefile.   I'm sure there are other linkage machinations one can use to get it done with the existing filenames, but adding the symlink is the conventional approach to making linkage work easily since there isn't otherwise a way to tell the linker to use libXXX.so.Y  from a normal "-l" flag.  Doing a quick google, I'm clearly not the only one that expects the symlink approach to be used to please the compilers link phase, see the below two discussions:
  http://www.ibm.com/developerworks/linux/library/l-shlibs/index.html
  http://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work

**Comment by johguenther** [comment]
Does VMD use TBB? I can link `ospTutorial` without any `-ltbb` (or `libtbb.so.2`). However, we need to clean-up the packaging of dependencies anyway.

**Comment by tachyon-john** [comment]
No VMD does not use TBB.  

If I remove TBB from the link, I get this:
/usr/local/ospray-1.1.1.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface5::internal::task_base::destroy(tbb::task&)'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_current_slot()'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libembree.so: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
make: *** [vmd_LINUXAMD64] Error 1


If I remove _both_ Embree and TBB from VMD linkage, I get this:
ld: warning: libembree.so.2, needed by /usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so, not found (try using -rpath or -rpath-link)
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcIntersect___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_avx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetUserData___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C_unv_3E_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeleteScene___un_3C_s_5B_un__RTCScene_5D__3E_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetUserData___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C_unv_3E_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeviceNewScene___un_3C_s_5B_un__RTCDevice_5D__3E_unenum_5B_RTCSceneFlags_5D_unenum_5B_RTCAlgorithmFlags_5D_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetTransform'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcIntersect___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeleteScene___un_3C_s_5B_un__RTCScene_5D__3E_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeviceNewScene___un_3C_s_5B_un__RTCDevice_5D__3E_unenum_5B_RTCSceneFlags_5D_unenum_5B_RTCAlgorithmFlags_5D_avx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetUserData___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C_unv_3E_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcOccluded___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_avx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcOccluded___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unuavx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeviceSetErrorFunction'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unuREFs_5B_unRTCBounds_5D__3E_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unuavx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewDevice'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unuavx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcOccluded___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unuREFs_5B_unRTCBounds_5D__3E_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcOccluded___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcCommit'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unuREFs_5B_unRTCBounds_5D__3E_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetBuffer'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `E_a::rtcDeleteScene___un_3C_s_5B_un__RTCScene_5D(void, long long)'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewUserGeometry___un_3C_s_5B_un__RTCScene_5D__3E_unusse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeviceNewScene___un_3C_s_5B_un__RTCDevice_5D__3E_unenum_5B_RTCSceneFlags_5D_unenum_5B_RTCAlgorithmFlags_5D_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeleteScene___un_3C_s_5B_un__RTCScene_5D__3E_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcIntersect___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewTriangleMesh'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeleteDevice'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `E_a::rtcSetBoundsFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____UM_un_3C_unv_3E_unuREFs_5B_unRTCBounds_5D(void, long long)'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcNewInstance'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeviceGetError'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_sse4'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetUserData___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C_unv_3E_avx'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcDeviceNewScene___un_3C_s_5B_un__RTCDevice_5D__3E_unenum_5B_RTCSceneFlags_5D_unenum_5B_RTCAlgorithmFlags_5D_avx2'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_avx512knl'
/usr/local/ospray-1.1.1.x86_64.linux/lib/libospray.so: undefined reference to `rtcIntersect___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_sse4'
make: *** [vmd_LINUXAMD64] Error 1

**Comment by tachyon-john** [comment]
Just a quick note that OSPRay 1.2.0 has the same issues with the need for adding symlinks for shared lib dependencies required during linkage (this is for ospray-1.2.0.x86_64.linux.tar.gz available on the github page):

First fixing linkage for Embree:
Linking  vmd_LINUXAMD64 ...
icpc: warning #10237: -lcilkrts linked in dynamically, static library not available
ld: cannot find -lembree
gmake: *** [vmd_LINUXAMD64] Error 1

Fix:
# cd /usr/local/ospray-1.2.0.x86_64.linux/lib
# ln -s libembree.so.2 libembree.so

Then on to TBB:
Linking  vmd_LINUXAMD64 ...
ln: creating symbolic link `./foobar': File exists
icpc: warning #10237: -lcilkrts linked in dynamically, static library not available
../lib/python/lib_LINUXAMD64/lib/python2.5/config/libpython2.5.a(posixmodule.o): In function `posix_tmpnam':
/home/johns/vmd/lib/python/Python-2.5.1/lib_LINUXAMD64/../Modules/posixmodule.c:6850: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
Stride.o: In function `ss_from_stride(DrawMolecule*)':
Stride.C:(.text+0x41): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/local/ospray-1.2.0.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface5::internal::task_base::destroy(tbb::task&)'
/usr/local/ospray-1.2.0.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/usr/local/ospray-1.2.0.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_current_slot()'
/usr/local/ospray-1.2.0.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const'
/usr/local/ospray-1.2.0.x86_64.linux/lib/libembree.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
/usr/local/ospray-1.2.0.x86_64.linux/lib/libembree.so: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
make: *** [vmd_LINUXAMD64] Error 1

Fix:
# cd /usr/local/ospray-1.2.0.x86_64.linux/lib
# ln -s libtbb.so.2 libtbb.so
# ln -s libtbbmalloc.so.2 libtbbmalloc.so

Success!
