### ISSUE TITLE
Compilation fails with rtc symbols undefined

### ISSUE THREAD

**Issue by yurivict** [ospray/OSPRay#96]
```
../../libospray.so.1.1.1: undefined reference to `rtcSetOccludedFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_sse4'
../../libospray.so.1.1.1: undefined reference to `rtcSetIntersectFunction___un_3C_s_5B_un__RTCScene_5D__3E_unuun_3C____un_3C_unv_3E_REFs_5B_vyRTCRay_5D_unu_3E_sse2'
../../libospray.so.1.1.1: undefined reference to `rtcDeleteScene___un_3C_s_5B_un__RTCScene_5D__3E_sse2'
../../libospray.so.1.1.1: undefined reference to `rtcIntersect___un_3C_s_5B_un__RTCScene_5D__3E_REFs_5B_vyRTCRay_5D_sse4'
...
```

On FreeBSD 11.

**Comment by johguenther** [comment]
This looks like a misconfiguration of ISPC's ISA targets; `OSPRAY_BUILD_ISA` is set to `SSE`?
These symbols should be defined in `libembree.so`. Which Embree version do you use, and internal or external Embree (i.e. the values of `OSPRAY_USE_EXTERNAL_EMBREE` and `embree_DIR`)?

**Comment by yurivict** [comment]
I use the external embree version 2.12.0.  embree_DIR=/usr/local. OSPRAY_BUILD_ISA:STRING=ALL by default.

**Comment by johguenther** [comment]
Hmm, strange. Shouldn't `embree_DIR` be set to `/usr/local/lib/cmake/embree-2.12.0` so CMake can find the Embree libs? What is your `ISPC_VERSION`?

Can you please enable `CMAKE_VERBOSE_MAKEFILE` and post the failing linker line?

And maybe the output of `nm /usr/local/lib/libembree.so.2 | fgrep rtcIntersect_` as well?

**Comment by yurivict** [comment]
/usr/local is where pre-installed embree is. Arch Linux also sets embree_DIR in a similar way: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ospray

ispc-1.9.1 is installed. ISPC_VERSION:STRING=1.9.1

The failing link line:
```
cd /usr/ports/graphics/ospray/work/OSPRay-1.1.1/apps/volumeViewer && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/ospVolumeViewer.dir/link.txt --verbose=1
/usr/bin/c++   -O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer -fPIC -fno-strict-aliasing -Wno-narrowing -std=c++11 -DNDEBUG    -O3 -Wstrict-aliasing=1   -fstack-protector CMakeFiles/ospVolumeViewer.dir/main.cpp.o CMakeFiles/ospVolumeViewer.dir/ColorMap.cpp.o CMakeFiles/ospVolumeViewer.dir/IsosurfaceEditor.cpp.o CMakeFiles/ospVolumeViewer.dir/IsovalueWidget.cpp.o CMakeFiles/ospVolumeViewer.dir/LightEditor.cpp.o CMakeFiles/ospVolumeViewer.dir/LinearTransferFunctionWidget.cpp.o CMakeFiles/ospVolumeViewer.dir/OpenGLAnnotationRenderer.cpp.o CMakeFiles/ospVolumeViewer.dir/PreferencesDialog.cpp.o CMakeFiles/ospVolumeViewer.dir/ProbeWidget.cpp.o CMakeFiles/ospVolumeViewer.dir/QOSPRayWindow.cpp.o CMakeFiles/ospVolumeViewer.dir/SliceEditor.cpp.o CMakeFiles/ospVolumeViewer.dir/SliceWidget.cpp.o CMakeFiles/ospVolumeViewer.dir/TransferFunctionEditor.cpp.o CMakeFiles/ospVolumeViewer.dir/VolumeViewer.cpp.o CMakeFiles/ospVolumeViewer.dir/moc_IsosurfaceEditor.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_IsovalueWidget.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_LightEditor.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_LinearTransferFunctionWidget.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_OpenGLAnnotationRenderer.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_PreferencesDialog.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_ProbeWidget.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_QOSPRayWindow.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_SliceEditor.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_SliceWidget.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_TransferFunctionEditor.cxx.o CMakeFiles/ospVolumeViewer.dir/moc_VolumeViewer.cxx.o  -o ../../ospVolumeViewer  -L/usr/local/lib  ../../libospray_importer.so.1.1.1 ../../libospray_module_opengl_util.so.1.1.1 ../../libospray_tfn.so.1.1.1 /usr/local/lib/qt4/libQtOpenGL.so /usr/local/lib/qt4/libQtGui.so /usr/local/lib/qt4/libQtCore.so /usr/local/lib/libGLU.so /usr/local/lib/libGL.so /usr/local/lib/libGLU.so /usr/local/lib/libGL.so -ltbbmalloc -ltbb ../../libospray.so.1.1.1 /usr/local/lib/cmake/embree-2.12.0/../../libembree.so.2.12.0 ../../libospray_common.so.1.1.1 -pthread -ltbbmalloc -ltbb -Wl,-rpath,/usr/ports/graphics/ospray/work/OSPRay-1.1.1:/usr/local/lib/qt4:/usr/local/lib: 
```

$ nm /usr/local/lib/libembree.so.2 | fgrep rtcIntersect
0000000000063fd0 t _ZN6embree21invalid_rtcIntersect1Ev
0000000000064080 t _ZN6embree21invalid_rtcIntersect4Ev
0000000000064130 t _ZN6embree21invalid_rtcIntersect8Ev
0000000000064290 t _ZN6embree21invalid_rtcIntersectNEv
00000000000641e0 t _ZN6embree22invalid_rtcIntersect16Ev
00000000000594e0 T rtcIntersect
0000000000059840 T rtcIntersect16
00000000000599e0 T rtcIntersect1M
0000000000059b30 T rtcIntersect1Mp
0000000000059600 T rtcIntersect4
0000000000059720 T rtcIntersect8
0000000000059c80 T rtcIntersectNM
0000000000059e10 T rtcIntersectNp
```

**Comment by timbiedert** [comment]
Embree from AUR recently caused issues because EMBREE_(MAX_)ISA was not set properly in its config; see this thread:   https://github.com/ospray/OSPRay/issues/81.

Manually compiling and installing Embree + OSPRay worked fine for me on Arch with default settings.

**Comment by johguenther** [comment]
OK, it seems that your installed Embree was not compiled with ISPC support (you can double-check by looking for `EMBREE_ISPC_SUPPORT` in `/usr/local/lib/cmake/embree-2.12.0/embree-config-default.cmake`). We will add this a check to OSPRays CMake files.

So, please either switch off `OSPRAY_USE_EXTERNAL_EMBREE` to compile the internal Embree, or install Embree v2.12 from https://github.com/embree/embree/releases/tag/v2.12.0 (which has ISPC support).

**Comment by ingowald** [comment]
I would also propose that for future versions we switch to doing the ispc binding in ospray, and call the embree stream API.
This way we can get rid of this dependency of requiring a special (non default) build of embree.

**Comment by johguenther** [comment]
The default build of Embree supports ISPC, it's rather the special AUR(?) package that did not have it.

**Comment by yurivict** [comment]
EMBREE_ISPC_SUPPORT=OFF in embree, because ispc wasn't even supported on FreeBSD before. I prefer using external packages, unless there is a very good reason not to. Now I am not sure if switching embree to EMBREE_ISPC_SUPPORT=ON as a default makes sense or not.

**Comment by yurivict** [comment]
With EMBREE_ISPC_SUPPORT=ON in embree this problem is gone. I suggested the embree maintainer to reset it to embree's default (ON).

Thank you for your help resolving this issue!
